// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_accel_cnn_accel_Pipeline_VITIS_LOOP_49_5_VITIS_LOOP_50_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        tile_in_address0,
        tile_in_ce0,
        tile_in_q0,
        tile_in_1_address0,
        tile_in_1_ce0,
        tile_in_1_q0,
        tile_in_2_address0,
        tile_in_2_ce0,
        tile_in_2_q0,
        tile_out_address0,
        tile_out_ce0,
        tile_out_we0,
        tile_out_d0,
        tile_out_1_address0,
        tile_out_1_ce0,
        tile_out_1_we0,
        tile_out_1_d0,
        tile_out_2_address0,
        tile_out_2_ce0,
        tile_out_2_we0,
        tile_out_2_d0,
        tile_out_3_address0,
        tile_out_3_ce0,
        tile_out_3_we0,
        tile_out_3_d0,
        tile_out_4_address0,
        tile_out_4_ce0,
        tile_out_4_we0,
        tile_out_4_d0,
        tile_out_5_address0,
        tile_out_5_ce0,
        tile_out_5_we0,
        tile_out_5_d0,
        tile_out_6_address0,
        tile_out_6_ce0,
        tile_out_6_we0,
        tile_out_6_d0,
        tile_out_7_address0,
        tile_out_7_ce0,
        tile_out_7_we0,
        tile_out_7_d0,
        tile_out_8_address0,
        tile_out_8_ce0,
        tile_out_8_we0,
        tile_out_8_d0,
        tile_out_9_address0,
        tile_out_9_ce0,
        tile_out_9_we0,
        tile_out_9_d0,
        tile_out_10_address0,
        tile_out_10_ce0,
        tile_out_10_we0,
        tile_out_10_d0,
        tile_out_11_address0,
        tile_out_11_ce0,
        tile_out_11_we0,
        tile_out_11_d0,
        tile_out_12_address0,
        tile_out_12_ce0,
        tile_out_12_we0,
        tile_out_12_d0,
        tile_out_13_address0,
        tile_out_13_ce0,
        tile_out_13_we0,
        tile_out_13_d0,
        tile_out_14_address0,
        tile_out_14_ce0,
        tile_out_14_we0,
        tile_out_14_d0,
        tile_out_15_address0,
        tile_out_15_ce0,
        tile_out_15_we0,
        tile_out_15_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] tile_in_address0;
output   tile_in_ce0;
input  [7:0] tile_in_q0;
output  [9:0] tile_in_1_address0;
output   tile_in_1_ce0;
input  [7:0] tile_in_1_q0;
output  [9:0] tile_in_2_address0;
output   tile_in_2_ce0;
input  [7:0] tile_in_2_q0;
output  [9:0] tile_out_address0;
output   tile_out_ce0;
output   tile_out_we0;
output  [7:0] tile_out_d0;
output  [9:0] tile_out_1_address0;
output   tile_out_1_ce0;
output   tile_out_1_we0;
output  [7:0] tile_out_1_d0;
output  [9:0] tile_out_2_address0;
output   tile_out_2_ce0;
output   tile_out_2_we0;
output  [7:0] tile_out_2_d0;
output  [9:0] tile_out_3_address0;
output   tile_out_3_ce0;
output   tile_out_3_we0;
output  [7:0] tile_out_3_d0;
output  [9:0] tile_out_4_address0;
output   tile_out_4_ce0;
output   tile_out_4_we0;
output  [7:0] tile_out_4_d0;
output  [9:0] tile_out_5_address0;
output   tile_out_5_ce0;
output   tile_out_5_we0;
output  [7:0] tile_out_5_d0;
output  [9:0] tile_out_6_address0;
output   tile_out_6_ce0;
output   tile_out_6_we0;
output  [7:0] tile_out_6_d0;
output  [9:0] tile_out_7_address0;
output   tile_out_7_ce0;
output   tile_out_7_we0;
output  [7:0] tile_out_7_d0;
output  [9:0] tile_out_8_address0;
output   tile_out_8_ce0;
output   tile_out_8_we0;
output  [7:0] tile_out_8_d0;
output  [9:0] tile_out_9_address0;
output   tile_out_9_ce0;
output   tile_out_9_we0;
output  [7:0] tile_out_9_d0;
output  [9:0] tile_out_10_address0;
output   tile_out_10_ce0;
output   tile_out_10_we0;
output  [7:0] tile_out_10_d0;
output  [9:0] tile_out_11_address0;
output   tile_out_11_ce0;
output   tile_out_11_we0;
output  [7:0] tile_out_11_d0;
output  [9:0] tile_out_12_address0;
output   tile_out_12_ce0;
output   tile_out_12_we0;
output  [7:0] tile_out_12_d0;
output  [9:0] tile_out_13_address0;
output   tile_out_13_ce0;
output   tile_out_13_we0;
output  [7:0] tile_out_13_d0;
output  [9:0] tile_out_14_address0;
output   tile_out_14_ce0;
output   tile_out_14_we0;
output  [7:0] tile_out_14_d0;
output  [9:0] tile_out_15_address0;
output   tile_out_15_ce0;
output   tile_out_15_we0;
output  [7:0] tile_out_15_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln49_fu_363_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [9:0] empty_25_fu_430_p2;
reg   [9:0] empty_25_reg_517;
wire   [63:0] p_cast_fu_452_p1;
reg   [63:0] p_cast_reg_522;
reg   [63:0] p_cast_reg_522_pp0_iter3_reg;
reg   [7:0] conv_reg_557;
wire    ap_block_pp0_stage0;
reg   [5:0] x_fu_86;
wire   [5:0] add_ln50_fu_436_p2;
wire    ap_loop_init;
reg   [5:0] y_fu_90;
wire   [5:0] select_ln49_1_fu_406_p3;
reg   [10:0] indvar_flatten6_fu_94;
wire   [10:0] add_ln49_1_fu_369_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten6_load;
reg    tile_in_ce0_local;
reg    tile_in_1_ce0_local;
reg    tile_in_2_ce0_local;
reg    tile_out_we0_local;
reg    tile_out_ce0_local;
reg    tile_out_1_we0_local;
reg    tile_out_1_ce0_local;
reg    tile_out_2_we0_local;
reg    tile_out_2_ce0_local;
reg    tile_out_3_we0_local;
reg    tile_out_3_ce0_local;
reg    tile_out_4_we0_local;
reg    tile_out_4_ce0_local;
reg    tile_out_5_we0_local;
reg    tile_out_5_ce0_local;
reg    tile_out_6_we0_local;
reg    tile_out_6_ce0_local;
reg    tile_out_7_we0_local;
reg    tile_out_7_ce0_local;
reg    tile_out_8_we0_local;
reg    tile_out_8_ce0_local;
reg    tile_out_9_we0_local;
reg    tile_out_9_ce0_local;
reg    tile_out_10_we0_local;
reg    tile_out_10_ce0_local;
reg    tile_out_11_we0_local;
reg    tile_out_11_ce0_local;
reg    tile_out_12_we0_local;
reg    tile_out_12_ce0_local;
reg    tile_out_13_we0_local;
reg    tile_out_13_ce0_local;
reg    tile_out_14_we0_local;
reg    tile_out_14_ce0_local;
reg    tile_out_15_we0_local;
reg    tile_out_15_ce0_local;
wire   [0:0] icmp_ln50_fu_392_p2;
wire   [5:0] add_ln49_fu_386_p2;
wire   [4:0] empty_fu_414_p1;
wire   [5:0] select_ln49_fu_398_p3;
wire   [9:0] tmp_5_fu_418_p3;
wire   [9:0] select_ln49_cast_fu_426_p1;
wire  signed [8:0] tile_in_load_cast_fu_458_p1;
wire  signed [8:0] tile_in_2_load_cast_fu_466_p1;
wire   [8:0] tmp5_fu_470_p2;
wire  signed [8:0] tile_in_1_load_cast_fu_462_p1;
wire   [8:0] sum_fu_476_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 x_fu_86 = 6'd0;
#0 y_fu_90 = 6'd0;
#0 indvar_flatten6_fu_94 = 11'd0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln49_fu_363_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_94 <= add_ln49_1_fu_369_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_94 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_fu_86 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            x_fu_86 <= add_ln50_fu_436_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            y_fu_90 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            y_fu_90 <= select_ln49_1_fu_406_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        empty_25_reg_517 <= empty_25_fu_430_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        conv_reg_557 <= {{sum_fu_476_p2[8:1]}};
        p_cast_reg_522[9 : 0] <= p_cast_fu_452_p1[9 : 0];
        p_cast_reg_522_pp0_iter3_reg[9 : 0] <= p_cast_reg_522[9 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln49_fu_363_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_in_1_ce0_local = 1'b1;
    end else begin
        tile_in_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_in_2_ce0_local = 1'b1;
    end else begin
        tile_in_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_in_ce0_local = 1'b1;
    end else begin
        tile_in_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_10_ce0_local = 1'b1;
    end else begin
        tile_out_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_10_we0_local = 1'b1;
    end else begin
        tile_out_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_11_ce0_local = 1'b1;
    end else begin
        tile_out_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_11_we0_local = 1'b1;
    end else begin
        tile_out_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_12_ce0_local = 1'b1;
    end else begin
        tile_out_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_12_we0_local = 1'b1;
    end else begin
        tile_out_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_13_ce0_local = 1'b1;
    end else begin
        tile_out_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_13_we0_local = 1'b1;
    end else begin
        tile_out_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_14_ce0_local = 1'b1;
    end else begin
        tile_out_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_14_we0_local = 1'b1;
    end else begin
        tile_out_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_15_ce0_local = 1'b1;
    end else begin
        tile_out_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_15_we0_local = 1'b1;
    end else begin
        tile_out_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_1_ce0_local = 1'b1;
    end else begin
        tile_out_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_1_we0_local = 1'b1;
    end else begin
        tile_out_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_2_ce0_local = 1'b1;
    end else begin
        tile_out_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_2_we0_local = 1'b1;
    end else begin
        tile_out_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_3_ce0_local = 1'b1;
    end else begin
        tile_out_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_3_we0_local = 1'b1;
    end else begin
        tile_out_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_4_ce0_local = 1'b1;
    end else begin
        tile_out_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_4_we0_local = 1'b1;
    end else begin
        tile_out_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_5_ce0_local = 1'b1;
    end else begin
        tile_out_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_5_we0_local = 1'b1;
    end else begin
        tile_out_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_6_ce0_local = 1'b1;
    end else begin
        tile_out_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_6_we0_local = 1'b1;
    end else begin
        tile_out_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_7_ce0_local = 1'b1;
    end else begin
        tile_out_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_7_we0_local = 1'b1;
    end else begin
        tile_out_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_8_ce0_local = 1'b1;
    end else begin
        tile_out_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_8_we0_local = 1'b1;
    end else begin
        tile_out_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_9_ce0_local = 1'b1;
    end else begin
        tile_out_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_9_we0_local = 1'b1;
    end else begin
        tile_out_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_ce0_local = 1'b1;
    end else begin
        tile_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        tile_out_we0_local = 1'b1;
    end else begin
        tile_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln49_1_fu_369_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 11'd1);

assign add_ln49_fu_386_p2 = (y_fu_90 + 6'd1);

assign add_ln50_fu_436_p2 = (select_ln49_fu_398_p3 + 6'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_25_fu_430_p2 = (tmp_5_fu_418_p3 + select_ln49_cast_fu_426_p1);

assign empty_fu_414_p1 = select_ln49_1_fu_406_p3[4:0];

assign icmp_ln49_fu_363_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_392_p2 = ((x_fu_86 == 6'd32) ? 1'b1 : 1'b0);

assign p_cast_fu_452_p1 = empty_25_reg_517;

assign select_ln49_1_fu_406_p3 = ((icmp_ln50_fu_392_p2[0:0] == 1'b1) ? add_ln49_fu_386_p2 : y_fu_90);

assign select_ln49_cast_fu_426_p1 = select_ln49_fu_398_p3;

assign select_ln49_fu_398_p3 = ((icmp_ln50_fu_392_p2[0:0] == 1'b1) ? 6'd0 : x_fu_86);

assign sum_fu_476_p2 = ($signed(tmp5_fu_470_p2) + $signed(tile_in_1_load_cast_fu_462_p1));

assign tile_in_1_address0 = p_cast_fu_452_p1;

assign tile_in_1_ce0 = tile_in_1_ce0_local;

assign tile_in_1_load_cast_fu_462_p1 = $signed(tile_in_1_q0);

assign tile_in_2_address0 = p_cast_fu_452_p1;

assign tile_in_2_ce0 = tile_in_2_ce0_local;

assign tile_in_2_load_cast_fu_466_p1 = $signed(tile_in_2_q0);

assign tile_in_address0 = p_cast_fu_452_p1;

assign tile_in_ce0 = tile_in_ce0_local;

assign tile_in_load_cast_fu_458_p1 = $signed(tile_in_q0);

assign tile_out_10_address0 = p_cast_reg_522_pp0_iter3_reg;

assign tile_out_10_ce0 = tile_out_10_ce0_local;

assign tile_out_10_d0 = conv_reg_557;

assign tile_out_10_we0 = tile_out_10_we0_local;

assign tile_out_11_address0 = p_cast_reg_522_pp0_iter3_reg;

assign tile_out_11_ce0 = tile_out_11_ce0_local;

assign tile_out_11_d0 = conv_reg_557;

assign tile_out_11_we0 = tile_out_11_we0_local;

assign tile_out_12_address0 = p_cast_reg_522_pp0_iter3_reg;

assign tile_out_12_ce0 = tile_out_12_ce0_local;

assign tile_out_12_d0 = conv_reg_557;

assign tile_out_12_we0 = tile_out_12_we0_local;

assign tile_out_13_address0 = p_cast_reg_522_pp0_iter3_reg;

assign tile_out_13_ce0 = tile_out_13_ce0_local;

assign tile_out_13_d0 = conv_reg_557;

assign tile_out_13_we0 = tile_out_13_we0_local;

assign tile_out_14_address0 = p_cast_reg_522_pp0_iter3_reg;

assign tile_out_14_ce0 = tile_out_14_ce0_local;

assign tile_out_14_d0 = conv_reg_557;

assign tile_out_14_we0 = tile_out_14_we0_local;

assign tile_out_15_address0 = p_cast_reg_522_pp0_iter3_reg;

assign tile_out_15_ce0 = tile_out_15_ce0_local;

assign tile_out_15_d0 = conv_reg_557;

assign tile_out_15_we0 = tile_out_15_we0_local;

assign tile_out_1_address0 = p_cast_reg_522_pp0_iter3_reg;

assign tile_out_1_ce0 = tile_out_1_ce0_local;

assign tile_out_1_d0 = conv_reg_557;

assign tile_out_1_we0 = tile_out_1_we0_local;

assign tile_out_2_address0 = p_cast_reg_522_pp0_iter3_reg;

assign tile_out_2_ce0 = tile_out_2_ce0_local;

assign tile_out_2_d0 = conv_reg_557;

assign tile_out_2_we0 = tile_out_2_we0_local;

assign tile_out_3_address0 = p_cast_reg_522_pp0_iter3_reg;

assign tile_out_3_ce0 = tile_out_3_ce0_local;

assign tile_out_3_d0 = conv_reg_557;

assign tile_out_3_we0 = tile_out_3_we0_local;

assign tile_out_4_address0 = p_cast_reg_522_pp0_iter3_reg;

assign tile_out_4_ce0 = tile_out_4_ce0_local;

assign tile_out_4_d0 = conv_reg_557;

assign tile_out_4_we0 = tile_out_4_we0_local;

assign tile_out_5_address0 = p_cast_reg_522_pp0_iter3_reg;

assign tile_out_5_ce0 = tile_out_5_ce0_local;

assign tile_out_5_d0 = conv_reg_557;

assign tile_out_5_we0 = tile_out_5_we0_local;

assign tile_out_6_address0 = p_cast_reg_522_pp0_iter3_reg;

assign tile_out_6_ce0 = tile_out_6_ce0_local;

assign tile_out_6_d0 = conv_reg_557;

assign tile_out_6_we0 = tile_out_6_we0_local;

assign tile_out_7_address0 = p_cast_reg_522_pp0_iter3_reg;

assign tile_out_7_ce0 = tile_out_7_ce0_local;

assign tile_out_7_d0 = conv_reg_557;

assign tile_out_7_we0 = tile_out_7_we0_local;

assign tile_out_8_address0 = p_cast_reg_522_pp0_iter3_reg;

assign tile_out_8_ce0 = tile_out_8_ce0_local;

assign tile_out_8_d0 = conv_reg_557;

assign tile_out_8_we0 = tile_out_8_we0_local;

assign tile_out_9_address0 = p_cast_reg_522_pp0_iter3_reg;

assign tile_out_9_ce0 = tile_out_9_ce0_local;

assign tile_out_9_d0 = conv_reg_557;

assign tile_out_9_we0 = tile_out_9_we0_local;

assign tile_out_address0 = p_cast_reg_522_pp0_iter3_reg;

assign tile_out_ce0 = tile_out_ce0_local;

assign tile_out_d0 = conv_reg_557;

assign tile_out_we0 = tile_out_we0_local;

assign tmp5_fu_470_p2 = ($signed(tile_in_load_cast_fu_458_p1) + $signed(tile_in_2_load_cast_fu_466_p1));

assign tmp_5_fu_418_p3 = {{empty_fu_414_p1}, {5'd0}};

always @ (posedge ap_clk) begin
    p_cast_reg_522[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    p_cast_reg_522_pp0_iter3_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
end

endmodule //cnn_accel_cnn_accel_Pipeline_VITIS_LOOP_49_5_VITIS_LOOP_50_6
