// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_accel_cnn_accel_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY,
        m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID,
        m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP,
        m_axi_gmem_0_BID,
        m_axi_gmem_0_BUSER,
        size_cast9,
        ty,
        size,
        tile_in_address0,
        tile_in_ce0,
        tile_in_we0,
        tile_in_d0,
        tile_in_1_address0,
        tile_in_1_ce0,
        tile_in_1_we0,
        tile_in_1_d0,
        tile_in_2_address0,
        tile_in_2_ce0,
        tile_in_2_we0,
        tile_in_2_d0,
        zext_ln28,
        phi_mul,
        input_r,
        tx
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_0_AWVALID;
input   m_axi_gmem_0_AWREADY;
output  [63:0] m_axi_gmem_0_AWADDR;
output  [0:0] m_axi_gmem_0_AWID;
output  [31:0] m_axi_gmem_0_AWLEN;
output  [2:0] m_axi_gmem_0_AWSIZE;
output  [1:0] m_axi_gmem_0_AWBURST;
output  [1:0] m_axi_gmem_0_AWLOCK;
output  [3:0] m_axi_gmem_0_AWCACHE;
output  [2:0] m_axi_gmem_0_AWPROT;
output  [3:0] m_axi_gmem_0_AWQOS;
output  [3:0] m_axi_gmem_0_AWREGION;
output  [0:0] m_axi_gmem_0_AWUSER;
output   m_axi_gmem_0_WVALID;
input   m_axi_gmem_0_WREADY;
output  [7:0] m_axi_gmem_0_WDATA;
output  [0:0] m_axi_gmem_0_WSTRB;
output   m_axi_gmem_0_WLAST;
output  [0:0] m_axi_gmem_0_WID;
output  [0:0] m_axi_gmem_0_WUSER;
output   m_axi_gmem_0_ARVALID;
input   m_axi_gmem_0_ARREADY;
output  [63:0] m_axi_gmem_0_ARADDR;
output  [0:0] m_axi_gmem_0_ARID;
output  [31:0] m_axi_gmem_0_ARLEN;
output  [2:0] m_axi_gmem_0_ARSIZE;
output  [1:0] m_axi_gmem_0_ARBURST;
output  [1:0] m_axi_gmem_0_ARLOCK;
output  [3:0] m_axi_gmem_0_ARCACHE;
output  [2:0] m_axi_gmem_0_ARPROT;
output  [3:0] m_axi_gmem_0_ARQOS;
output  [3:0] m_axi_gmem_0_ARREGION;
output  [0:0] m_axi_gmem_0_ARUSER;
input   m_axi_gmem_0_RVALID;
output   m_axi_gmem_0_RREADY;
input  [7:0] m_axi_gmem_0_RDATA;
input   m_axi_gmem_0_RLAST;
input  [0:0] m_axi_gmem_0_RID;
input  [10:0] m_axi_gmem_0_RFIFONUM;
input  [0:0] m_axi_gmem_0_RUSER;
input  [1:0] m_axi_gmem_0_RRESP;
input   m_axi_gmem_0_BVALID;
output   m_axi_gmem_0_BREADY;
input  [1:0] m_axi_gmem_0_BRESP;
input  [0:0] m_axi_gmem_0_BID;
input  [0:0] m_axi_gmem_0_BUSER;
input  [30:0] size_cast9;
input  [30:0] ty;
input  [30:0] size;
output  [9:0] tile_in_address0;
output   tile_in_ce0;
output   tile_in_we0;
output  [7:0] tile_in_d0;
output  [9:0] tile_in_1_address0;
output   tile_in_1_ce0;
output   tile_in_1_we0;
output  [7:0] tile_in_1_d0;
output  [9:0] tile_in_2_address0;
output   tile_in_2_ce0;
output   tile_in_2_we0;
output  [7:0] tile_in_2_d0;
input  [25:0] zext_ln28;
input  [56:0] phi_mul;
input  [63:0] input_r;
input  [30:0] tx;

reg ap_idle;
reg m_axi_gmem_0_ARVALID;
reg m_axi_gmem_0_RREADY;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
reg   [0:0] and_ln38_reg_542;
reg   [0:0] and_ln38_reg_542_pp0_iter1_reg;
reg    ap_block_state6_io_grp1;
reg    ap_block_pp0_stage2_subdone_grp1_done_reg;
reg    ap_block_pp0_stage2_subdone_grp1;
reg    ap_block_pp0_stage2_subdone;
reg   [0:0] and_ln38_reg_542_pp0_iter4_reg;
reg    ap_block_state15_pp0_stage2_iter4_grp3;
reg    ap_block_pp0_stage2_subdone_grp3_done_reg;
reg    ap_block_pp0_stage2_subdone_grp3;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln31_reg_514;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_AR;
wire    ap_block_pp0_stage2_grp1;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp2;
reg   [0:0] and_ln38_reg_542_pp0_iter3_reg;
wire    ap_block_pp0_stage2_grp3;
wire    ap_block_pp0_stage0_grp4;
reg   [7:0] reg_209;
reg    ap_block_state14_pp0_stage1_iter4_grp2;
reg    ap_block_pp0_stage1_11001_grp2;
reg    ap_block_pp0_stage2_11001_grp3;
reg    ap_block_state16_pp0_stage0_iter5_grp4;
reg    ap_block_pp0_stage0_11001_grp4;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_subdone;
wire   [31:0] tx_cast_fu_216_p1;
reg   [31:0] tx_cast_reg_488;
wire   [56:0] zext_ln28_cast_fu_220_p1;
reg   [56:0] zext_ln28_cast_reg_493;
wire   [31:0] size_cast_fu_224_p1;
reg   [31:0] size_cast_reg_498;
wire   [31:0] ty_cast_fu_228_p1;
reg   [31:0] ty_cast_reg_504;
wire   [35:0] size_cast9_cast_fu_232_p1;
reg   [35:0] size_cast9_cast_reg_509;
wire   [0:0] icmp_ln31_fu_254_p2;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln31_reg_514_pp0_iter1_reg;
reg   [0:0] icmp_ln31_reg_514_pp0_iter2_reg;
reg   [0:0] icmp_ln31_reg_514_pp0_iter3_reg;
reg   [0:0] icmp_ln31_reg_514_pp0_iter4_reg;
wire   [5:0] select_ln31_fu_284_p3;
reg   [5:0] select_ln31_reg_518;
wire   [5:0] select_ln31_1_fu_292_p3;
reg   [5:0] select_ln31_1_reg_526;
wire   [4:0] trunc_ln41_fu_300_p1;
reg   [4:0] trunc_ln41_reg_532;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
reg    ap_block_pp0_stage1_subdone;
wire   [0:0] and_ln38_fu_344_p2;
reg   [0:0] and_ln38_reg_542_pp0_iter2_reg;
wire   [35:0] grp_fu_205_p2;
reg   [35:0] empty_reg_546;
wire    ap_block_pp0_stage2_11001_grp0;
reg    ap_block_pp0_stage2_subdone_grp0_done_reg;
wire    ap_block_pp0_stage2_subdone_grp0;
wire   [9:0] add_ln41_fu_370_p2;
reg   [9:0] add_ln41_reg_551;
reg   [9:0] add_ln41_reg_551_pp0_iter2_reg;
reg   [9:0] add_ln41_reg_551_pp0_iter3_reg;
reg   [9:0] add_ln41_reg_551_pp0_iter4_reg;
wire   [37:0] tmp1_fu_396_p2;
reg   [37:0] tmp1_reg_556;
wire   [63:0] tmp3_fu_426_p2;
reg   [63:0] tmp3_reg_561;
reg   [63:0] gmem_addr_reg_566;
reg   [9:0] tile_in_1_addr_reg_572;
reg   [9:0] tile_in_2_addr_reg_577;
wire   [63:0] zext_ln41_1_fu_451_p1;
wire    ap_block_pp0_stage2_grp0;
wire   [63:0] add_ln36_1_fu_440_p2;
reg    ap_block_pp0_stage2_11001_grp1;
reg   [5:0] x_fu_102;
wire   [5:0] add_ln32_fu_350_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_x_load;
wire    ap_block_pp0_stage0;
reg   [5:0] y_fu_106;
reg   [5:0] ap_sig_allocacmp_y_load;
reg   [10:0] indvar_flatten_fu_110;
wire   [10:0] add_ln31_1_fu_260_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten_load;
reg    tile_in_we0_local;
reg    tile_in_ce0_local;
reg    tile_in_1_we0_local;
wire    ap_block_pp0_stage0_grp0;
reg    tile_in_1_ce0_local;
reg    tile_in_2_we0_local;
wire    ap_block_pp0_stage1_grp0;
reg    tile_in_2_ce0_local;
wire   [5:0] grp_fu_205_p0;
wire   [30:0] grp_fu_205_p1;
wire   [0:0] icmp_ln32_fu_278_p2;
wire   [5:0] add_ln31_fu_272_p2;
wire   [31:0] zext_ln31_fu_314_p1;
wire   [31:0] empty_26_fu_321_p2;
wire   [31:0] zext_ln32_fu_331_p1;
wire   [31:0] add_ln36_2_fu_334_p2;
wire   [0:0] cmp14_fu_326_p2;
wire   [0:0] icmp_ln38_fu_339_p2;
wire   [9:0] tmp_3_fu_360_p3;
wire   [9:0] zext_ln41_fu_367_p1;
wire   [35:0] zext_ln32_1_fu_376_p1;
wire   [35:0] tmp_fu_379_p2;
wire   [37:0] p_shl1_fu_388_p3;
wire   [37:0] tmp_cast_fu_384_p1;
wire   [56:0] tmp2_fu_402_p2;
wire   [61:0] tmp_1_fu_414_p3;
wire   [63:0] p_shl_fu_406_p3;
wire   [63:0] p_shl30_fu_422_p1;
wire   [63:0] tmp1_cast_fu_432_p1;
wire   [63:0] add_ln36_fu_435_p2;
reg    grp_fu_205_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage2_11001;
reg    ap_condition_exit_pp0_iter4_stage1;
reg    ap_idle_pp0_0to3;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_1to5;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [35:0] grp_fu_205_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp3_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp0_done_reg = 1'b0;
#0 x_fu_102 = 6'd0;
#0 y_fu_106 = 6'd0;
#0 indvar_flatten_fu_110 = 11'd0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_mul_6ns_31ns_36_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 36 ))
mul_6ns_31ns_36_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_205_p0),
    .din1(grp_fu_205_p1),
    .ce(grp_fu_205_ce),
    .dout(grp_fu_205_p2)
);

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp0)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp1)) begin
                ap_block_pp0_stage2_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp3_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp3_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp3)) begin
                ap_block_pp0_stage2_subdone_grp3_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln31_fu_254_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_110 <= add_ln31_1_fu_260_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_110 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_fu_102 <= 6'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln31_reg_514 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        x_fu_102 <= add_ln32_fu_350_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln31_fu_254_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_fu_106 <= select_ln31_1_fu_292_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_106 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        add_ln41_reg_551 <= add_ln41_fu_370_p2;
        add_ln41_reg_551_pp0_iter2_reg <= add_ln41_reg_551;
        add_ln41_reg_551_pp0_iter3_reg <= add_ln41_reg_551_pp0_iter2_reg;
        add_ln41_reg_551_pp0_iter4_reg <= add_ln41_reg_551_pp0_iter3_reg;
        size_cast9_cast_reg_509[30 : 0] <= size_cast9_cast_fu_232_p1[30 : 0];
        size_cast_reg_498[30 : 0] <= size_cast_fu_224_p1[30 : 0];
        tmp1_reg_556 <= tmp1_fu_396_p2;
        tmp3_reg_561[63 : 5] <= tmp3_fu_426_p2[63 : 5];
        tx_cast_reg_488[30 : 0] <= tx_cast_fu_216_p1[30 : 0];
        ty_cast_reg_504[30 : 0] <= ty_cast_fu_228_p1[30 : 0];
        zext_ln28_cast_reg_493[25 : 0] <= zext_ln28_cast_fu_220_p1[25 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp2))) begin
        and_ln38_reg_542 <= and_ln38_fu_344_p2;
        and_ln38_reg_542_pp0_iter1_reg <= and_ln38_reg_542;
        and_ln38_reg_542_pp0_iter2_reg <= and_ln38_reg_542_pp0_iter1_reg;
        and_ln38_reg_542_pp0_iter3_reg <= and_ln38_reg_542_pp0_iter2_reg;
        and_ln38_reg_542_pp0_iter4_reg <= and_ln38_reg_542_pp0_iter3_reg;
        gmem_addr_reg_566 <= add_ln36_1_fu_440_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        empty_reg_546 <= grp_fu_205_p2;
        tile_in_1_addr_reg_572 <= zext_ln41_1_fu_451_p1;
        tile_in_2_addr_reg_577 <= zext_ln41_1_fu_451_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln31_reg_514 <= icmp_ln31_fu_254_p2;
        icmp_ln31_reg_514_pp0_iter1_reg <= icmp_ln31_reg_514;
        icmp_ln31_reg_514_pp0_iter2_reg <= icmp_ln31_reg_514_pp0_iter1_reg;
        icmp_ln31_reg_514_pp0_iter3_reg <= icmp_ln31_reg_514_pp0_iter2_reg;
        icmp_ln31_reg_514_pp0_iter4_reg <= icmp_ln31_reg_514_pp0_iter3_reg;
        select_ln31_1_reg_526 <= select_ln31_1_fu_292_p3;
        select_ln31_reg_518 <= select_ln31_fu_284_p3;
        trunc_ln41_reg_532 <= trunc_ln41_fu_300_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp4)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp3) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp2)))) begin
        reg_209 <= m_axi_gmem_0_RDATA;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln31_reg_514 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln31_reg_514_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_condition_exit_pp0_iter4_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter4_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to5 = 1'b1;
    end else begin
        ap_idle_pp0_1to5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_110;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_x_load = 6'd0;
    end else begin
        ap_sig_allocacmp_x_load = x_fu_102;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_y_load = 6'd0;
    end else begin
        ap_sig_allocacmp_y_load = y_fu_106;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_grp1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg) & (1'd1 == and_ln38_reg_542_pp0_iter1_reg))) begin
        gmem_blk_n_AR = m_axi_gmem_0_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp4) & (1'd1 == and_ln38_reg_542_pp0_iter4_reg)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_grp3) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg) & (1'd1 == and_ln38_reg_542_pp0_iter4_reg)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp2) & (1'd1 == and_ln38_reg_542_pp0_iter3_reg)))) begin
        gmem_blk_n_R = m_axi_gmem_0_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)))) begin
        grp_fu_205_ce = 1'b1;
    end else begin
        grp_fu_205_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg) & (1'd1 == and_ln38_reg_542_pp0_iter1_reg))) begin
        m_axi_gmem_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp4) & (1'd1 == and_ln38_reg_542_pp0_iter4_reg)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp3) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg) & (1'd1 == and_ln38_reg_542_pp0_iter4_reg)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp2) & (1'd1 == and_ln38_reg_542_pp0_iter3_reg)))) begin
        m_axi_gmem_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        tile_in_1_ce0_local = 1'b1;
    end else begin
        tile_in_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'd1 == and_ln38_reg_542_pp0_iter4_reg))) begin
        tile_in_1_we0_local = 1'b1;
    end else begin
        tile_in_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        tile_in_2_ce0_local = 1'b1;
    end else begin
        tile_in_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (1'd1 == and_ln38_reg_542_pp0_iter4_reg))) begin
        tile_in_2_we0_local = 1'b1;
    end else begin
        tile_in_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        tile_in_ce0_local = 1'b1;
    end else begin
        tile_in_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (1'd1 == and_ln38_reg_542_pp0_iter4_reg))) begin
        tile_in_we0_local = 1'b1;
    end else begin
        tile_in_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to5 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln31_1_fu_260_p2 = (ap_sig_allocacmp_indvar_flatten_load + 11'd1);

assign add_ln31_fu_272_p2 = (ap_sig_allocacmp_y_load + 6'd1);

assign add_ln32_fu_350_p2 = (select_ln31_reg_518 + 6'd1);

assign add_ln36_1_fu_440_p2 = (add_ln36_fu_435_p2 + tmp3_reg_561);

assign add_ln36_2_fu_334_p2 = (zext_ln32_fu_331_p1 + tx_cast_reg_488);

assign add_ln36_fu_435_p2 = (tmp1_cast_fu_432_p1 + input_r);

assign add_ln41_fu_370_p2 = (tmp_3_fu_360_p3 + zext_ln41_fu_367_p1);

assign and_ln38_fu_344_p2 = (icmp_ln38_fu_339_p2 & cmp14_fu_326_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state16_pp0_stage0_iter5_grp4));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp4 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state16_pp0_stage0_iter5_grp4));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state16_pp0_stage0_iter5_grp4));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp2 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state14_pp0_stage1_iter4_grp2));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state14_pp0_stage1_iter4_grp2));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state15_pp0_stage2_iter4_grp3) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_io_grp1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage2_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_io_grp1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage2_11001_grp3 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state15_pp0_stage2_iter4_grp3) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg));
end

assign ap_block_pp0_stage2_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state15_pp0_stage2_iter4_grp3) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_io_grp1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage2_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_io_grp1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone_grp3 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state15_pp0_stage2_iter4_grp3) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_state14_pp0_stage1_iter4_grp2 = ((m_axi_gmem_0_RVALID == 1'b0) & (1'd1 == and_ln38_reg_542_pp0_iter3_reg));
end

always @ (*) begin
    ap_block_state15_pp0_stage2_iter4_grp3 = ((m_axi_gmem_0_RVALID == 1'b0) & (1'd1 == and_ln38_reg_542_pp0_iter4_reg));
end

always @ (*) begin
    ap_block_state16_pp0_stage0_iter5_grp4 = ((m_axi_gmem_0_RVALID == 1'b0) & (1'd1 == and_ln38_reg_542_pp0_iter4_reg));
end

always @ (*) begin
    ap_block_state6_io_grp1 = ((m_axi_gmem_0_ARREADY == 1'b0) & (1'd1 == and_ln38_reg_542_pp0_iter1_reg));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_ready = ap_ready_sig;

assign cmp14_fu_326_p2 = (($signed(empty_26_fu_321_p2) < $signed(size_cast_reg_498)) ? 1'b1 : 1'b0);

assign empty_26_fu_321_p2 = (zext_ln31_fu_314_p1 + ty_cast_reg_504);

assign grp_fu_205_p0 = grp_fu_205_p00;

assign grp_fu_205_p00 = select_ln31_1_reg_526;

assign grp_fu_205_p1 = size_cast9_cast_reg_509;

assign icmp_ln31_fu_254_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_278_p2 = ((ap_sig_allocacmp_x_load == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_339_p2 = (($signed(add_ln36_2_fu_334_p2) < $signed(size_cast_reg_498)) ? 1'b1 : 1'b0);

assign m_axi_gmem_0_ARADDR = gmem_addr_reg_566;

assign m_axi_gmem_0_ARBURST = 2'd0;

assign m_axi_gmem_0_ARCACHE = 4'd0;

assign m_axi_gmem_0_ARID = 1'd0;

assign m_axi_gmem_0_ARLEN = 64'd3;

assign m_axi_gmem_0_ARLOCK = 2'd0;

assign m_axi_gmem_0_ARPROT = 3'd0;

assign m_axi_gmem_0_ARQOS = 4'd0;

assign m_axi_gmem_0_ARREGION = 4'd0;

assign m_axi_gmem_0_ARSIZE = 3'd0;

assign m_axi_gmem_0_ARUSER = 1'd0;

assign m_axi_gmem_0_AWADDR = 64'd0;

assign m_axi_gmem_0_AWBURST = 2'd0;

assign m_axi_gmem_0_AWCACHE = 4'd0;

assign m_axi_gmem_0_AWID = 1'd0;

assign m_axi_gmem_0_AWLEN = 32'd0;

assign m_axi_gmem_0_AWLOCK = 2'd0;

assign m_axi_gmem_0_AWPROT = 3'd0;

assign m_axi_gmem_0_AWQOS = 4'd0;

assign m_axi_gmem_0_AWREGION = 4'd0;

assign m_axi_gmem_0_AWSIZE = 3'd0;

assign m_axi_gmem_0_AWUSER = 1'd0;

assign m_axi_gmem_0_AWVALID = 1'b0;

assign m_axi_gmem_0_BREADY = 1'b0;

assign m_axi_gmem_0_WDATA = 8'd0;

assign m_axi_gmem_0_WID = 1'd0;

assign m_axi_gmem_0_WLAST = 1'b0;

assign m_axi_gmem_0_WSTRB = 1'd0;

assign m_axi_gmem_0_WUSER = 1'd0;

assign m_axi_gmem_0_WVALID = 1'b0;

assign p_shl1_fu_388_p3 = {{tmp_fu_379_p2}, {2'd0}};

assign p_shl30_fu_422_p1 = tmp_1_fu_414_p3;

assign p_shl_fu_406_p3 = {{tmp2_fu_402_p2}, {7'd0}};

assign select_ln31_1_fu_292_p3 = ((icmp_ln32_fu_278_p2[0:0] == 1'b1) ? add_ln31_fu_272_p2 : ap_sig_allocacmp_y_load);

assign select_ln31_fu_284_p3 = ((icmp_ln32_fu_278_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_x_load);

assign size_cast9_cast_fu_232_p1 = size_cast9;

assign size_cast_fu_224_p1 = size;

assign tile_in_1_address0 = tile_in_1_addr_reg_572;

assign tile_in_1_ce0 = tile_in_1_ce0_local;

assign tile_in_1_d0 = reg_209;

assign tile_in_1_we0 = tile_in_1_we0_local;

assign tile_in_2_address0 = tile_in_2_addr_reg_577;

assign tile_in_2_ce0 = tile_in_2_ce0_local;

assign tile_in_2_d0 = reg_209;

assign tile_in_2_we0 = tile_in_2_we0_local;

assign tile_in_address0 = zext_ln41_1_fu_451_p1;

assign tile_in_ce0 = tile_in_ce0_local;

assign tile_in_d0 = reg_209;

assign tile_in_we0 = tile_in_we0_local;

assign tmp1_cast_fu_432_p1 = tmp1_reg_556;

assign tmp1_fu_396_p2 = (p_shl1_fu_388_p3 - tmp_cast_fu_384_p1);

assign tmp2_fu_402_p2 = (zext_ln28_cast_reg_493 + phi_mul);

assign tmp3_fu_426_p2 = (p_shl_fu_406_p3 - p_shl30_fu_422_p1);

assign tmp_1_fu_414_p3 = {{tmp2_fu_402_p2}, {5'd0}};

assign tmp_3_fu_360_p3 = {{trunc_ln41_reg_532}, {5'd0}};

assign tmp_cast_fu_384_p1 = tmp_fu_379_p2;

assign tmp_fu_379_p2 = (zext_ln32_1_fu_376_p1 + empty_reg_546);

assign trunc_ln41_fu_300_p1 = select_ln31_1_fu_292_p3[4:0];

assign tx_cast_fu_216_p1 = tx;

assign ty_cast_fu_228_p1 = ty;

assign zext_ln28_cast_fu_220_p1 = zext_ln28;

assign zext_ln31_fu_314_p1 = select_ln31_1_reg_526;

assign zext_ln32_1_fu_376_p1 = select_ln31_reg_518;

assign zext_ln32_fu_331_p1 = select_ln31_reg_518;

assign zext_ln41_1_fu_451_p1 = add_ln41_reg_551_pp0_iter4_reg;

assign zext_ln41_fu_367_p1 = select_ln31_reg_518;

always @ (posedge ap_clk) begin
    tx_cast_reg_488[31] <= 1'b0;
    zext_ln28_cast_reg_493[56:26] <= 31'b0000000000000000000000000000000;
    size_cast_reg_498[31] <= 1'b0;
    ty_cast_reg_504[31] <= 1'b0;
    size_cast9_cast_reg_509[35:31] <= 5'b00000;
    tmp3_reg_561[4:0] <= 5'b00000;
end

endmodule //cnn_accel_cnn_accel_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4
