# Created by Sathya Narayanan N
# Email id: sathya281@gmail.com

# Copyright (C) 2019 IIT Madras. All rights reserved.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>

SHELL := /bin/bash # Use bash syntax
DC ?=
PROGRAM ?= 
#default target board
FLAGS ?=

all: create_dir
	make $(PROGRAM).riscv 

$(PROGRAM).riscv: create_dir
	@echo "Present Directory: $(PWD); $(PROGRAM)"
	@riscv$(XLEN)-unknown-elf-gcc -march=$(MARCH) -mabi=$(MABI) -w $(DC) -mcmodel=medany -static -g -std=gnu99 -fno-builtin-printf $(FLAGS) -I$(bsplib) -I$(bspinc) -I$(bspboard) -I$(bspdri)/include -c ./$(PROGRAM).c -o ./output/$(PROGRAM).o 
	@riscv$(XLEN)-unknown-elf-gcc -march=$(MARCH) -mabi=$(MABI) -T  $(bspboard)/link.ld ./output/$(PROGRAM).o $(GENLIB)/gen_lib/libshakti$(XLEN).a   -o ./output/$(PROGRAM).shakti -static -nostartfiles -lm -lgcc
	@riscv$(XLEN)-unknown-elf-objdump -D ./output/$(PROGRAM).shakti > ./output/$(PROGRAM).dump

create_dir:
	@echo "Creating output directory"
	@echo "Present Directory: $(PWD)"
	@mkdir -p ./output

