// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mobilenet_top_mobilenet_top_Pipeline_VITIS_LOOP_55_1_VITIS_LOOP_56_2_VITIS_LOOP_57_31 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buf_B_address0,
        buf_B_ce0,
        buf_B_q0,
        buf_B_address1,
        buf_B_ce1,
        buf_B_q1,
        buf_exp_address1,
        buf_exp_ce1,
        buf_exp_we1,
        buf_exp_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] buf_B_address0;
output   buf_B_ce0;
input  [15:0] buf_B_q0;
output  [11:0] buf_B_address1;
output   buf_B_ce1;
input  [15:0] buf_B_q1;
output  [12:0] buf_exp_address1;
output   buf_exp_ce1;
output   buf_exp_we1;
output  [15:0] buf_exp_d1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln55_reg_1002;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] features_2_conv_0_1_bias_address0;
wire   [7:0] features_2_conv_0_1_bias_q0;
wire   [6:0] features_2_conv_0_1_weight_q0;
wire   [6:0] features_2_conv_0_1_weight_q1;
reg   [15:0] reg_278;
wire    ap_block_pp0_stage1_11001;
wire    ap_block_pp0_stage0_11001;
reg   [15:0] reg_282;
wire   [46:0] grp_fu_270_p2;
reg   [46:0] reg_286;
wire   [46:0] grp_fu_274_p2;
reg   [46:0] reg_290;
wire   [0:0] icmp_ln55_fu_322_p2;
reg   [0:0] icmp_ln55_reg_1002_pp0_iter1_reg;
reg   [0:0] icmp_ln55_reg_1002_pp0_iter2_reg;
wire   [3:0] select_ln55_2_fu_389_p3;
reg   [3:0] select_ln55_2_reg_1006;
wire   [5:0] oc_2_mid2_fu_409_p3;
reg   [5:0] oc_2_mid2_reg_1013;
wire   [3:0] select_ln56_fu_417_p3;
reg   [3:0] select_ln56_reg_1020;
wire   [4:0] trunc_ln60_fu_425_p1;
reg   [4:0] trunc_ln60_reg_1028;
reg   [7:0] tmp_65_reg_1054;
reg   [6:0] features_2_conv_0_1_weight_load_reg_1060;
reg   [6:0] features_2_conv_0_1_weight_load_1_reg_1065;
wire   [12:0] add_ln62_fu_636_p2;
reg   [12:0] add_ln62_reg_1080;
reg   [12:0] add_ln62_reg_1080_pp0_iter2_reg;
reg   [12:0] add_ln62_reg_1080_pp0_iter3_reg;
reg   [6:0] features_2_conv_0_1_weight_load_2_reg_1100;
reg   [6:0] features_2_conv_0_1_weight_load_3_reg_1105;
reg   [7:0] features_2_conv_0_1_bias_load_reg_1110;
reg   [31:0] tmp_55_reg_1115;
wire   [55:0] add_ln60_11_fu_886_p2;
reg   [55:0] add_ln60_11_reg_1120;
reg   [39:0] trunc_ln60_4_reg_1126;
wire   [15:0] ref_tmp23_1_i_fu_943_p9;
reg   [15:0] ref_tmp23_1_i_reg_1131;
wire    ap_block_pp0_stage0_subdone;
wire   [31:0] zext_ln60_17_fu_437_p1;
wire    ap_block_pp0_stage1;
wire   [31:0] zext_ln60_19_fu_450_p1;
wire   [31:0] p_cast159_fu_571_p1;
wire    ap_block_pp0_stage0;
wire   [31:0] p_cast160_fu_594_p1;
wire   [31:0] zext_ln60_21_fu_619_p1;
wire   [31:0] zext_ln60_23_fu_631_p1;
wire   [31:0] p_cast161_fu_663_p1;
wire   [31:0] p_cast162_fu_675_p1;
wire   [31:0] zext_ln58_fu_680_p1;
wire   [31:0] zext_ln62_fu_963_p1;
reg   [5:0] oc_fu_138;
wire   [5:0] add_ln57_fu_642_p2;
wire    ap_loop_init;
reg   [3:0] w_idx_fu_142;
reg   [9:0] indvar_flatten39_fu_146;
wire   [9:0] select_ln56_2_fu_461_p3;
reg   [3:0] h_fu_150;
reg   [12:0] indvar_flatten52_fu_154;
wire   [12:0] add_ln55_fu_328_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten52_load;
reg    features_2_conv_0_1_weight_ce1_local;
reg   [6:0] features_2_conv_0_1_weight_address1_local;
reg    features_2_conv_0_1_weight_ce0_local;
reg   [6:0] features_2_conv_0_1_weight_address0_local;
reg    buf_B_ce1_local;
reg   [11:0] buf_B_address1_local;
reg    buf_B_ce0_local;
reg   [11:0] buf_B_address0_local;
reg    features_2_conv_0_1_bias_ce0_local;
reg    buf_exp_we1_local;
reg    buf_exp_ce1_local;
reg   [22:0] grp_fu_270_p0;
wire   [46:0] zext_ln60_18_fu_717_p1;
wire   [46:0] zext_ln60_22_fu_816_p1;
reg  signed [23:0] grp_fu_270_p1;
wire  signed [46:0] shl_i_i_i140_i82_cast_fu_692_p1;
wire  signed [46:0] shl_i_i_i140_i82_2_cast_fu_742_p1;
reg   [22:0] grp_fu_274_p0;
wire   [46:0] zext_ln60_20_fu_729_p1;
wire   [46:0] zext_ln60_24_fu_838_p1;
reg  signed [23:0] grp_fu_274_p1;
wire  signed [46:0] shl_i_i_i140_i82_1_cast_fu_705_p1;
wire  signed [46:0] sext_ln62_fu_755_p1;
wire   [0:0] icmp_ln56_fu_357_p2;
wire   [0:0] icmp_ln57_fu_377_p2;
wire   [0:0] xor_ln55_fu_371_p2;
wire   [3:0] add_ln55_1_fu_351_p2;
wire   [3:0] select_ln55_fu_363_p3;
wire   [0:0] and_ln55_fu_383_p2;
wire   [0:0] empty_fu_403_p2;
wire   [3:0] add_ln56_1_fu_397_p2;
wire   [6:0] shl_ln60_9_fu_429_p3;
wire   [6:0] or_ln60_7_fu_442_p3;
wire   [9:0] add_ln56_2_fu_455_p2;
wire   [7:0] tmp_fu_486_p3;
wire   [9:0] p_shl4_fu_479_p3;
wire   [9:0] p_shl17_fu_493_p1;
wire   [12:0] p_shl5_fu_503_p3;
wire   [12:0] zext_ln56_fu_510_p1;
wire   [5:0] tmp_s_fu_520_p3;
wire   [9:0] p_cast67_fu_527_p1;
wire   [9:0] empty_114_fu_497_p2;
wire   [7:0] tmp_54_fu_544_p3;
wire   [9:0] p_shl_fu_537_p3;
wire   [9:0] p_shl13_fu_551_p1;
wire   [9:0] empty_116_fu_555_p2;
wire   [12:0] p_cast69_fu_561_p1;
wire   [12:0] add_ln56_fu_514_p2;
wire   [9:0] empty_115_fu_531_p2;
wire   [8:0] tmp_63_fu_576_p4;
wire   [9:0] tmp_64_fu_586_p3;
wire   [6:0] or_ln60_8_fu_612_p3;
wire   [6:0] or_ln60_9_fu_624_p3;
wire   [12:0] empty_117_fu_565_p2;
wire   [12:0] zext_ln58_1_fu_609_p1;
wire   [9:0] tmp_66_fu_656_p3;
wire   [9:0] tmp_67_fu_668_p3;
wire   [23:0] shl_i_i_i140_i1_fu_684_p3;
wire   [23:0] shl_i_i_i140_i82_1_fu_697_p3;
wire   [22:0] shl_ln60_10_fu_710_p3;
wire   [22:0] shl_ln60_11_fu_722_p3;
wire   [23:0] shl_i_i_i140_i82_2_fu_734_p3;
wire   [23:0] shl_i_i_i140_i82_3_fu_747_p3;
wire   [39:0] shl_ln60_s_fu_760_p3;
wire  signed [46:0] sext_ln60_8_fu_767_p1;
wire   [46:0] add_ln60_8_fu_771_p2;
wire   [30:0] trunc_ln6_fu_777_p4;
wire   [46:0] tmp_68_fu_787_p3;
wire  signed [47:0] sext_ln60_fu_795_p1;
wire  signed [47:0] sext_ln60_48_fu_799_p1;
wire   [22:0] shl_ln60_12_fu_809_p3;
wire   [47:0] add_ln60_9_fu_803_p2;
wire   [22:0] shl_ln60_13_fu_831_p3;
wire   [47:0] tmp_56_fu_843_p3;
wire  signed [55:0] sext_ln60_49_fu_850_p1;
wire  signed [55:0] sext_ln60_11_fu_854_p1;
wire   [55:0] add_ln60_10_fu_858_p2;
wire   [39:0] tmp_69_fu_864_p4;
wire   [55:0] shl_ln60_14_fu_874_p3;
wire  signed [55:0] sext_ln60_12_fu_882_p1;
wire   [0:0] icmp_ln62_fu_902_p2;
wire   [0:0] tmp_57_fu_907_p3;
wire   [0:0] xor_ln62_fu_923_p2;
wire   [0:0] and_ln62_fu_929_p2;
wire   [15:0] ref_tmp23_1_i_fu_943_p6;
wire   [15:0] ref_tmp23_1_i_fu_943_p7;
wire   [1:0] ref_tmp23_1_i_fu_943_p8;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter3_stage0;
reg    ap_idle_pp0_0to2;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to4;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire  signed [1:0] ref_tmp23_1_i_fu_943_p1;
wire   [1:0] ref_tmp23_1_i_fu_943_p3;
wire   [1:0] ref_tmp23_1_i_fu_943_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 oc_fu_138 = 6'd0;
#0 w_idx_fu_142 = 4'd0;
#0 indvar_flatten39_fu_146 = 10'd0;
#0 h_fu_150 = 4'd0;
#0 indvar_flatten52_fu_154 = 13'd0;
#0 ap_done_reg = 1'b0;
end

mobilenet_top_mobilenet_top_Pipeline_VITIS_LOOP_55_1_VITIS_LOOP_56_2_VITIS_LOOP_57_31_featufYi #(
    .DataWidth( 8 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
features_2_conv_0_1_bias_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(features_2_conv_0_1_bias_address0),
    .ce0(features_2_conv_0_1_bias_ce0_local),
    .q0(features_2_conv_0_1_bias_q0)
);

mobilenet_top_mobilenet_top_Pipeline_VITIS_LOOP_55_1_VITIS_LOOP_56_2_VITIS_LOOP_57_31_featug8j #(
    .DataWidth( 7 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
features_2_conv_0_1_weight_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(features_2_conv_0_1_weight_address0_local),
    .ce0(features_2_conv_0_1_weight_ce0_local),
    .q0(features_2_conv_0_1_weight_q0),
    .address1(features_2_conv_0_1_weight_address1_local),
    .ce1(features_2_conv_0_1_weight_ce1_local),
    .q1(features_2_conv_0_1_weight_q1)
);

mobilenet_top_mul_23ns_24s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 47 ))
mul_23ns_24s_47_1_1_U44(
    .din0(grp_fu_270_p0),
    .din1(grp_fu_270_p1),
    .dout(grp_fu_270_p2)
);

mobilenet_top_mul_23ns_24s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 47 ))
mul_23ns_24s_47_1_1_U45(
    .din0(grp_fu_274_p0),
    .din1(grp_fu_274_p1),
    .dout(grp_fu_274_p2)
);

(* dissolve_hierarchy = "yes" *) mobilenet_top_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U46(
    .din0(16'd1536),
    .din1(16'd0),
    .din2(ref_tmp23_1_i_fu_943_p6),
    .def(ref_tmp23_1_i_fu_943_p7),
    .sel(ref_tmp23_1_i_fu_943_p8),
    .dout(ref_tmp23_1_i_fu_943_p9)
);

mobilenet_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        h_fu_150 <= 4'd0;
    end else if (((icmp_ln55_reg_1002 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        h_fu_150 <= select_ln55_2_fu_389_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten39_fu_146 <= 10'd0;
    end else if (((icmp_ln55_reg_1002 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        indvar_flatten39_fu_146 <= select_ln56_2_fu_461_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln55_fu_322_p2 == 1'd0))) begin
            indvar_flatten52_fu_154 <= add_ln55_fu_328_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten52_fu_154 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            oc_fu_138 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            oc_fu_138 <= add_ln57_fu_642_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_idx_fu_142 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            w_idx_fu_142 <= select_ln56_reg_1020;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln60_11_reg_1120 <= add_ln60_11_fu_886_p2;
        add_ln62_reg_1080 <= add_ln62_fu_636_p2;
        add_ln62_reg_1080_pp0_iter2_reg <= add_ln62_reg_1080;
        add_ln62_reg_1080_pp0_iter3_reg <= add_ln62_reg_1080_pp0_iter2_reg;
        features_2_conv_0_1_bias_load_reg_1110 <= features_2_conv_0_1_bias_q0;
        icmp_ln55_reg_1002 <= icmp_ln55_fu_322_p2;
        icmp_ln55_reg_1002_pp0_iter1_reg <= icmp_ln55_reg_1002;
        icmp_ln55_reg_1002_pp0_iter2_reg <= icmp_ln55_reg_1002_pp0_iter1_reg;
        tmp_65_reg_1054 <= {{empty_115_fu_531_p2[9:2]}};
        trunc_ln60_4_reg_1126 <= {{add_ln60_11_fu_886_p2[55:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        features_2_conv_0_1_weight_load_1_reg_1065 <= features_2_conv_0_1_weight_q0;
        features_2_conv_0_1_weight_load_reg_1060 <= features_2_conv_0_1_weight_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        features_2_conv_0_1_weight_load_2_reg_1100 <= features_2_conv_0_1_weight_q1;
        features_2_conv_0_1_weight_load_3_reg_1105 <= features_2_conv_0_1_weight_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        oc_2_mid2_reg_1013 <= oc_2_mid2_fu_409_p3;
        ref_tmp23_1_i_reg_1131 <= ref_tmp23_1_i_fu_943_p9;
        select_ln55_2_reg_1006 <= select_ln55_2_fu_389_p3;
        select_ln56_reg_1020 <= select_ln56_fu_417_p3;
        tmp_55_reg_1115 <= {{add_ln60_9_fu_803_p2[47:16]}};
        trunc_ln60_reg_1028 <= trunc_ln60_fu_425_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_278 <= buf_B_q1;
        reg_282 <= buf_B_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_286 <= grp_fu_270_p2;
        reg_290 <= grp_fu_274_p2;
    end
end

always @ (*) begin
    if (((icmp_ln55_reg_1002 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln55_reg_1002_pp0_iter2_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to4 = 1'b1;
    end else begin
        ap_idle_pp0_1to4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten52_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten52_load = indvar_flatten52_fu_154;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            buf_B_address0_local = p_cast162_fu_675_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            buf_B_address0_local = p_cast160_fu_594_p1;
        end else begin
            buf_B_address0_local = 'bx;
        end
    end else begin
        buf_B_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            buf_B_address1_local = p_cast161_fu_663_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            buf_B_address1_local = p_cast159_fu_571_p1;
        end else begin
            buf_B_address1_local = 'bx;
        end
    end else begin
        buf_B_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_B_ce0_local = 1'b1;
    end else begin
        buf_B_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_B_ce1_local = 1'b1;
    end else begin
        buf_B_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_exp_ce1_local = 1'b1;
    end else begin
        buf_exp_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_exp_we1_local = 1'b1;
    end else begin
        buf_exp_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        features_2_conv_0_1_bias_ce0_local = 1'b1;
    end else begin
        features_2_conv_0_1_bias_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        features_2_conv_0_1_weight_address0_local = zext_ln60_23_fu_631_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        features_2_conv_0_1_weight_address0_local = zext_ln60_19_fu_450_p1;
    end else begin
        features_2_conv_0_1_weight_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        features_2_conv_0_1_weight_address1_local = zext_ln60_21_fu_619_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        features_2_conv_0_1_weight_address1_local = zext_ln60_17_fu_437_p1;
    end else begin
        features_2_conv_0_1_weight_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        features_2_conv_0_1_weight_ce0_local = 1'b1;
    end else begin
        features_2_conv_0_1_weight_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        features_2_conv_0_1_weight_ce1_local = 1'b1;
    end else begin
        features_2_conv_0_1_weight_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_270_p0 = zext_ln60_22_fu_816_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_270_p0 = zext_ln60_18_fu_717_p1;
        end else begin
            grp_fu_270_p0 = 'bx;
        end
    end else begin
        grp_fu_270_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_270_p1 = shl_i_i_i140_i82_2_cast_fu_742_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_270_p1 = shl_i_i_i140_i82_cast_fu_692_p1;
        end else begin
            grp_fu_270_p1 = 'bx;
        end
    end else begin
        grp_fu_270_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_274_p0 = zext_ln60_24_fu_838_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_274_p0 = zext_ln60_20_fu_729_p1;
        end else begin
            grp_fu_274_p0 = 'bx;
        end
    end else begin
        grp_fu_274_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_274_p1 = sext_ln62_fu_755_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_274_p1 = shl_i_i_i140_i82_1_cast_fu_705_p1;
        end else begin
            grp_fu_274_p1 = 'bx;
        end
    end else begin
        grp_fu_274_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to4 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln55_1_fu_351_p2 = (h_fu_150 + 4'd1);

assign add_ln55_fu_328_p2 = (ap_sig_allocacmp_indvar_flatten52_load + 13'd1);

assign add_ln56_1_fu_397_p2 = (select_ln55_fu_363_p3 + 4'd1);

assign add_ln56_2_fu_455_p2 = (indvar_flatten39_fu_146 + 10'd1);

assign add_ln56_fu_514_p2 = (p_shl5_fu_503_p3 + zext_ln56_fu_510_p1);

assign add_ln57_fu_642_p2 = (oc_2_mid2_reg_1013 + 6'd1);

assign add_ln60_10_fu_858_p2 = ($signed(sext_ln60_49_fu_850_p1) + $signed(sext_ln60_11_fu_854_p1));

assign add_ln60_11_fu_886_p2 = ($signed(shl_ln60_14_fu_874_p3) + $signed(sext_ln60_12_fu_882_p1));

assign add_ln60_8_fu_771_p2 = ($signed(sext_ln60_8_fu_767_p1) + $signed(reg_286));

assign add_ln60_9_fu_803_p2 = ($signed(sext_ln60_fu_795_p1) + $signed(sext_ln60_48_fu_799_p1));

assign add_ln62_fu_636_p2 = (empty_117_fu_565_p2 + zext_ln58_1_fu_609_p1);

assign and_ln55_fu_383_p2 = (xor_ln55_fu_371_p2 & icmp_ln57_fu_377_p2);

assign and_ln62_fu_929_p2 = (xor_ln62_fu_923_p2 & tmp_57_fu_907_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign buf_B_address0 = buf_B_address0_local;

assign buf_B_address1 = buf_B_address1_local;

assign buf_B_ce0 = buf_B_ce0_local;

assign buf_B_ce1 = buf_B_ce1_local;

assign buf_exp_address1 = zext_ln62_fu_963_p1;

assign buf_exp_ce1 = buf_exp_ce1_local;

assign buf_exp_d1 = ref_tmp23_1_i_reg_1131;

assign buf_exp_we1 = buf_exp_we1_local;

assign empty_114_fu_497_p2 = (p_shl4_fu_479_p3 - p_shl17_fu_493_p1);

assign empty_115_fu_531_p2 = (p_cast67_fu_527_p1 + empty_114_fu_497_p2);

assign empty_116_fu_555_p2 = (p_shl_fu_537_p3 - p_shl13_fu_551_p1);

assign empty_117_fu_565_p2 = (p_cast69_fu_561_p1 + add_ln56_fu_514_p2);

assign empty_fu_403_p2 = (icmp_ln56_fu_357_p2 | and_ln55_fu_383_p2);

assign features_2_conv_0_1_bias_address0 = zext_ln58_fu_680_p1;

assign icmp_ln55_fu_322_p2 = ((ap_sig_allocacmp_indvar_flatten52_load == 13'd6912) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_357_p2 = ((indvar_flatten39_fu_146 == 10'd576) ? 1'b1 : 1'b0);

assign icmp_ln57_fu_377_p2 = ((oc_fu_138 == 6'd48) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_902_p2 = (($signed(trunc_ln60_4_reg_1126) > $signed(40'd393216)) ? 1'b1 : 1'b0);

assign oc_2_mid2_fu_409_p3 = ((empty_fu_403_p2[0:0] == 1'b1) ? 6'd0 : oc_fu_138);

assign or_ln60_7_fu_442_p3 = {{trunc_ln60_fu_425_p1}, {2'd1}};

assign or_ln60_8_fu_612_p3 = {{trunc_ln60_reg_1028}, {2'd2}};

assign or_ln60_9_fu_624_p3 = {{trunc_ln60_reg_1028}, {2'd3}};

assign p_cast159_fu_571_p1 = empty_115_fu_531_p2;

assign p_cast160_fu_594_p1 = tmp_64_fu_586_p3;

assign p_cast161_fu_663_p1 = tmp_66_fu_656_p3;

assign p_cast162_fu_675_p1 = tmp_67_fu_668_p3;

assign p_cast67_fu_527_p1 = tmp_s_fu_520_p3;

assign p_cast69_fu_561_p1 = empty_116_fu_555_p2;

assign p_shl13_fu_551_p1 = tmp_54_fu_544_p3;

assign p_shl17_fu_493_p1 = tmp_fu_486_p3;

assign p_shl4_fu_479_p3 = {{select_ln55_2_reg_1006}, {6'd0}};

assign p_shl5_fu_503_p3 = {{select_ln55_2_reg_1006}, {9'd0}};

assign p_shl_fu_537_p3 = {{select_ln56_reg_1020}, {6'd0}};

assign ref_tmp23_1_i_fu_943_p6 = {{add_ln60_11_reg_1120[39:24]}};

assign ref_tmp23_1_i_fu_943_p7 = 'bx;

assign ref_tmp23_1_i_fu_943_p8 = {{icmp_ln62_fu_902_p2}, {and_ln62_fu_929_p2}};

assign select_ln55_2_fu_389_p3 = ((icmp_ln56_fu_357_p2[0:0] == 1'b1) ? add_ln55_1_fu_351_p2 : h_fu_150);

assign select_ln55_fu_363_p3 = ((icmp_ln56_fu_357_p2[0:0] == 1'b1) ? 4'd0 : w_idx_fu_142);

assign select_ln56_2_fu_461_p3 = ((icmp_ln56_fu_357_p2[0:0] == 1'b1) ? 10'd1 : add_ln56_2_fu_455_p2);

assign select_ln56_fu_417_p3 = ((and_ln55_fu_383_p2[0:0] == 1'b1) ? add_ln56_1_fu_397_p2 : select_ln55_fu_363_p3);

assign sext_ln60_11_fu_854_p1 = $signed(reg_286);

assign sext_ln60_12_fu_882_p1 = $signed(reg_290);

assign sext_ln60_48_fu_799_p1 = $signed(reg_290);

assign sext_ln60_49_fu_850_p1 = $signed(tmp_56_fu_843_p3);

assign sext_ln60_8_fu_767_p1 = $signed(shl_ln60_s_fu_760_p3);

assign sext_ln60_fu_795_p1 = $signed(tmp_68_fu_787_p3);

assign sext_ln62_fu_755_p1 = $signed(shl_i_i_i140_i82_3_fu_747_p3);

assign shl_i_i_i140_i1_fu_684_p3 = {{reg_278}, {8'd0}};

assign shl_i_i_i140_i82_1_cast_fu_705_p1 = $signed(shl_i_i_i140_i82_1_fu_697_p3);

assign shl_i_i_i140_i82_1_fu_697_p3 = {{reg_282}, {8'd0}};

assign shl_i_i_i140_i82_2_cast_fu_742_p1 = $signed(shl_i_i_i140_i82_2_fu_734_p3);

assign shl_i_i_i140_i82_2_fu_734_p3 = {{reg_278}, {8'd0}};

assign shl_i_i_i140_i82_3_fu_747_p3 = {{reg_282}, {8'd0}};

assign shl_i_i_i140_i82_cast_fu_692_p1 = $signed(shl_i_i_i140_i1_fu_684_p3);

assign shl_ln60_10_fu_710_p3 = {{features_2_conv_0_1_weight_load_reg_1060}, {16'd0}};

assign shl_ln60_11_fu_722_p3 = {{features_2_conv_0_1_weight_load_1_reg_1065}, {16'd0}};

assign shl_ln60_12_fu_809_p3 = {{features_2_conv_0_1_weight_load_2_reg_1100}, {16'd0}};

assign shl_ln60_13_fu_831_p3 = {{features_2_conv_0_1_weight_load_3_reg_1105}, {16'd0}};

assign shl_ln60_14_fu_874_p3 = {{tmp_69_fu_864_p4}, {16'd0}};

assign shl_ln60_9_fu_429_p3 = {{trunc_ln60_fu_425_p1}, {2'd0}};

assign shl_ln60_s_fu_760_p3 = {{features_2_conv_0_1_bias_load_reg_1110}, {32'd0}};

assign tmp_54_fu_544_p3 = {{select_ln56_reg_1020}, {4'd0}};

assign tmp_56_fu_843_p3 = {{tmp_55_reg_1115}, {16'd0}};

assign tmp_57_fu_907_p3 = add_ln60_11_reg_1120[32'd55];

assign tmp_63_fu_576_p4 = {{empty_115_fu_531_p2[9:1]}};

assign tmp_64_fu_586_p3 = {{tmp_63_fu_576_p4}, {1'd1}};

assign tmp_66_fu_656_p3 = {{tmp_65_reg_1054}, {2'd2}};

assign tmp_67_fu_668_p3 = {{tmp_65_reg_1054}, {2'd3}};

assign tmp_68_fu_787_p3 = {{trunc_ln6_fu_777_p4}, {16'd0}};

assign tmp_69_fu_864_p4 = {{add_ln60_10_fu_858_p2[55:16]}};

assign tmp_fu_486_p3 = {{select_ln55_2_reg_1006}, {4'd0}};

assign tmp_s_fu_520_p3 = {{select_ln56_reg_1020}, {2'd0}};

assign trunc_ln60_fu_425_p1 = oc_2_mid2_fu_409_p3[4:0];

assign trunc_ln6_fu_777_p4 = {{add_ln60_8_fu_771_p2[46:16]}};

assign xor_ln55_fu_371_p2 = (icmp_ln56_fu_357_p2 ^ 1'd1);

assign xor_ln62_fu_923_p2 = (icmp_ln62_fu_902_p2 ^ 1'd1);

assign zext_ln56_fu_510_p1 = p_shl4_fu_479_p3;

assign zext_ln58_1_fu_609_p1 = oc_2_mid2_reg_1013;

assign zext_ln58_fu_680_p1 = oc_2_mid2_reg_1013;

assign zext_ln60_17_fu_437_p1 = shl_ln60_9_fu_429_p3;

assign zext_ln60_18_fu_717_p1 = shl_ln60_10_fu_710_p3;

assign zext_ln60_19_fu_450_p1 = or_ln60_7_fu_442_p3;

assign zext_ln60_20_fu_729_p1 = shl_ln60_11_fu_722_p3;

assign zext_ln60_21_fu_619_p1 = or_ln60_8_fu_612_p3;

assign zext_ln60_22_fu_816_p1 = shl_ln60_12_fu_809_p3;

assign zext_ln60_23_fu_631_p1 = or_ln60_9_fu_624_p3;

assign zext_ln60_24_fu_838_p1 = shl_ln60_13_fu_831_p3;

assign zext_ln62_fu_963_p1 = add_ln62_reg_1080_pp0_iter3_reg;

endmodule //mobilenet_top_mobilenet_top_Pipeline_VITIS_LOOP_55_1_VITIS_LOOP_56_2_VITIS_LOOP_57_31
