// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mobilenet_top_mobilenet_top_Pipeline_VITIS_LOOP_55_1_VITIS_LOOP_56_2_VITIS_LOOP_57_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buf_A_address0,
        buf_A_ce0,
        buf_A_q0,
        buf_A_address1,
        buf_A_ce1,
        buf_A_q1,
        buf_B_address1,
        buf_B_ce1,
        buf_B_we1,
        buf_B_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] buf_A_address0;
output   buf_A_ce0;
input  [15:0] buf_A_q0;
output  [11:0] buf_A_address1;
output   buf_A_ce1;
input  [15:0] buf_A_q1;
output  [11:0] buf_B_address1;
output   buf_B_ce1;
output   buf_B_we1;
output  [15:0] buf_B_d1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln55_reg_1217;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] features_1_conv_2_bias_address0;
wire   [7:0] features_1_conv_2_bias_q0;
wire   [6:0] features_1_conv_2_weight_q0;
wire   [6:0] features_1_conv_2_weight_q1;
reg   [6:0] reg_346;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire    ap_block_pp0_stage0_11001;
reg   [6:0] reg_350;
reg   [15:0] reg_354;
wire    ap_block_pp0_stage3_11001;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [15:0] reg_358;
reg   [6:0] reg_362;
reg   [6:0] reg_366;
wire   [39:0] grp_fu_338_p2;
reg   [39:0] reg_370;
wire   [39:0] grp_fu_342_p2;
reg   [39:0] reg_374;
wire   [0:0] icmp_ln55_fu_406_p2;
reg   [0:0] icmp_ln55_reg_1217_pp0_iter1_reg;
wire   [3:0] select_ln55_1_fu_473_p3;
reg   [3:0] select_ln55_1_reg_1221;
reg   [3:0] select_ln55_1_reg_1221_pp0_iter1_reg;
wire   [3:0] select_ln56_fu_501_p3;
reg   [3:0] select_ln56_reg_1229;
reg   [3:0] select_ln56_reg_1229_pp0_iter1_reg;
wire   [1:0] trunc_ln58_fu_509_p1;
reg   [1:0] trunc_ln58_reg_1236;
reg   [1:0] trunc_ln58_reg_1236_pp0_iter1_reg;
wire   [0:0] trunc_ln60_fu_518_p1;
reg   [0:0] trunc_ln60_reg_1246;
reg   [8:0] tmp_46_reg_1276;
reg   [7:0] tmp_51_reg_1282;
reg   [0:0] tmp_60_reg_1290;
reg   [7:0] features_1_conv_2_bias_load_reg_1295;
wire   [39:0] add_ln60_1_fu_922_p2;
reg   [39:0] add_ln60_1_reg_1360;
reg   [23:0] tmp_63_reg_1365;
wire   [39:0] add_ln60_5_fu_1066_p2;
reg   [39:0] add_ln60_5_reg_1370;
reg   [15:0] trunc_ln3_reg_1375;
wire    ap_block_pp0_stage1_subdone;
wire   [31:0] zext_ln58_fu_513_p1;
wire    ap_block_pp0_stage1;
wire   [31:0] zext_ln60_1_fu_530_p1;
wire   [31:0] zext_ln60_3_fu_543_p1;
wire   [31:0] zext_ln60_fu_624_p1;
wire    ap_block_pp0_stage2;
wire   [31:0] p_cast144_fu_647_p1;
wire   [31:0] zext_ln60_5_fu_687_p1;
wire   [31:0] zext_ln60_7_fu_699_p1;
wire   [31:0] p_cast145_fu_715_p1;
wire    ap_block_pp0_stage3;
wire   [31:0] p_cast146_fu_727_p1;
wire   [31:0] zext_ln60_9_fu_739_p1;
wire   [31:0] zext_ln60_11_fu_751_p1;
wire   [31:0] p_cast147_fu_789_p1;
wire    ap_block_pp0_stage0;
wire   [31:0] p_cast148_fu_804_p1;
wire   [31:0] zext_ln60_13_fu_842_p1;
wire   [31:0] zext_ln60_15_fu_854_p1;
wire   [31:0] p_cast149_fu_892_p1;
wire   [31:0] p_cast150_fu_904_p1;
wire   [31:0] zext_ln63_fu_1177_p1;
reg   [2:0] oc_fu_142;
wire   [2:0] add_ln57_fu_548_p2;
wire    ap_loop_init;
reg   [3:0] w_idx_fu_146;
reg   [6:0] indvar_flatten19_fu_150;
wire   [6:0] select_ln56_1_fu_560_p3;
reg   [3:0] h_fu_154;
reg   [9:0] indvar_flatten32_fu_158;
wire   [9:0] add_ln55_2_fu_412_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten32_load;
reg    features_1_conv_2_bias_ce0_local;
reg    features_1_conv_2_weight_ce1_local;
reg   [3:0] features_1_conv_2_weight_address1_local;
reg    features_1_conv_2_weight_ce0_local;
reg   [3:0] features_1_conv_2_weight_address0_local;
reg    buf_A_ce1_local;
reg   [11:0] buf_A_address1_local;
reg    buf_A_ce0_local;
reg   [11:0] buf_A_address0_local;
reg    buf_B_we1_local;
reg    buf_B_ce1_local;
reg   [22:0] grp_fu_338_p0;
wire   [39:0] zext_ln60_2_fu_817_p1;
wire   [39:0] zext_ln60_6_fu_936_p1;
wire   [39:0] zext_ln60_10_fu_1009_p1;
wire   [39:0] zext_ln60_14_fu_1080_p1;
reg  signed [23:0] grp_fu_338_p1;
wire  signed [39:0] sext_ln60_fu_764_p1;
wire  signed [39:0] sext_ln60_2_fu_867_p1;
wire  signed [39:0] sext_ln60_4_fu_962_p1;
wire  signed [39:0] sext_ln60_6_fu_1035_p1;
reg   [22:0] grp_fu_342_p0;
wire   [39:0] zext_ln60_4_fu_830_p1;
wire   [39:0] zext_ln60_8_fu_949_p1;
wire   [39:0] zext_ln60_12_fu_1022_p1;
wire   [39:0] zext_ln60_16_fu_1093_p1;
reg  signed [23:0] grp_fu_342_p1;
wire  signed [39:0] sext_ln60_1_fu_777_p1;
wire  signed [39:0] sext_ln60_3_fu_880_p1;
wire  signed [39:0] sext_ln60_5_fu_975_p1;
wire  signed [39:0] sext_ln60_7_fu_1048_p1;
wire   [0:0] icmp_ln56_fu_441_p2;
wire   [0:0] icmp_ln57_fu_461_p2;
wire   [0:0] xor_ln55_fu_455_p2;
wire   [3:0] add_ln55_fu_435_p2;
wire   [3:0] select_ln55_fu_447_p3;
wire   [0:0] and_ln55_fu_467_p2;
wire   [0:0] empty_fu_487_p2;
wire   [3:0] add_ln56_fu_481_p2;
wire   [2:0] oc_1_mid2_fu_493_p3;
wire   [3:0] shl_ln3_fu_522_p3;
wire   [3:0] or_ln1_fu_535_p3;
wire   [6:0] add_ln56_3_fu_554_p2;
wire   [8:0] tmp_fu_590_p3;
wire   [10:0] p_shl5_fu_583_p3;
wire   [10:0] p_shl6_fu_597_p1;
wire   [6:0] tmp_42_fu_607_p3;
wire   [10:0] p_cast47_fu_614_p1;
wire   [10:0] empty_118_fu_601_p2;
wire   [10:0] empty_120_fu_618_p2;
wire   [9:0] tmp_44_fu_629_p4;
wire   [10:0] tmp_45_fu_639_p3;
wire   [3:0] or_ln60_1_fu_680_p3;
wire   [3:0] or_ln60_2_fu_692_p3;
wire   [10:0] tmp_48_fu_708_p3;
wire   [10:0] tmp_50_fu_720_p3;
wire   [3:0] or_ln60_3_fu_732_p3;
wire   [3:0] or_ln60_4_fu_744_p3;
wire   [23:0] shl_i_i_i140_i_fu_756_p3;
wire   [23:0] shl_i_i_i140_i_1_fu_769_p3;
wire   [10:0] tmp_53_fu_782_p3;
wire   [10:0] tmp_56_fu_794_p5;
wire   [22:0] shl_ln60_1_fu_809_p3;
wire   [22:0] shl_ln60_2_fu_822_p3;
wire   [3:0] or_ln60_5_fu_835_p3;
wire   [3:0] or_ln60_6_fu_847_p3;
wire   [23:0] shl_i_i_i140_i_2_fu_859_p3;
wire   [23:0] shl_i_i_i140_i_3_fu_872_p3;
wire   [10:0] tmp_59_fu_885_p3;
wire   [10:0] tmp_61_fu_897_p3;
wire   [39:0] shl_ln60_s_fu_909_p3;
wire   [39:0] add_ln60_fu_916_p2;
wire   [22:0] shl_ln60_3_fu_928_p3;
wire   [22:0] shl_ln60_4_fu_941_p3;
wire   [23:0] shl_i_i_i140_i_4_fu_954_p3;
wire   [23:0] shl_i_i_i140_i_5_fu_967_p3;
wire   [39:0] add_ln60_2_fu_980_p2;
wire   [39:0] add_ln60_3_fu_985_p2;
wire   [22:0] shl_ln60_5_fu_1001_p3;
wire   [22:0] shl_ln60_6_fu_1014_p3;
wire   [23:0] shl_i_i_i140_i_6_fu_1027_p3;
wire   [23:0] shl_i_i_i140_i_7_fu_1040_p3;
wire   [39:0] and_ln_fu_1053_p3;
wire   [39:0] add_ln60_4_fu_1060_p2;
wire   [22:0] shl_ln60_7_fu_1072_p3;
wire   [22:0] shl_ln60_8_fu_1085_p3;
wire   [39:0] add_ln60_6_fu_1098_p2;
wire   [39:0] add_ln60_7_fu_1103_p2;
wire   [7:0] tmp_58_fu_1126_p3;
wire   [9:0] p_shl_fu_1119_p3;
wire   [9:0] p_shl4_fu_1133_p1;
wire   [5:0] tmp_43_fu_1143_p3;
wire   [9:0] p_cast49_fu_1150_p1;
wire   [9:0] empty_119_fu_1137_p2;
wire   [9:0] empty_121_fu_1154_p2;
wire   [7:0] tmp_6_fu_1160_p4;
wire   [9:0] add_ln_fu_1170_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage1;
reg    ap_idle_pp0_0to0;
reg   [3:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 oc_fu_142 = 3'd0;
#0 w_idx_fu_146 = 4'd0;
#0 indvar_flatten19_fu_150 = 7'd0;
#0 h_fu_154 = 4'd0;
#0 indvar_flatten32_fu_158 = 10'd0;
#0 ap_done_reg = 1'b0;
end

mobilenet_top_mobilenet_top_Pipeline_VITIS_LOOP_55_1_VITIS_LOOP_56_2_VITIS_LOOP_57_3_featurdEe #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
features_1_conv_2_bias_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(features_1_conv_2_bias_address0),
    .ce0(features_1_conv_2_bias_ce0_local),
    .q0(features_1_conv_2_bias_q0)
);

mobilenet_top_mobilenet_top_Pipeline_VITIS_LOOP_55_1_VITIS_LOOP_56_2_VITIS_LOOP_57_3_featureOg #(
    .DataWidth( 7 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
features_1_conv_2_weight_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(features_1_conv_2_weight_address0_local),
    .ce0(features_1_conv_2_weight_ce0_local),
    .q0(features_1_conv_2_weight_q0),
    .address1(features_1_conv_2_weight_address1_local),
    .ce1(features_1_conv_2_weight_ce1_local),
    .q1(features_1_conv_2_weight_q1)
);

mobilenet_top_mul_23ns_24s_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 40 ))
mul_23ns_24s_40_1_1_U37(
    .din0(grp_fu_338_p0),
    .din1(grp_fu_338_p1),
    .dout(grp_fu_338_p2)
);

mobilenet_top_mul_23ns_24s_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 40 ))
mul_23ns_24s_40_1_1_U38(
    .din0(grp_fu_342_p0),
    .din1(grp_fu_342_p1),
    .dout(grp_fu_342_p2)
);

mobilenet_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        h_fu_154 <= 4'd0;
    end else if (((icmp_ln55_reg_1217 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        h_fu_154 <= select_ln55_1_fu_473_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten19_fu_150 <= 7'd0;
    end else if (((icmp_ln55_reg_1217 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        indvar_flatten19_fu_150 <= select_ln56_1_fu_560_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln55_fu_406_p2 == 1'd0))) begin
            indvar_flatten32_fu_158 <= add_ln55_2_fu_412_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten32_fu_158 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        oc_fu_142 <= 3'd0;
    end else if (((icmp_ln55_reg_1217 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        oc_fu_142 <= add_ln57_fu_548_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_idx_fu_146 <= 4'd0;
    end else if (((icmp_ln55_reg_1217 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        w_idx_fu_146 <= select_ln56_reg_1229;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln60_1_reg_1360 <= add_ln60_1_fu_922_p2;
        select_ln55_1_reg_1221 <= select_ln55_1_fu_473_p3;
        select_ln55_1_reg_1221_pp0_iter1_reg <= select_ln55_1_reg_1221;
        select_ln56_reg_1229 <= select_ln56_fu_501_p3;
        select_ln56_reg_1229_pp0_iter1_reg <= select_ln56_reg_1229;
        trunc_ln58_reg_1236 <= trunc_ln58_fu_509_p1;
        trunc_ln58_reg_1236_pp0_iter1_reg <= trunc_ln58_reg_1236;
        trunc_ln60_reg_1246 <= trunc_ln60_fu_518_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln60_5_reg_1370 <= add_ln60_5_fu_1066_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        features_1_conv_2_bias_load_reg_1295 <= features_1_conv_2_bias_q0;
        tmp_46_reg_1276 <= {{empty_120_fu_618_p2[10:2]}};
        tmp_51_reg_1282 <= {{empty_120_fu_618_p2[10:3]}};
        tmp_60_reg_1290 <= empty_120_fu_618_p2[32'd1];
        tmp_63_reg_1365 <= {{add_ln60_3_fu_985_p2[39:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln55_reg_1217 <= icmp_ln55_fu_406_p2;
        icmp_ln55_reg_1217_pp0_iter1_reg <= icmp_ln55_reg_1217;
        trunc_ln3_reg_1375 <= {{add_ln60_7_fu_1103_p2[39:24]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_346 <= features_1_conv_2_weight_q1;
        reg_350 <= features_1_conv_2_weight_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_354 <= buf_A_q1;
        reg_358 <= buf_A_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_362 <= features_1_conv_2_weight_q1;
        reg_366 <= features_1_conv_2_weight_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_370 <= grp_fu_338_p2;
        reg_374 <= grp_fu_342_p2;
    end
end

always @ (*) begin
    if (((icmp_ln55_reg_1217 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln55_reg_1217_pp0_iter1_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten32_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten32_load = indvar_flatten32_fu_158;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_A_address0_local = p_cast150_fu_904_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_A_address0_local = p_cast148_fu_804_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        buf_A_address0_local = p_cast146_fu_727_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        buf_A_address0_local = p_cast144_fu_647_p1;
    end else begin
        buf_A_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_A_address1_local = p_cast149_fu_892_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_A_address1_local = p_cast147_fu_789_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        buf_A_address1_local = p_cast145_fu_715_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        buf_A_address1_local = zext_ln60_fu_624_p1;
    end else begin
        buf_A_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_A_ce0_local = 1'b1;
    end else begin
        buf_A_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_A_ce1_local = 1'b1;
    end else begin
        buf_A_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_B_ce1_local = 1'b1;
    end else begin
        buf_B_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_B_we1_local = 1'b1;
    end else begin
        buf_B_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        features_1_conv_2_bias_ce0_local = 1'b1;
    end else begin
        features_1_conv_2_bias_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        features_1_conv_2_weight_address0_local = zext_ln60_15_fu_854_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        features_1_conv_2_weight_address0_local = zext_ln60_11_fu_751_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        features_1_conv_2_weight_address0_local = zext_ln60_7_fu_699_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        features_1_conv_2_weight_address0_local = zext_ln60_3_fu_543_p1;
    end else begin
        features_1_conv_2_weight_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        features_1_conv_2_weight_address1_local = zext_ln60_13_fu_842_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        features_1_conv_2_weight_address1_local = zext_ln60_9_fu_739_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        features_1_conv_2_weight_address1_local = zext_ln60_5_fu_687_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        features_1_conv_2_weight_address1_local = zext_ln60_1_fu_530_p1;
    end else begin
        features_1_conv_2_weight_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        features_1_conv_2_weight_ce0_local = 1'b1;
    end else begin
        features_1_conv_2_weight_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        features_1_conv_2_weight_ce1_local = 1'b1;
    end else begin
        features_1_conv_2_weight_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_338_p0 = zext_ln60_14_fu_1080_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_338_p0 = zext_ln60_10_fu_1009_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_338_p0 = zext_ln60_6_fu_936_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_338_p0 = zext_ln60_2_fu_817_p1;
        end else begin
            grp_fu_338_p0 = 'bx;
        end
    end else begin
        grp_fu_338_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_338_p1 = sext_ln60_6_fu_1035_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_338_p1 = sext_ln60_4_fu_962_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_338_p1 = sext_ln60_2_fu_867_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_338_p1 = sext_ln60_fu_764_p1;
        end else begin
            grp_fu_338_p1 = 'bx;
        end
    end else begin
        grp_fu_338_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_342_p0 = zext_ln60_16_fu_1093_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_342_p0 = zext_ln60_12_fu_1022_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_342_p0 = zext_ln60_8_fu_949_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_342_p0 = zext_ln60_4_fu_830_p1;
        end else begin
            grp_fu_342_p0 = 'bx;
        end
    end else begin
        grp_fu_342_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_342_p1 = sext_ln60_7_fu_1048_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_342_p1 = sext_ln60_5_fu_975_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_342_p1 = sext_ln60_3_fu_880_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_342_p1 = sext_ln60_1_fu_777_p1;
        end else begin
            grp_fu_342_p1 = 'bx;
        end
    end else begin
        grp_fu_342_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln55_2_fu_412_p2 = (ap_sig_allocacmp_indvar_flatten32_load + 10'd1);

assign add_ln55_fu_435_p2 = (h_fu_154 + 4'd1);

assign add_ln56_3_fu_554_p2 = (indvar_flatten19_fu_150 + 7'd1);

assign add_ln56_fu_481_p2 = (select_ln55_fu_447_p3 + 4'd1);

assign add_ln57_fu_548_p2 = (oc_1_mid2_fu_493_p3 + 3'd1);

assign add_ln60_1_fu_922_p2 = (add_ln60_fu_916_p2 + reg_374);

assign add_ln60_2_fu_980_p2 = (add_ln60_1_reg_1360 + reg_370);

assign add_ln60_3_fu_985_p2 = (add_ln60_2_fu_980_p2 + reg_374);

assign add_ln60_4_fu_1060_p2 = (and_ln_fu_1053_p3 + reg_370);

assign add_ln60_5_fu_1066_p2 = (add_ln60_4_fu_1060_p2 + reg_374);

assign add_ln60_6_fu_1098_p2 = (add_ln60_5_reg_1370 + reg_370);

assign add_ln60_7_fu_1103_p2 = (add_ln60_6_fu_1098_p2 + reg_374);

assign add_ln60_fu_916_p2 = (shl_ln60_s_fu_909_p3 + reg_370);

assign add_ln_fu_1170_p3 = {{tmp_6_fu_1160_p4}, {trunc_ln58_reg_1236_pp0_iter1_reg}};

assign and_ln55_fu_467_p2 = (xor_ln55_fu_455_p2 & icmp_ln57_fu_461_p2);

assign and_ln_fu_1053_p3 = {{tmp_63_reg_1365}, {16'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign ap_ready = ap_ready_sig;

assign buf_A_address0 = buf_A_address0_local;

assign buf_A_address1 = buf_A_address1_local;

assign buf_A_ce0 = buf_A_ce0_local;

assign buf_A_ce1 = buf_A_ce1_local;

assign buf_B_address1 = zext_ln63_fu_1177_p1;

assign buf_B_ce1 = buf_B_ce1_local;

assign buf_B_d1 = trunc_ln3_reg_1375;

assign buf_B_we1 = buf_B_we1_local;

assign empty_118_fu_601_p2 = (p_shl5_fu_583_p3 - p_shl6_fu_597_p1);

assign empty_119_fu_1137_p2 = (p_shl_fu_1119_p3 - p_shl4_fu_1133_p1);

assign empty_120_fu_618_p2 = (p_cast47_fu_614_p1 + empty_118_fu_601_p2);

assign empty_121_fu_1154_p2 = (p_cast49_fu_1150_p1 + empty_119_fu_1137_p2);

assign empty_fu_487_p2 = (icmp_ln56_fu_441_p2 | and_ln55_fu_467_p2);

assign features_1_conv_2_bias_address0 = zext_ln58_fu_513_p1;

assign icmp_ln55_fu_406_p2 = ((ap_sig_allocacmp_indvar_flatten32_load == 10'd576) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_441_p2 = ((indvar_flatten19_fu_150 == 7'd48) ? 1'b1 : 1'b0);

assign icmp_ln57_fu_461_p2 = ((oc_fu_142 == 3'd4) ? 1'b1 : 1'b0);

assign oc_1_mid2_fu_493_p3 = ((empty_fu_487_p2[0:0] == 1'b1) ? 3'd0 : oc_fu_142);

assign or_ln1_fu_535_p3 = {{trunc_ln60_fu_518_p1}, {3'd1}};

assign or_ln60_1_fu_680_p3 = {{trunc_ln60_reg_1246}, {3'd2}};

assign or_ln60_2_fu_692_p3 = {{trunc_ln60_reg_1246}, {3'd3}};

assign or_ln60_3_fu_732_p3 = {{trunc_ln60_reg_1246}, {3'd4}};

assign or_ln60_4_fu_744_p3 = {{trunc_ln60_reg_1246}, {3'd5}};

assign or_ln60_5_fu_835_p3 = {{trunc_ln60_reg_1246}, {3'd6}};

assign or_ln60_6_fu_847_p3 = {{trunc_ln60_reg_1246}, {3'd7}};

assign p_cast144_fu_647_p1 = tmp_45_fu_639_p3;

assign p_cast145_fu_715_p1 = tmp_48_fu_708_p3;

assign p_cast146_fu_727_p1 = tmp_50_fu_720_p3;

assign p_cast147_fu_789_p1 = tmp_53_fu_782_p3;

assign p_cast148_fu_804_p1 = tmp_56_fu_794_p5;

assign p_cast149_fu_892_p1 = tmp_59_fu_885_p3;

assign p_cast150_fu_904_p1 = tmp_61_fu_897_p3;

assign p_cast47_fu_614_p1 = tmp_42_fu_607_p3;

assign p_cast49_fu_1150_p1 = tmp_43_fu_1143_p3;

assign p_shl4_fu_1133_p1 = tmp_58_fu_1126_p3;

assign p_shl5_fu_583_p3 = {{select_ln55_1_reg_1221}, {7'd0}};

assign p_shl6_fu_597_p1 = tmp_fu_590_p3;

assign p_shl_fu_1119_p3 = {{select_ln55_1_reg_1221_pp0_iter1_reg}, {6'd0}};

assign select_ln55_1_fu_473_p3 = ((icmp_ln56_fu_441_p2[0:0] == 1'b1) ? add_ln55_fu_435_p2 : h_fu_154);

assign select_ln55_fu_447_p3 = ((icmp_ln56_fu_441_p2[0:0] == 1'b1) ? 4'd0 : w_idx_fu_146);

assign select_ln56_1_fu_560_p3 = ((icmp_ln56_fu_441_p2[0:0] == 1'b1) ? 7'd1 : add_ln56_3_fu_554_p2);

assign select_ln56_fu_501_p3 = ((and_ln55_fu_467_p2[0:0] == 1'b1) ? add_ln56_fu_481_p2 : select_ln55_fu_447_p3);

assign sext_ln60_1_fu_777_p1 = $signed(shl_i_i_i140_i_1_fu_769_p3);

assign sext_ln60_2_fu_867_p1 = $signed(shl_i_i_i140_i_2_fu_859_p3);

assign sext_ln60_3_fu_880_p1 = $signed(shl_i_i_i140_i_3_fu_872_p3);

assign sext_ln60_4_fu_962_p1 = $signed(shl_i_i_i140_i_4_fu_954_p3);

assign sext_ln60_5_fu_975_p1 = $signed(shl_i_i_i140_i_5_fu_967_p3);

assign sext_ln60_6_fu_1035_p1 = $signed(shl_i_i_i140_i_6_fu_1027_p3);

assign sext_ln60_7_fu_1048_p1 = $signed(shl_i_i_i140_i_7_fu_1040_p3);

assign sext_ln60_fu_764_p1 = $signed(shl_i_i_i140_i_fu_756_p3);

assign shl_i_i_i140_i_1_fu_769_p3 = {{reg_358}, {8'd0}};

assign shl_i_i_i140_i_2_fu_859_p3 = {{reg_354}, {8'd0}};

assign shl_i_i_i140_i_3_fu_872_p3 = {{reg_358}, {8'd0}};

assign shl_i_i_i140_i_4_fu_954_p3 = {{reg_354}, {8'd0}};

assign shl_i_i_i140_i_5_fu_967_p3 = {{reg_358}, {8'd0}};

assign shl_i_i_i140_i_6_fu_1027_p3 = {{reg_354}, {8'd0}};

assign shl_i_i_i140_i_7_fu_1040_p3 = {{reg_358}, {8'd0}};

assign shl_i_i_i140_i_fu_756_p3 = {{reg_354}, {8'd0}};

assign shl_ln3_fu_522_p3 = {{trunc_ln60_fu_518_p1}, {3'd0}};

assign shl_ln60_1_fu_809_p3 = {{reg_346}, {16'd0}};

assign shl_ln60_2_fu_822_p3 = {{reg_350}, {16'd0}};

assign shl_ln60_3_fu_928_p3 = {{reg_362}, {16'd0}};

assign shl_ln60_4_fu_941_p3 = {{reg_366}, {16'd0}};

assign shl_ln60_5_fu_1001_p3 = {{reg_346}, {16'd0}};

assign shl_ln60_6_fu_1014_p3 = {{reg_350}, {16'd0}};

assign shl_ln60_7_fu_1072_p3 = {{reg_362}, {16'd0}};

assign shl_ln60_8_fu_1085_p3 = {{reg_366}, {16'd0}};

assign shl_ln60_s_fu_909_p3 = {{features_1_conv_2_bias_load_reg_1295}, {32'd0}};

assign tmp_42_fu_607_p3 = {{select_ln56_reg_1229}, {3'd0}};

assign tmp_43_fu_1143_p3 = {{select_ln56_reg_1229_pp0_iter1_reg}, {2'd0}};

assign tmp_44_fu_629_p4 = {{empty_120_fu_618_p2[10:1]}};

assign tmp_45_fu_639_p3 = {{tmp_44_fu_629_p4}, {1'd1}};

assign tmp_48_fu_708_p3 = {{tmp_46_reg_1276}, {2'd2}};

assign tmp_50_fu_720_p3 = {{tmp_46_reg_1276}, {2'd3}};

assign tmp_53_fu_782_p3 = {{tmp_51_reg_1282}, {3'd4}};

assign tmp_56_fu_794_p5 = {{{{tmp_51_reg_1282}, {1'd1}}, {tmp_60_reg_1290}}, {1'd1}};

assign tmp_58_fu_1126_p3 = {{select_ln55_1_reg_1221_pp0_iter1_reg}, {4'd0}};

assign tmp_59_fu_885_p3 = {{tmp_51_reg_1282}, {3'd6}};

assign tmp_61_fu_897_p3 = {{tmp_51_reg_1282}, {3'd7}};

assign tmp_6_fu_1160_p4 = {{empty_121_fu_1154_p2[9:2]}};

assign tmp_fu_590_p3 = {{select_ln55_1_reg_1221}, {5'd0}};

assign trunc_ln58_fu_509_p1 = oc_1_mid2_fu_493_p3[1:0];

assign trunc_ln60_fu_518_p1 = oc_1_mid2_fu_493_p3[0:0];

assign xor_ln55_fu_455_p2 = (icmp_ln56_fu_441_p2 ^ 1'd1);

assign zext_ln58_fu_513_p1 = trunc_ln58_fu_509_p1;

assign zext_ln60_10_fu_1009_p1 = shl_ln60_5_fu_1001_p3;

assign zext_ln60_11_fu_751_p1 = or_ln60_4_fu_744_p3;

assign zext_ln60_12_fu_1022_p1 = shl_ln60_6_fu_1014_p3;

assign zext_ln60_13_fu_842_p1 = or_ln60_5_fu_835_p3;

assign zext_ln60_14_fu_1080_p1 = shl_ln60_7_fu_1072_p3;

assign zext_ln60_15_fu_854_p1 = or_ln60_6_fu_847_p3;

assign zext_ln60_16_fu_1093_p1 = shl_ln60_8_fu_1085_p3;

assign zext_ln60_1_fu_530_p1 = shl_ln3_fu_522_p3;

assign zext_ln60_2_fu_817_p1 = shl_ln60_1_fu_809_p3;

assign zext_ln60_3_fu_543_p1 = or_ln1_fu_535_p3;

assign zext_ln60_4_fu_830_p1 = shl_ln60_2_fu_822_p3;

assign zext_ln60_5_fu_687_p1 = or_ln60_1_fu_680_p3;

assign zext_ln60_6_fu_936_p1 = shl_ln60_3_fu_928_p3;

assign zext_ln60_7_fu_699_p1 = or_ln60_2_fu_692_p3;

assign zext_ln60_8_fu_949_p1 = shl_ln60_4_fu_941_p3;

assign zext_ln60_9_fu_739_p1 = or_ln60_3_fu_732_p3;

assign zext_ln60_fu_624_p1 = empty_120_fu_618_p2;

assign zext_ln63_fu_1177_p1 = add_ln_fu_1170_p3;

endmodule //mobilenet_top_mobilenet_top_Pipeline_VITIS_LOOP_55_1_VITIS_LOOP_56_2_VITIS_LOOP_57_3
