#/***************************************************************************
# * Project           		 : shakti devt board
# * Name of the file	     	 : gdb.script
# * Brief Description of file    : iniatilise options for gdb
# * Name of Author    	         : Sathya Narayanan N
# * Email ID                     : sathya281@gmail.com
#
# Copyright (C) 2019  IIT Madras. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#***************************************************************************/
set remotetimeout unlimited
target remote localhost:3333
#Baud rate 9600
#set {short}0x11300=325
#Baud rate 19200
set {short}0x11300=163
#Baud rate 37800
#set {short}0x11300=82
#Baud rate 57600
#set {short}0x11300=54
#Baud rate 115200
#set {short}0x11300=27
#Baud rate 230400
#set {short}0x11300=12
#Baud rate 460800
#set {short}0x11300=7


