# Created by Sathya Narayanan N
# Email id: sathya281@gmail.com

# Copyright (C) 2019 IIT Madras. All rights reserved.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>

SHELL := /bin/bash # Use bash syntax
DC ?=
PROGRAM ?= sd_boot
#default target board
FLAGS ?=
SD_DIR= ./sdcard/

all: create_dir
	make $(PROGRAM).riscv 

$(PROGRAM).riscv: create_dir
	@riscv$(XLEN)-unknown-elf-gcc  -march=$(MARCH)  -mabi=$(MABI) -w $(DC) -mcmodel=medany -static -std=gnu99 -fno-builtin-printf  -I$(bspinc) -I$(bspdri) -I$(bspboard) -I$(SD_DIR)	$(FLAGS) -c ./spicntrl.c -o ./output/spicntrl.o 
	@riscv$(XLEN)-unknown-elf-gcc  -march=$(MARCH)  -mabi=$(MABI) -w $(DC) -mcmodel=medany -static -std=gnu99 -fno-builtin-printf  -I$(bspinc) -I$(bspdri) -I$(bspboard) -I$(SD_DIR)	$(FLAGS) -c $(SD_DIR)/ff.c -o ./output/ff.o 
	@riscv$(XLEN)-unknown-elf-gcc  -march=$(MARCH)  -mabi=$(MABI) -w $(DC) -mcmodel=medany -static -std=gnu99 -fno-builtin-printf  -I$(bspinc) -I$(bspdri) -I$(bspboard) -I$(SD_DIR)	$(FLAGS) -c ./$(PROGRAM).c -o ./output/$(PROGRAM).o 
	@echo "Linking files"
	@riscv$(XLEN)-unknown-elf-gcc -T $(bspboard)/link.ld ./../gen_lib/sspi.o ./output/$(PROGRAM).o   $(GENLIB)/gen_lib/libshakti$(XLEN).a  ./output/ff.o ./output/spicntrl.o  -o ./output/$(PROGRAM).shakti -mcmodel=medany -march=$(MARCH)  -mabi=$(MABI) -static -nostartfiles -lm -lgcc
	@riscv$(XLEN)-unknown-elf-objdump -D ./output/$(PROGRAM).shakti &> ./output/$(PROGRAM).dump
create_dir:
	@mkdir -p ./output


#  $(GENLIB)/gen_lib/libshakti$(XLEN).a 