-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_accel_cnn_accel_Pipeline_VITIS_LOOP_34_3_VITIS_LOOP_35_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ty : IN STD_LOGIC_VECTOR (30 downto 0);
    size : IN STD_LOGIC_VECTOR (31 downto 0);
    tile_in_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    tile_in_ce0 : OUT STD_LOGIC;
    tile_in_we0 : OUT STD_LOGIC;
    tile_in_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    tile_in_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    tile_in_1_ce0 : OUT STD_LOGIC;
    tile_in_1_we0 : OUT STD_LOGIC;
    tile_in_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    tile_in_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    tile_in_2_ce0 : OUT STD_LOGIC;
    tile_in_2_we0 : OUT STD_LOGIC;
    tile_in_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    tx : IN STD_LOGIC_VECTOR (30 downto 0);
    input_r_load : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of cnn_accel_cnn_accel_Pipeline_VITIS_LOOP_34_3_VITIS_LOOP_35_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln34_fu_163_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tx_cast_fu_137_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tx_cast_reg_324 : STD_LOGIC_VECTOR (31 downto 0);
    signal ty_cast_fu_141_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ty_cast_reg_329 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_fu_230_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_reg_338 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln44_fu_239_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln44_reg_343 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln39_fu_249_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln39_reg_348 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln44_1_fu_274_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal x_fu_62 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln35_fu_254_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal y_fu_66 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln34_1_fu_206_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten_fu_70 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln34_1_fu_169_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (10 downto 0);
    signal tile_in_we0_local : STD_LOGIC;
    signal and_ln41_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tile_in_ce0_local : STD_LOGIC;
    signal tile_in_1_we0_local : STD_LOGIC;
    signal tile_in_1_ce0_local : STD_LOGIC;
    signal tile_in_2_we0_local : STD_LOGIC;
    signal tile_in_2_ce0_local : STD_LOGIC;
    signal icmp_ln35_fu_192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln34_fu_186_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln44_fu_214_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln34_fu_226_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln34_fu_198_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_1_fu_218_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln44_fu_235_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln35_fu_245_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal cmp14_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_fu_280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cnn_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component cnn_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln34_fu_163_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_70 <= add_ln34_1_fu_169_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_70 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    x_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_62 <= ap_const_lv6_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_fu_62 <= add_ln35_fu_254_p2;
                end if;
            end if; 
        end if;
    end process;

    y_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    y_fu_66 <= ap_const_lv6_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    y_fu_66 <= select_ln34_1_fu_206_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln39_reg_348 <= add_ln39_fu_249_p2;
                add_ln44_reg_343 <= add_ln44_fu_239_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                empty_reg_338 <= empty_fu_230_p2;
                    tx_cast_reg_324(30 downto 0) <= tx_cast_fu_137_p1(30 downto 0);
                    ty_cast_reg_329(30 downto 0) <= ty_cast_fu_141_p1(30 downto 0);
            end if;
        end if;
    end process;
    tx_cast_reg_324(31) <= '0';
    ty_cast_reg_329(31) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln34_1_fu_169_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv11_1));
    add_ln34_fu_186_p2 <= std_logic_vector(unsigned(y_fu_66) + unsigned(ap_const_lv6_1));
    add_ln35_fu_254_p2 <= std_logic_vector(unsigned(select_ln34_fu_198_p3) + unsigned(ap_const_lv6_1));
    add_ln39_fu_249_p2 <= std_logic_vector(unsigned(zext_ln35_fu_245_p1) + unsigned(tx_cast_reg_324));
    add_ln44_fu_239_p2 <= std_logic_vector(unsigned(tmp_1_fu_218_p3) + unsigned(zext_ln44_fu_235_p1));
    and_ln41_fu_284_p2 <= (icmp_ln41_fu_280_p2 and cmp14_fu_270_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln34_fu_163_p2)
    begin
        if (((icmp_ln34_fu_163_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_70)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_70;
        end if; 
    end process;

    cmp14_fu_270_p2 <= "1" when (signed(empty_reg_338) < signed(size)) else "0";
    empty_fu_230_p2 <= std_logic_vector(unsigned(zext_ln34_fu_226_p1) + unsigned(ty_cast_reg_329));
    icmp_ln34_fu_163_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv11_400) else "0";
    icmp_ln35_fu_192_p2 <= "1" when (x_fu_62 = ap_const_lv6_20) else "0";
    icmp_ln41_fu_280_p2 <= "1" when (signed(add_ln39_reg_348) < signed(size)) else "0";
    select_ln34_1_fu_206_p3 <= 
        add_ln34_fu_186_p2 when (icmp_ln35_fu_192_p2(0) = '1') else 
        y_fu_66;
    select_ln34_fu_198_p3 <= 
        ap_const_lv6_0 when (icmp_ln35_fu_192_p2(0) = '1') else 
        x_fu_62;
    tile_in_1_address0 <= zext_ln44_1_fu_274_p1(10 - 1 downto 0);
    tile_in_1_ce0 <= tile_in_1_ce0_local;

    tile_in_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tile_in_1_ce0_local <= ap_const_logic_1;
        else 
            tile_in_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tile_in_1_d0 <= input_r_load;
    tile_in_1_we0 <= tile_in_1_we0_local;

    tile_in_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, and_ln41_fu_284_p2)
    begin
        if (((ap_const_lv1_1 = and_ln41_fu_284_p2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tile_in_1_we0_local <= ap_const_logic_1;
        else 
            tile_in_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    tile_in_2_address0 <= zext_ln44_1_fu_274_p1(10 - 1 downto 0);
    tile_in_2_ce0 <= tile_in_2_ce0_local;

    tile_in_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tile_in_2_ce0_local <= ap_const_logic_1;
        else 
            tile_in_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tile_in_2_d0 <= input_r_load;
    tile_in_2_we0 <= tile_in_2_we0_local;

    tile_in_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, and_ln41_fu_284_p2)
    begin
        if (((ap_const_lv1_1 = and_ln41_fu_284_p2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tile_in_2_we0_local <= ap_const_logic_1;
        else 
            tile_in_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    tile_in_address0 <= zext_ln44_1_fu_274_p1(10 - 1 downto 0);
    tile_in_ce0 <= tile_in_ce0_local;

    tile_in_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tile_in_ce0_local <= ap_const_logic_1;
        else 
            tile_in_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tile_in_d0 <= input_r_load;
    tile_in_we0 <= tile_in_we0_local;

    tile_in_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, and_ln41_fu_284_p2)
    begin
        if (((ap_const_lv1_1 = and_ln41_fu_284_p2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tile_in_we0_local <= ap_const_logic_1;
        else 
            tile_in_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_218_p3 <= (trunc_ln44_fu_214_p1 & ap_const_lv5_0);
    trunc_ln44_fu_214_p1 <= select_ln34_1_fu_206_p3(5 - 1 downto 0);
    tx_cast_fu_137_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tx),32));
    ty_cast_fu_141_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ty),32));
    zext_ln34_fu_226_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln34_1_fu_206_p3),32));
    zext_ln35_fu_245_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln34_fu_198_p3),32));
    zext_ln44_1_fu_274_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln44_reg_343),64));
    zext_ln44_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln34_fu_198_p3),10));
end behav;
