-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cnn_accel_conv_layer_1_Pipeline_VITIS_LOOP_60_6_VITIS_LOOP_61_7_VITIS_LOOP_62_8_w_1_conMgi is 
    generic(
             DataWidth     : integer := 6; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cnn_accel_conv_layer_1_Pipeline_VITIS_LOOP_60_6_VITIS_LOOP_61_7_VITIS_LOOP_62_8_w_1_conMgi is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "000000", 1 => "000000", 2 => "000000", 3 => "000000", 
    4 => "000101", 5 => "000011", 6 => "001001", 7 => "111101", 
    8 => "000000", 9 => "000000", 10 => "001001", 11 => "010001", 
    12 => "111111", 13 => "000001", 14 => "010000", 15 => "000000", 
    16 => "110010", 17 => "000100", 18 => "000000", 19 => "000101", 
    20 => "000100", 21 => "000011", 22 => "000100", 23 => "110111", 
    24 => "111101", 25 => "001110", 26 => "001001", 27 => "111100", 
    28 => "000000", 29 => "000000", 30 => "000100", 31 => "000011", 
    32 => "000000", 33 => "000000", 34 => "111001", 35 => "010010", 
    36 => "000101", 37 => "000100", 38 => "000111", 39 => "101110", 
    40 => "110101", 41 => "000110", 42 => "000011", 43 => "110100", 
    44 => "000000", 45 => "000000", 46 => "110100", 47 => "000011", 
    48 => "110010", 49 => "001101", 50 => "000000", 51 => "000000", 
    52 => "000000", 53 => "000000", 54 => "000000", 55 => "000000", 
    56 => "000010", 57 => "000101", 58 => "111111", 59 => "111110", 
    60 => "000000", 61 => "000000", 62 => "000011", 63 => "111101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;

end if;
end process;

end rtl;

