set_property BITSTREAM.GENERAL.COMPRESS TRUE          [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pulldown      [current_design]
set_property CFGBVS GND                               [current_design]
set_property CONFIG_VOLTAGE 1.8                       [current_design]

set_property SEVERITY {Warning} [get_drc_checks NSTD-1]

#set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets sys_clk_p_IBUF]
set_property -quiet PACKAGE_PIN BC28 [get_ports {sys_clk_n}]
set_property IOSTANDARD DIFF_SSTL12 [get_ports sys_clk_n]

set_property -quiet PACKAGE_PIN BC27 [get_ports {sys_clk_p}]
set_property IOSTANDARD DIFF_SSTL12 [get_ports sys_clk_p]


create_clock -add -name sys_clk_p_pin -period 5.00 -waveform {0 2.5} [get_ports {sys_clk_p}];

set_property DCI_CASCADE {41 43} [get_iobanks 42]

set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets sys_clk_p]

## pins which are connected to motherboard connector TB3 
## and connector BA1 on x-board EB-PDS-DEBUG-R1 
#set_property -quiet PACKAGE_PIN N48 [get_ports {eb_tb3_1_CLK_IO_N_0}]
#set_property -quiet PACKAGE_PIN M46 [get_ports {eb_tb3_1_CLK_IO_N_1}]
#set_property -quiet PACKAGE_PIN T47 [get_ports {eb_tb3_1_CLK_IO_N_2}]
#set_property -quiet PACKAGE_PIN N47 [get_ports {eb_tb3_1_CLK_IO_P_0}]
#set_property -quiet PACKAGE_PIN N46 [get_ports {eb_tb3_1_CLK_IO_P_1}]
#set_property -quiet PACKAGE_PIN U47 [get_ports {eb_tb3_1_CLK_IO_P_2}]

#IO0
set_property -quiet PACKAGE_PIN V54 [get_ports {pin_trst}]
set_property IOSTANDARD LVCMOS18 [get_ports pin_trst]
set_property PULLDOWN true [get_ports pin_trst]
#IO1
set_property -quiet PACKAGE_PIN V53 [get_ports {pin_tdi}]
set_property IOSTANDARD LVCMOS18 [get_ports pin_tdi]
#IO2
set_property -quiet PACKAGE_PIN T53 [get_ports {pin_tms}]
set_property IOSTANDARD LVCMOS18 [get_ports pin_tms]
set_property PULLUP true [get_ports pin_tms]
#IO3
set_property -quiet PACKAGE_PIN T52 [get_ports {pin_tck}]
set_property IOSTANDARD LVCMOS18 [get_ports pin_tck]
create_clock -add -name tck_pin -period 100.00 -waveform {0 50} [get_ports {pin_tck}];
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets pin_tck_IBUF_inst/O]
#IO4
set_property -quiet PACKAGE_PIN U52 [get_ports {pin_tdo}]
set_property IOSTANDARD LVCMOS18 [get_ports pin_tdo]


set_property -quiet PACKAGE_PIN V52 [get_ports {clk_out}]

set_property -quiet PACKAGE_PIN R52 [get_ports {i2c0_sda}]
set_property IOSTANDARD LVCMOS18 [get_ports i2c0_sda]
set_property -quiet PACKAGE_PIN R51 [get_ports {i2c0_scl}]
set_property IOSTANDARD LVCMOS18 [get_ports i2c0_scl]
set_property -quiet PACKAGE_PIN W54 [get_ports {i2c1_sda}]
set_property IOSTANDARD LVCMOS18 [get_ports i2c1_sda]
set_property -quiet PACKAGE_PIN W53 [get_ports {i2c1_scl}]
set_property IOSTANDARD LVCMOS18 [get_ports i2c1_scl]
set_property -quiet PACKAGE_PIN T54 [get_ports {spi0_nss}]
set_property IOSTANDARD LVCMOS18 [get_ports spi0_nss]
set_property -quiet PACKAGE_PIN U54 [get_ports {spi0_sclk}]
set_property IOSTANDARD LVCMOS18 [get_ports spi0_sclk]
set_property -quiet PACKAGE_PIN U42 [get_ports {spi0_mosi}]
set_property IOSTANDARD LVCMOS18 [get_ports spi0_mosi]
set_property -quiet PACKAGE_PIN V42 [get_ports {spi0_miso}]
set_property IOSTANDARD LVCMOS18 [get_ports spi0_miso]
set_property -quiet PACKAGE_PIN T43 [get_ports {io7_cell}]
set_property IOSTANDARD LVCMOS18 [get_ports io7_cell]
set_property -quiet PACKAGE_PIN T42 [get_ports {io8_cell}]
set_property IOSTANDARD LVCMOS18 [get_ports io8_cell]
set_property -quiet PACKAGE_PIN R41 [get_ports {io9_cell}]
set_property IOSTANDARD LVCMOS18 [get_ports io9_cell]
set_property -quiet PACKAGE_PIN R40 [get_ports {io10_cell}]
set_property IOSTANDARD LVCMOS18 [get_ports io10_cell]
set_property -quiet PACKAGE_PIN T40 [get_ports {io12_cell}]
set_property IOSTANDARD LVCMOS18 [get_ports io12_cell]
set_property -quiet PACKAGE_PIN U40 [get_ports {io13_cell}]
set_property IOSTANDARD LVCMOS18 [get_ports io13_cell]
set_property -quiet PACKAGE_PIN V44 [get_ports {io16_cell}]
set_property IOSTANDARD LVCMOS18 [get_ports io16_cell]
set_property -quiet PACKAGE_PIN V43 [get_ports {io17_cell}]
set_property IOSTANDARD LVCMOS18 [get_ports io17_cell]
set_property -quiet PACKAGE_PIN R43 [get_ports {io18_cell}]
set_property IOSTANDARD LVCMOS18 [get_ports io18_cell]
set_property -quiet PACKAGE_PIN R42 [get_ports {io19_cell}]
set_property IOSTANDARD LVCMOS18 [get_ports io19_cell]
set_property -quiet PACKAGE_PIN A50 [get_ports {io20_cell}]
set_property IOSTANDARD LVCMOS18 [get_ports io20_cell]

set_property -quiet PACKAGE_PIN B50 [get_ports {gpio_4}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_4]
set_property PULLDOWN true [get_ports { gpio_4 }]; 
set_property -quiet PACKAGE_PIN C53 [get_ports {gpio_7}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_7]
set_property PULLDOWN true [get_ports { gpio_7 }]; 
set_property -quiet PACKAGE_PIN C52 [get_ports {gpio_8}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_8]
set_property PULLDOWN true [get_ports { gpio_8 }]; 
set_property -quiet PACKAGE_PIN D54 [get_ports {gpio_14}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_14]
set_property PULLDOWN true [get_ports { gpio_14 }]; 
set_property -quiet PACKAGE_PIN D53 [get_ports {gpio_15}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_15]
set_property PULLDOWN true [get_ports { gpio_15 }]; 
set_property -quiet PACKAGE_PIN C49 [get_ports {gpio_16}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_16]
set_property PULLDOWN true [get_ports { gpio_16 }]; 
set_property -quiet PACKAGE_PIN D49 [get_ports {gpio_17}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_17]
set_property PULLDOWN true [get_ports { gpio_17 }]; 
set_property -quiet PACKAGE_PIN D51 [get_ports {gpio_18}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_18]
set_property PULLDOWN true [get_ports { gpio_18 }]; 
set_property -quiet PACKAGE_PIN D50 [get_ports {gpio_19}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_19]
set_property PULLDOWN true [get_ports { gpio_19 }]; 
set_property -quiet PACKAGE_PIN B52 [get_ports {gpio_20}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_20]
set_property PULLDOWN true [get_ports { gpio_20 }]; 
set_property -quiet PACKAGE_PIN B51 [get_ports {gpio_21}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_21]
set_property PULLDOWN true [get_ports { gpio_21 }]; 
set_property -quiet PACKAGE_PIN J49 [get_ports {gpio_22}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_22]
set_property PULLDOWN true [get_ports { gpio_22 }]; 
set_property -quiet PACKAGE_PIN J46 [get_ports {gpio_23}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_23]
set_property PULLDOWN true [get_ports { gpio_23 }]; 
set_property -quiet PACKAGE_PIN J45 [get_ports {gpio_24}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_24]
set_property PULLDOWN true [get_ports { gpio_24 }]; 
set_property -quiet PACKAGE_PIN H49 [get_ports {gpio_25}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_25]
set_property PULLDOWN true [get_ports { gpio_25 }]; 
set_property -quiet PACKAGE_PIN H48 [get_ports {gpio_26}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_26]
set_property PULLDOWN true [get_ports { gpio_26 }]; 
set_property -quiet PACKAGE_PIN G47 [get_ports {gpio_27}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_27]
set_property PULLDOWN true [get_ports { gpio_27 }]; 
set_property -quiet PACKAGE_PIN H47 [get_ports {gpio_28}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_28]
set_property PULLDOWN true [get_ports { gpio_28 }]; 
set_property -quiet PACKAGE_PIN F48 [get_ports {gpio_29}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_29]
set_property PULLDOWN true [get_ports { gpio_29 }]; 
set_property -quiet PACKAGE_PIN F47 [get_ports {gpio_30}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_30]
set_property PULLDOWN true [get_ports { gpio_30 }]; 
set_property -quiet PACKAGE_PIN G46 [get_ports {gpio_31}]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_31]
set_property PULLDOWN true [get_ports { gpio_31 }]; 

#set_property -quiet PACKAGE_PIN H46 [get_ports {eb_tb3_1_IO_047}]
#set_property -quiet PACKAGE_PIN F49 [get_ports {eb_tb3_1_IO_048}]
#set_property -quiet PACKAGE_PIN G49 [get_ports {eb_tb3_1_IO_049}]
#set_property -quiet PACKAGE_PIN G51 [get_ports {eb_tb3_1_IO_050}]
#set_property -quiet PACKAGE_PIN G50 [get_ports {eb_tb3_1_IO_051}]
#set_property -quiet PACKAGE_PIN E50 [get_ports {eb_tb3_1_IO_052}]
#set_property -quiet PACKAGE_PIN F50 [get_ports {eb_tb3_1_IO_053}]
#set_property -quiet PACKAGE_PIN F54 [get_ports {eb_tb3_1_IO_054}]
#set_property -quiet PACKAGE_PIN F53 [get_ports {eb_tb3_1_IO_055}]
#set_property -quiet PACKAGE_PIN E52 [get_ports {eb_tb3_1_IO_056}]
#set_property -quiet PACKAGE_PIN E51 [get_ports {eb_tb3_1_IO_057}]
#set_property -quiet PACKAGE_PIN F52 [get_ports {eb_tb3_1_IO_058}]
#set_property -quiet PACKAGE_PIN G52 [get_ports {eb_tb3_1_IO_059}]
#set_property -quiet PACKAGE_PIN G54 [get_ports {eb_tb3_1_IO_060}]
#set_property -quiet PACKAGE_PIN H54 [get_ports {eb_tb3_1_IO_061}]
#set_property -quiet PACKAGE_PIN J51 [get_ports {eb_tb3_1_IO_062}]
#set_property -quiet PACKAGE_PIN J50 [get_ports {eb_tb3_1_IO_063}]
#set_property -quiet PACKAGE_PIN K51 [get_ports {eb_tb3_1_IO_064}]
#set_property -quiet PACKAGE_PIN K50 [get_ports {eb_tb3_1_IO_065}]
#set_property -quiet PACKAGE_PIN H53 [get_ports {eb_tb3_1_IO_066}]
#set_property -quiet PACKAGE_PIN J53 [get_ports {eb_tb3_1_IO_067}]
#set_property -quiet PACKAGE_PIN K53 [get_ports {eb_tb3_1_IO_068}]
#set_property -quiet PACKAGE_PIN K52 [get_ports {eb_tb3_1_IO_069}]
#set_property -quiet PACKAGE_PIN H52 [get_ports {eb_tb3_1_IO_070}]
#set_property -quiet PACKAGE_PIN H51 [get_ports {eb_tb3_1_IO_071}]
#set_property -quiet PACKAGE_PIN U45 [get_ports {eb_tb3_1_IO_072}]
#set_property -quiet PACKAGE_PIN U44 [get_ports {eb_tb3_1_IO_073}]
#set_property -quiet PACKAGE_PIN U46 [get_ports {eb_tb3_1_IO_074}]
#set_property -quiet PACKAGE_PIN V46 [get_ports {eb_tb3_1_IO_075}]
#set_property -quiet PACKAGE_PIN P46 [get_ports {eb_tb3_1_IO_076}]
#set_property -quiet PACKAGE_PIN P45 [get_ports {eb_tb3_1_IO_077}]
#set_property -quiet PACKAGE_PIN R46 [get_ports {eb_tb3_1_IO_078}]
#set_property -quiet PACKAGE_PIN R45 [get_ports {eb_tb3_1_IO_079}]
#set_property -quiet PACKAGE_PIN L44 [get_ports {eb_tb3_1_IO_080}]
#set_property -quiet PACKAGE_PIN M44 [get_ports {eb_tb3_1_IO_081}]
#set_property -quiet PACKAGE_PIN T45 [get_ports {eb_tb3_1_IO_082}]
#set_property -quiet PACKAGE_PIN T44 [get_ports {eb_tb3_1_IO_083}]
#set_property -quiet PACKAGE_PIN W50 [get_ports {eb_tb3_1_IO_084}]
#set_property -quiet PACKAGE_PIN W49 [get_ports {eb_tb3_1_IO_085}]
#set_property -quiet PACKAGE_PIN T50 [get_ports {eb_tb3_1_IO_086}]
#set_property -quiet PACKAGE_PIN U50 [get_ports {eb_tb3_1_IO_087}]
#set_property -quiet PACKAGE_PIN L45 [get_ports {eb_tb3_1_IO_088}]
#set_property -quiet PACKAGE_PIN M45 [get_ports {eb_tb3_1_IO_089}]
#set_property -quiet PACKAGE_PIN V51 [get_ports {eb_tb3_1_IO_090}]
#set_property -quiet PACKAGE_PIN W51 [get_ports {eb_tb3_1_IO_091}]
#set_property -quiet PACKAGE_PIN K46 [get_ports {eb_tb3_1_IO_092}]
#set_property -quiet PACKAGE_PIN K45 [get_ports {eb_tb3_1_IO_093}]
#set_property -quiet PACKAGE_PIN V48 [get_ports {eb_tb3_1_IO_094}]
#set_property -quiet PACKAGE_PIN W48 [get_ports {eb_tb3_1_IO_095}]
#set_property -quiet PACKAGE_PIN L40 [get_ports {eb_tb3_1_IO_096}]
#set_property -quiet PACKAGE_PIN M40 [get_ports {eb_tb3_1_IO_097}]
#set_property -quiet PACKAGE_PIN N41 [get_ports {eb_tb3_1_IO_098}]
#set_property -quiet PACKAGE_PIN P41 [get_ports {eb_tb3_1_IO_099}]
#set_property -quiet PACKAGE_PIN M42 [get_ports {eb_tb3_1_IO_100}]
#set_property -quiet PACKAGE_PIN N42 [get_ports {eb_tb3_1_IO_101}]
#set_property -quiet PACKAGE_PIN N43 [get_ports {eb_tb3_1_IO_102}]
#set_property -quiet PACKAGE_PIN P43 [get_ports {eb_tb3_1_IO_103}]
#set_property -quiet PACKAGE_PIN N44 [get_ports {eb_tb3_1_IO_104}]
#set_property -quiet PACKAGE_PIN P44 [get_ports {eb_tb3_1_IO_105}]
#set_property -quiet PACKAGE_PIN L43 [get_ports {eb_tb3_1_IO_106}]
#set_property -quiet PACKAGE_PIN L42 [get_ports {eb_tb3_1_IO_107}]
#set_property -quiet PACKAGE_PIN L49 [get_ports {eb_tb3_1_IO_108}]
#set_property -quiet PACKAGE_PIN M49 [get_ports {eb_tb3_1_IO_109}]
#set_property -quiet PACKAGE_PIN N49 [get_ports {eb_tb3_1_IO_110}]
#set_property -quiet PACKAGE_PIN P49 [get_ports {eb_tb3_1_IO_111}]
#set_property -quiet PACKAGE_PIN L50 [get_ports {eb_tb3_1_IO_112}]
#set_property -quiet PACKAGE_PIN M50 [get_ports {eb_tb3_1_IO_113}]
#set_property -quiet PACKAGE_PIN P51 [get_ports {eb_tb3_1_IO_114}]
#set_property -quiet PACKAGE_PIN P50 [get_ports {eb_tb3_1_IO_115}]
#set_property -quiet PACKAGE_PIN L54 [get_ports {eb_tb3_1_IO_116}]
#set_property -quiet PACKAGE_PIN M54 [get_ports {eb_tb3_1_IO_117}]
#set_property -quiet PACKAGE_PIN L53 [get_ports {eb_tb3_1_IO_118}]
#set_property -quiet PACKAGE_PIN L52 [get_ports {eb_tb3_1_IO_119}]
#set_property -quiet PACKAGE_PIN M52 [get_ports {eb_tb3_1_IO_120}]
#set_property -quiet PACKAGE_PIN M51 [get_ports {eb_tb3_1_IO_121}]
#set_property -quiet PACKAGE_PIN P54 [get_ports {eb_tb3_1_IO_122}]
#set_property -quiet PACKAGE_PIN P53 [get_ports {eb_tb3_1_IO_123}]
#set_property -quiet PACKAGE_PIN N54 [get_ports {eb_tb3_1_IO_124}]
#set_property -quiet PACKAGE_PIN N53 [get_ports {eb_tb3_1_IO_125}]
#set_property -quiet PACKAGE_PIN N52 [get_ports {eb_tb3_1_IO_126}]
#set_property -quiet PACKAGE_PIN N51 [get_ports {eb_tb3_1_IO_127}]
#set_property -quiet PACKAGE_PIN P48 [get_ports {eb_tb3_1_IO_128}]
#set_property -quiet PACKAGE_PIN K47 [get_ports {eb_tb3_1_IO_129}]
#set_property -quiet PACKAGE_PIN M41 [get_ports {eb_tb3_1_IO_130}]
#set_property -quiet PACKAGE_PIN R50 [get_ports {eb_tb3_1_IO_131}]
#set_property -quiet PACKAGE_PIN V47 [get_ports {eb_tb3_1_IO_132}]
#set_property -quiet PACKAGE_PIN U41 [get_ports {eb_tb3_1_IO_133}]

#set_property -quiet PACKAGE_PIN J48 [get_ports {eb_tb3_1_JTAG_P1V8_NSRST}]
#set_property -quiet PACKAGE_PIN V49 [get_ports {eb_tb3_1_JTAG_P1V8_NTRST}]
#set_property -quiet PACKAGE_PIN R47 [get_ports {eb_tb3_1_JTAG_P1V8_RTCK}]
#set_property -quiet PACKAGE_PIN M47 [get_ports {eb_tb3_1_JTAG_P1V8_TCK}]
#set_property -quiet PACKAGE_PIN L47 [get_ports {eb_tb3_1_JTAG_P1V8_TDI}]
#set_property -quiet PACKAGE_PIN U49 [get_ports {eb_tb3_1_JTAG_P1V8_TDO}]
#set_property -quiet PACKAGE_PIN R48 [get_ports {eb_tb3_1_JTAG_P1V8_TMS}]
#UART
#set_property -quiet PACKAGE_PIN L48 [get_ports {eb_tb3_1_UART_CTSN_FPGA2HOST}]
#set_property -quiet PACKAGE_PIN K48 [get_ports {eb_tb3_1_UART_RTSN_HOST2FPGA}]
set_property -quiet PACKAGE_PIN T48 [get_ports {uart0_SOUT}]
set_property IOSTANDARD LVCMOS18 [get_ports uart0_SOUT]

set_property -quiet PACKAGE_PIN T49 [get_ports {uart0_SIN}]
set_property IOSTANDARD LVCMOS18 [get_ports uart0_SIN]


# pins which are connected to motherboard connector TA3 
# and connector BA1 on x-board EB-PDS-DDR4-R3 
set_property -quiet PACKAGE_PIN BC52 [get_ports {sys_rst}]
set_property IOSTANDARD LVCMOS12 [get_ports sys_rst]
#set_property -quiet PACKAGE_PIN AN48 [get_ports {eb_ta3_1_BUTTON2}]
#set_property -quiet PACKAGE_PIN AN49 [get_ports {eb_ta3_1_BUTTON3}]
set_property -quiet PACKAGE_PIN AT48 [get_ports {c0_sys_clk_n}]
set_property -quiet PACKAGE_PIN AR48 [get_ports {c0_sys_clk_p}]
set_property -quiet PACKAGE_PIN AU52 [get_ports {c0_ddr4_adr[0]}]
set_property -quiet PACKAGE_PIN AV52 [get_ports {c0_ddr4_adr[1]}]
set_property -quiet PACKAGE_PIN AV53 [get_ports {c0_ddr4_adr[2]}]
set_property -quiet PACKAGE_PIN AV54 [get_ports {c0_ddr4_adr[3]}]
set_property -quiet PACKAGE_PIN AR53 [get_ports {c0_ddr4_adr[4]}]
set_property -quiet PACKAGE_PIN AT53 [get_ports {c0_ddr4_adr[5]}]
set_property -quiet PACKAGE_PIN AP53 [get_ports {c0_ddr4_adr[6]}]
set_property -quiet PACKAGE_PIN AP54 [get_ports {c0_ddr4_adr[7]}]
set_property -quiet PACKAGE_PIN AR52 [get_ports {c0_ddr4_adr[8]}]
set_property -quiet PACKAGE_PIN AT52 [get_ports {c0_ddr4_adr[9]}]
set_property -quiet PACKAGE_PIN AP49 [get_ports {c0_ddr4_adr[10]}]
set_property -quiet PACKAGE_PIN AP50 [get_ports {c0_ddr4_adr[11]}]
set_property -quiet PACKAGE_PIN AT50 [get_ports {c0_ddr4_adr[12]}]
set_property -quiet PACKAGE_PIN AU50 [get_ports {c0_ddr4_adr[13]}]
set_property -quiet PACKAGE_PIN AR50 [get_ports {c0_ddr4_adr[14]}]
set_property -quiet PACKAGE_PIN AR51 [get_ports {c0_ddr4_adr[15]}]
set_property -quiet PACKAGE_PIN AU51 [get_ports {c0_ddr4_adr[16]}]
set_property -quiet PACKAGE_PIN AU42 [get_ports {c0_ddr4_act_n}]
#set_property -quiet PACKAGE_PIN BC49 [get_ports {eb_ta3_1_DDR4_ALERT_N}]
set_property -quiet PACKAGE_PIN AV51 [get_ports {c0_ddr4_ba[0]}]
set_property -quiet PACKAGE_PIN AT49 [get_ports {c0_ddr4_ba[1]}]
set_property -quiet PACKAGE_PIN AU49 [get_ports {c0_ddr4_bg[0]}]
set_property -quiet PACKAGE_PIN AU54 [get_ports {c0_ddr4_ck_c[0]}]
set_property -quiet PACKAGE_PIN AT54 [get_ports {c0_ddr4_ck_t[0]}]
set_property -quiet PACKAGE_PIN AV49 [get_ports {c0_ddr4_cke[0]}]
set_property -quiet PACKAGE_PIN AP48 [get_ports {c0_ddr4_cs_n[0]}]
set_property -quiet PACKAGE_PIN AY45 [get_ports {c0_ddr4_dq[0]}]
set_property -quiet PACKAGE_PIN AY46 [get_ports {c0_ddr4_dq[1]}]
set_property -quiet PACKAGE_PIN AV46 [get_ports {c0_ddr4_dq[2]}]
set_property -quiet PACKAGE_PIN AW46 [get_ports {c0_ddr4_dq[3]}]
set_property -quiet PACKAGE_PIN AV44 [get_ports {c0_ddr4_dq[4]}]
set_property -quiet PACKAGE_PIN AW45 [get_ports {c0_ddr4_dq[5]}]
set_property -quiet PACKAGE_PIN AW43 [get_ports {c0_ddr4_dq[6]}]
set_property -quiet PACKAGE_PIN AW44 [get_ports {c0_ddr4_dq[7]}]
set_property -quiet PACKAGE_PIN AY43 [get_ports {c0_ddr4_dm_dbi_n[0]}]
set_property -quiet PACKAGE_PIN AV43 [get_ports {c0_ddr4_dqs_c[0]}]
set_property -quiet PACKAGE_PIN AV42 [get_ports {c0_ddr4_dqs_t[0]}]
set_property -quiet PACKAGE_PIN BA45 [get_ports {c0_ddr4_dq[8]}]
set_property -quiet PACKAGE_PIN BB45 [get_ports {c0_ddr4_dq[9]}]
set_property -quiet PACKAGE_PIN BB46 [get_ports {c0_ddr4_dq[10]}]
set_property -quiet PACKAGE_PIN BC46 [get_ports {c0_ddr4_dq[11]}]
set_property -quiet PACKAGE_PIN AY47 [get_ports {c0_ddr4_dq[12]}]
set_property -quiet PACKAGE_PIN AY48 [get_ports {c0_ddr4_dq[13]}]
set_property -quiet PACKAGE_PIN BA47 [get_ports {c0_ddr4_dq[14]}]
set_property -quiet PACKAGE_PIN BA48 [get_ports {c0_ddr4_dq[15]}]
set_property -quiet PACKAGE_PIN BB44 [get_ports {c0_ddr4_dm_dbi_n[1]}]
set_property -quiet PACKAGE_PIN BC47 [get_ports {c0_ddr4_dqs_c[1]}]
set_property -quiet PACKAGE_PIN BB47 [get_ports {c0_ddr4_dqs_t[1]}]
set_property -quiet PACKAGE_PIN AJ48 [get_ports {c0_ddr4_dq[16]}]
set_property -quiet PACKAGE_PIN AJ49 [get_ports {c0_ddr4_dq[17]}]
set_property -quiet PACKAGE_PIN AL49 [get_ports {c0_ddr4_dq[18]}]
set_property -quiet PACKAGE_PIN AM49 [get_ports {c0_ddr4_dq[19]}]
set_property -quiet PACKAGE_PIN AJ51 [get_ports {c0_ddr4_dq[20]}]
set_property -quiet PACKAGE_PIN AK51 [get_ports {c0_ddr4_dq[21]}]
set_property -quiet PACKAGE_PIN AL50 [get_ports {c0_ddr4_dq[22]}]
set_property -quiet PACKAGE_PIN AM50 [get_ports {c0_ddr4_dq[23]}]
set_property -quiet PACKAGE_PIN AM51 [get_ports {c0_ddr4_dm_dbi_n[2]}]
set_property -quiet PACKAGE_PIN AK50 [get_ports {c0_ddr4_dqs_c[2]}]
set_property -quiet PACKAGE_PIN AJ50 [get_ports {c0_ddr4_dqs_t[2]}]
set_property -quiet PACKAGE_PIN AK41 [get_ports {c0_ddr4_dq[24]}]
set_property -quiet PACKAGE_PIN AK42 [get_ports {c0_ddr4_dq[25]}]
set_property -quiet PACKAGE_PIN AL42 [get_ports {c0_ddr4_dq[26]}]
set_property -quiet PACKAGE_PIN AM42 [get_ports {c0_ddr4_dq[27]}]
set_property -quiet PACKAGE_PIN AL44 [get_ports {c0_ddr4_dq[28]}]
set_property -quiet PACKAGE_PIN AL45 [get_ports {c0_ddr4_dq[29]}]
set_property -quiet PACKAGE_PIN AJ43 [get_ports {c0_ddr4_dq[30]}]
set_property -quiet PACKAGE_PIN AJ44 [get_ports {c0_ddr4_dq[31]}]
set_property -quiet PACKAGE_PIN AM44 [get_ports {c0_ddr4_dm_dbi_n[3]}]
set_property -quiet PACKAGE_PIN AL43 [get_ports {c0_ddr4_dqs_c[3]}]
set_property -quiet PACKAGE_PIN AK43 [get_ports {c0_ddr4_dqs_t[3]}]
set_property -quiet PACKAGE_PIN AN43 [get_ports {c0_ddr4_dq[32]}]
set_property -quiet PACKAGE_PIN AN44 [get_ports {c0_ddr4_dq[33]}]
set_property -quiet PACKAGE_PIN AP43 [get_ports {c0_ddr4_dq[34]}]
set_property -quiet PACKAGE_PIN AP44 [get_ports {c0_ddr4_dq[35]}]
set_property -quiet PACKAGE_PIN AR42 [get_ports {c0_ddr4_dq[36]}]
set_property -quiet PACKAGE_PIN AR43 [get_ports {c0_ddr4_dq[37]}]
set_property -quiet PACKAGE_PIN AT42 [get_ports {c0_ddr4_dq[38]}]
set_property -quiet PACKAGE_PIN AT43 [get_ports {c0_ddr4_dq[39]}]
set_property -quiet PACKAGE_PIN AU41 [get_ports {c0_ddr4_dm_dbi_n[4]}]
set_property -quiet PACKAGE_PIN AR41 [get_ports {c0_ddr4_dqs_c[4]}]
set_property -quiet PACKAGE_PIN AP41 [get_ports {c0_ddr4_dqs_t[4]}]
set_property -quiet PACKAGE_PIN AR47 [get_ports {c0_ddr4_dq[40]}]
set_property -quiet PACKAGE_PIN AT47 [get_ports {c0_ddr4_dq[41]}]
set_property -quiet PACKAGE_PIN AT44 [get_ports {c0_ddr4_dq[42]}]
set_property -quiet PACKAGE_PIN AT45 [get_ports {c0_ddr4_dq[43]}]
set_property -quiet PACKAGE_PIN AU44 [get_ports {c0_ddr4_dq[44]}]
set_property -quiet PACKAGE_PIN AU45 [get_ports {c0_ddr4_dq[45]}]
set_property -quiet PACKAGE_PIN AP45 [get_ports {c0_ddr4_dq[46]}]
set_property -quiet PACKAGE_PIN AP46 [get_ports {c0_ddr4_dq[47]}]
set_property -quiet PACKAGE_PIN AU46 [get_ports {c0_ddr4_dm_dbi_n[5]}]
set_property -quiet PACKAGE_PIN AR46 [get_ports {c0_ddr4_dqs_c[5]}]
set_property -quiet PACKAGE_PIN AR45 [get_ports {c0_ddr4_dqs_t[5]}]
set_property -quiet PACKAGE_PIN BB51 [get_ports {c0_ddr4_dq[48]}]
set_property -quiet PACKAGE_PIN BB52 [get_ports {c0_ddr4_dq[49]}]
set_property -quiet PACKAGE_PIN BA54 [get_ports {c0_ddr4_dq[50]}]
set_property -quiet PACKAGE_PIN BB54 [get_ports {c0_ddr4_dq[51]}]
set_property -quiet PACKAGE_PIN AY52 [get_ports {c0_ddr4_dq[52]}]
set_property -quiet PACKAGE_PIN AY53 [get_ports {c0_ddr4_dq[53]}]
set_property -quiet PACKAGE_PIN AW53 [get_ports {c0_ddr4_dq[54]}]
set_property -quiet PACKAGE_PIN AW54 [get_ports {c0_ddr4_dq[55]}]
set_property -quiet PACKAGE_PIN BC51 [get_ports {c0_ddr4_dm_dbi_n[6]}]
set_property -quiet PACKAGE_PIN BA53 [get_ports {c0_ddr4_dqs_c[6]}]
set_property -quiet PACKAGE_PIN BA52 [get_ports {c0_ddr4_dqs_t[6]}]
set_property -quiet PACKAGE_PIN AV47 [get_ports {c0_ddr4_dq[56]}]
set_property -quiet PACKAGE_PIN AV48 [get_ports {c0_ddr4_dq[57]}]
set_property -quiet PACKAGE_PIN AW48 [get_ports {c0_ddr4_dq[58]}]
set_property -quiet PACKAGE_PIN AW49 [get_ports {c0_ddr4_dq[59]}]
set_property -quiet PACKAGE_PIN BA49 [get_ports {c0_ddr4_dq[60]}]
set_property -quiet PACKAGE_PIN BA50 [get_ports {c0_ddr4_dq[61]}]
set_property -quiet PACKAGE_PIN AY50 [get_ports {c0_ddr4_dq[62]}]
set_property -quiet PACKAGE_PIN AY51 [get_ports {c0_ddr4_dq[63]}]
set_property -quiet PACKAGE_PIN BB49 [get_ports {c0_ddr4_dm_dbi_n[7]}]
set_property -quiet PACKAGE_PIN AW51 [get_ports {c0_ddr4_dqs_c[7]}]
set_property -quiet PACKAGE_PIN AW50 [get_ports {c0_ddr4_dqs_t[7]}]
#set_property -quiet PACKAGE_PIN AK47 [get_ports {eb_ta3_1_DDR4_DQ08_D0_DX64}]
#set_property -quiet PACKAGE_PIN AK48 [get_ports {eb_ta3_1_DDR4_DQ08_D1_DX65}]
#set_property -quiet PACKAGE_PIN AJ45 [get_ports {eb_ta3_1_DDR4_DQ08_D2_DX66}]
#set_property -quiet PACKAGE_PIN AJ46 [get_ports {eb_ta3_1_DDR4_DQ08_D3_DX67}]
#set_property -quiet PACKAGE_PIN AM46 [get_ports {eb_ta3_1_DDR4_DQ08_D4_DX68}]
#set_property -quiet PACKAGE_PIN AM47 [get_ports {eb_ta3_1_DDR4_DQ08_D5_DX69}]
#set_property -quiet PACKAGE_PIN AN46 [get_ports {eb_ta3_1_DDR4_DQ08_D6_DX70}]
#set_property -quiet PACKAGE_PIN AN47 [get_ports {eb_ta3_1_DDR4_DQ08_D7_DX71}]
#set_property -quiet PACKAGE_PIN AL47 [get_ports {eb_ta3_1_DDR4_DQ08_DM_DBI_N}]
#set_property -quiet PACKAGE_PIN AK46 [get_ports {eb_ta3_1_DDR4_DQ08_DQS_C}]
#set_property -quiet PACKAGE_PIN AK45 [get_ports {eb_ta3_1_DDR4_DQ08_DQS_T}]
#set_property -quiet PACKAGE_PIN AL53 [get_ports {eb_ta3_1_DDR4_DQ09_D0_DX72}]
#set_property -quiet PACKAGE_PIN AL54 [get_ports {eb_ta3_1_DDR4_DQ09_D1_DX73}]
#set_property -quiet PACKAGE_PIN AJ53 [get_ports {eb_ta3_1_DDR4_DQ09_D2_DX74}]
#set_property -quiet PACKAGE_PIN AK53 [get_ports {eb_ta3_1_DDR4_DQ09_D3_DX75}]
#set_property -quiet PACKAGE_PIN AM54 [get_ports {eb_ta3_1_DDR4_DQ09_D4_DX76}]
#set_property -quiet PACKAGE_PIN AN54 [get_ports {eb_ta3_1_DDR4_DQ09_D5_DX77}]
#set_property -quiet PACKAGE_PIN AK52 [get_ports {eb_ta3_1_DDR4_DQ09_D6_DX78}]
#set_property -quiet PACKAGE_PIN AL52 [get_ports {eb_ta3_1_DDR4_DQ09_D7_DX79}]
#set_property -quiet PACKAGE_PIN AN52 [get_ports {eb_ta3_1_DDR4_DQ09_DM_DBI_N}]
#set_property -quiet PACKAGE_PIN AJ54 [get_ports {eb_ta3_1_DDR4_DQ09_DQS_C}]
#set_property -quiet PACKAGE_PIN AH54 [get_ports {eb_ta3_1_DDR4_DQ09_DQS_T}]
set_property -quiet PACKAGE_PIN AN42 [get_ports {c0_ddr4_odt[0]}]
#set_property -quiet PACKAGE_PIN BC44 [get_ports {eb_ta3_1_DDR4_PAR}]
set_property -quiet PACKAGE_PIN AW41 [get_ports {c0_ddr4_reset_n}]
#set_property -quiet PACKAGE_PIN BC48 [get_ports {eb_ta3_1_DDR4_TEN}]
#set_property -quiet PACKAGE_PIN BB50 [get_ports {eb_ta3_1_LED_BLUE1}]
#set_property -quiet PACKAGE_PIN AM45 [get_ports {eb_ta3_1_LED_BLUE2}]
#set_property -quiet PACKAGE_PIN AU47 [get_ports {eb_ta3_1_LED_GREEN1}]
#set_property -quiet PACKAGE_PIN BA44 [get_ports {eb_ta3_1_LED_GREEN2}]
#set_property -quiet PACKAGE_PIN AL48 [get_ports {eb_ta3_1_LED_RED1}]
#set_property -quiet PACKAGE_PIN AN51 [get_ports {eb_ta3_1_LED_RED2}]
#set_property -quiet PACKAGE_PIN AM41 [get_ports {eb_ta3_1_LED_YELLOW1}]
#set_property -quiet PACKAGE_PIN AN53 [get_ports {eb_ta3_1_LED_YELLOW2}]

## pins which are connected to motherboard connector TA4 
## and connector BA1 on x-board EB-PDS-GBITETHERNET-R1 
set_property -quiet PACKAGE_PIN BA24 [get_ports {phy_ref_clk}]
set_property IOSTANDARD LVCMOS18 [get_ports phy_ref_clk]
set_property -quiet PACKAGE_PIN BH21 [get_ports {phy_col}] 
set_property -quiet PACKAGE_PIN BJ21 [get_ports {phy_crs}]
set_property IOSTANDARD LVCMOS18 [get_ports phy_crs]

#set_property -quiet PACKAGE_PIN BJ24 [get_ports {eb_ta4_1_ETH1_GTX_CLK_TCK}]
set_property -quiet PACKAGE_PIN AV22 [get_ports {phy_mdc}]
set_property IOSTANDARD LVCMOS18 [get_ports phy_mdc]
set_property -quiet PACKAGE_PIN AU22 [get_ports {phy_mdio}]
set_property IOSTANDARD LVCMOS18 [get_ports phy_mdio]
#set_property -quiet PACKAGE_PIN BD19 [get_ports {eb_ta4_1_ETH1_NINTERRUPT}]
set_property -quiet PACKAGE_PIN BB19 [get_ports {phy_rst_n}]
set_property IOSTANDARD LVCMOS18 [get_ports phy_rst_n]
set_property -quiet PACKAGE_PIN BD18 [get_ports {phy_rx_clk}]
set_property IOSTANDARD LVCMOS18 [get_ports phy_rx_clk]
set_property -quiet PACKAGE_PIN BD20 [get_ports {phy_dv}]
set_property IOSTANDARD LVCMOS18 [get_ports phy_dv]
set_property -quiet PACKAGE_PIN BJ25 [get_ports {phy_rx_er}]
set_property IOSTANDARD LVCMOS18 [get_ports phy_rx_er]
set_property -quiet PACKAGE_PIN BH24 [get_ports {phy_rx_data[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports phy_rx_data[0]]
set_property -quiet PACKAGE_PIN BG24 [get_ports {phy_rx_data[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports phy_rx_data[1]]
set_property -quiet PACKAGE_PIN BG25 [get_ports {phy_rx_data[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports phy_rx_data[2]]
set_property -quiet PACKAGE_PIN BF25 [get_ports {phy_rx_data[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports phy_rx_data[3]]
#set_property -quiet PACKAGE_PIN BJ23 [get_ports {eb_ta4_1_ETH1_RXD4}]
#set_property -quiet PACKAGE_PIN BH23 [get_ports {eb_ta4_1_ETH1_RXD5}]
#set_property -quiet PACKAGE_PIN BH22 [get_ports {eb_ta4_1_ETH1_RXD6}]
#set_property -quiet PACKAGE_PIN BG22 [get_ports {eb_ta4_1_ETH1_RXD7}]
set_property -quiet PACKAGE_PIN AY23 [get_ports {phy_tx_clk}]
set_property IOSTANDARD LVCMOS18 [get_ports phy_tx_clk]
set_property -quiet PACKAGE_PIN AU25 [get_ports {phy_tx_en}]
set_property IOSTANDARD LVCMOS18 [get_ports phy_tx_en]
#set_property -quiet PACKAGE_PIN AT25 [get_ports {eb_ta4_1_ETH1_TX_ER}]
set_property -quiet PACKAGE_PIN AW23 [get_ports {phy_tx_data[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports phy_tx_data[0]]
set_property -quiet PACKAGE_PIN AV23 [get_ports {phy_tx_data[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports phy_tx_data[1]]
set_property -quiet PACKAGE_PIN AW24 [get_ports {phy_tx_data[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports phy_tx_data[2]]
set_property -quiet PACKAGE_PIN AW25 [get_ports {phy_tx_data[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports phy_tx_data[3]]
#set_property -quiet PACKAGE_PIN AV24 [get_ports {eb_ta4_1_ETH1_TXD4}]
#set_property -quiet PACKAGE_PIN AU24 [get_ports {eb_ta4_1_ETH1_TXD5}]
#set_property -quiet PACKAGE_PIN AT22 [get_ports {eb_ta4_1_ETH1_TXD6}]
#set_property -quiet PACKAGE_PIN AT23 [get_ports {eb_ta4_1_ETH1_TXD7}]

set_property -quiet PACKAGE_PIN BC23 [get_ports {phy1_ref_clk}]
set_property -quiet PACKAGE_PIN BJ11 [get_ports {phy1_col}]
set_property -quiet PACKAGE_PIN BH11 [get_ports {phy1_crs}]
#set_property -quiet PACKAGE_PIN BH12 [get_ports {eb_ta4_1_ETH2_GTX_CLK_TCK}]
set_property -quiet PACKAGE_PIN BC13 [get_ports {phy1_mdc}]
set_property -quiet PACKAGE_PIN BC14 [get_ports {phy1_mdio}]
#set_property -quiet PACKAGE_PIN BA23 [get_ports {eb_ta4_1_ETH2_NINTERRUPT}]
set_property -quiet PACKAGE_PIN BD24 [get_ports {phy1_rst_n}]
set_property -quiet PACKAGE_PIN BC19 [get_ports {phy1_rx_clk}]
set_property -quiet PACKAGE_PIN BA19 [get_ports {phy1_dv}]
set_property -quiet PACKAGE_PIN BG12 [get_ports {phy1_rx_er}]
set_property -quiet PACKAGE_PIN BJ14 [get_ports {phy1_rx_data[0]}]
set_property -quiet PACKAGE_PIN BJ15 [get_ports {phy1_rx_data[1]}]
set_property -quiet PACKAGE_PIN BG15 [get_ports {phy1_rx_data[2}]
set_property -quiet PACKAGE_PIN BF15 [get_ports {phy1_rx_data[3]}]
#set_property -quiet PACKAGE_PIN BH14 [get_ports {phy_rx_data[3]}]
#set_property -quiet PACKAGE_PIN BG14 [get_ports {eb_ta4_1_ETH2_RXD5}]
#set_property -quiet PACKAGE_PIN BJ13 [get_ports {eb_ta4_1_ETH2_RXD6}]
#set_property -quiet PACKAGE_PIN BH13 [get_ports {eb_ta4_1_ETH2_RXD7}]
#set_property -quiet PACKAGE_PIN BC24 [get_ports {phy1_tx_clk}]
#set_property -quiet PACKAGE_PIN BC12 [get_ports {phy1_tx_en}]
#set_property -quiet PACKAGE_PIN BB12 [get_ports {eb_ta4_1_ETH2_TX_ER}]
#set_property -quiet PACKAGE_PIN BE15 [get_ports {phy1_tx_data[0]}]
#set_property -quiet PACKAGE_PIN BD15 [get_ports {phy1_tx_data[1]}]
#set_property -quiet PACKAGE_PIN BF12 [get_ports {phy1_tx_data[2]}]
#set_property -quiet PACKAGE_PIN BF13 [get_ports {phy1_tx_data[3]}]
#set_property -quiet PACKAGE_PIN BE12 [get_ports {eb_ta4_1_ETH2_TXD4}]
#set_property -quiet PACKAGE_PIN BE13 [get_ports {eb_ta4_1_ETH2_TXD5}]
#set_property -quiet PACKAGE_PIN BD13 [get_ports {eb_ta4_1_ETH2_TXD6}]
#set_property -quiet PACKAGE_PIN BD14 [get_ports {eb_ta4_1_ETH2_TXD7}]


# pins which are connected to motherboard connector TB4 
## and connector BA1 on x-board EB-PDS-DVI-R1 
#set_property -quiet PACKAGE_PIN L13 [get_ports {eb_tb4_1_DBG_CLK}]
#set_property -quiet PACKAGE_PIN U17 [get_ports {eb_tb4_1_DBG_DATA_A_0}]
#set_property -quiet PACKAGE_PIN G20 [get_ports {eb_tb4_1_DBG_DATA_A_1}]
#set_property -quiet PACKAGE_PIN P19 [get_ports {eb_tb4_1_DBG_DATA_A_2}]
#set_property -quiet PACKAGE_PIN M21 [get_ports {eb_tb4_1_DBG_DATA_A_3}]
#set_property -quiet PACKAGE_PIN T18 [get_ports {eb_tb4_1_DBG_DATA_A_4}]
#set_property -quiet PACKAGE_PIN V18 [get_ports {eb_tb4_1_DBG_DATA_A_5}]
#set_property -quiet PACKAGE_PIN N17 [get_ports {eb_tb4_1_DBG_DATA_A_6}]
#set_property -quiet PACKAGE_PIN N18 [get_ports {eb_tb4_1_DBG_DATA_A_7}]
#set_property -quiet PACKAGE_PIN T17 [get_ports {eb_tb4_1_DBG_DATA_A_8}]
#set_property -quiet PACKAGE_PIN V17 [get_ports {eb_tb4_1_DBG_DATA_A_9}]
#set_property -quiet PACKAGE_PIN M17 [get_ports {eb_tb4_1_DBG_DATA_B_0}]
#set_property -quiet PACKAGE_PIN N19 [get_ports {eb_tb4_1_DBG_DATA_B_1}]
#set_property -quiet PACKAGE_PIN G19 [get_ports {eb_tb4_1_DBG_DATA_B_2}]
#set_property -quiet PACKAGE_PIN N21 [get_ports {eb_tb4_1_DBG_DATA_B_3}]
#set_property -quiet PACKAGE_PIN U19 [get_ports {eb_tb4_1_DBG_DATA_B_4}]
#set_property -quiet PACKAGE_PIN R20 [get_ports {eb_tb4_1_DBG_DATA_B_5}]
#set_property -quiet PACKAGE_PIN T19 [get_ports {eb_tb4_1_DBG_DATA_B_6}]
#set_property -quiet PACKAGE_PIN U20 [get_ports {eb_tb4_1_DBG_DATA_B_7}]
#set_property -quiet PACKAGE_PIN P18 [get_ports {eb_tb4_1_DBG_DATA_B_8}]
#set_property -quiet PACKAGE_PIN T20 [get_ports {eb_tb4_1_DBG_DATA_B_9}]
#set_property -quiet PACKAGE_PIN H19 [get_ports {eb_tb4_1_DVI_IN_CTL_1}]
#set_property -quiet PACKAGE_PIN J19 [get_ports {eb_tb4_1_DVI_IN_CTL_2}]
#set_property -quiet PACKAGE_PIN M25 [get_ports {eb_tb4_1_DVI_IN_DATA_E_0}]
#set_property -quiet PACKAGE_PIN N23 [get_ports {eb_tb4_1_DVI_IN_DATA_E_1}]
#set_property -quiet PACKAGE_PIN P23 [get_ports {eb_tb4_1_DVI_IN_DATA_E_2}]
#set_property -quiet PACKAGE_PIN N22 [get_ports {eb_tb4_1_DVI_IN_DATA_E_3}]
#set_property -quiet PACKAGE_PIN N24 [get_ports {eb_tb4_1_DVI_IN_DATA_E_4}]
#set_property -quiet PACKAGE_PIN M22 [get_ports {eb_tb4_1_DVI_IN_DATA_E_5}]
#set_property -quiet PACKAGE_PIN M24 [get_ports {eb_tb4_1_DVI_IN_DATA_E_6}]
#set_property -quiet PACKAGE_PIN P21 [get_ports {eb_tb4_1_DVI_IN_DATA_E_7}]
#set_property -quiet PACKAGE_PIN R21 [get_ports {eb_tb4_1_DVI_IN_DATA_E_8}]
#set_property -quiet PACKAGE_PIN K23 [get_ports {eb_tb4_1_DVI_IN_DATA_E_9}]
#set_property -quiet PACKAGE_PIN L23 [get_ports {eb_tb4_1_DVI_IN_DATA_E_10}]
#set_property -quiet PACKAGE_PIN K22 [get_ports {eb_tb4_1_DVI_IN_DATA_E_11}]
#set_property -quiet PACKAGE_PIN L22 [get_ports {eb_tb4_1_DVI_IN_DATA_E_12}]
#set_property -quiet PACKAGE_PIN H23 [get_ports {eb_tb4_1_DVI_IN_DATA_E_13}]
#set_property -quiet PACKAGE_PIN J23 [get_ports {eb_tb4_1_DVI_IN_DATA_E_14}]
#set_property -quiet PACKAGE_PIN H26 [get_ports {eb_tb4_1_DVI_IN_DATA_E_15}]
#set_property -quiet PACKAGE_PIN J26 [get_ports {eb_tb4_1_DVI_IN_DATA_E_16}]
#set_property -quiet PACKAGE_PIN J25 [get_ports {eb_tb4_1_DVI_IN_DATA_E_17}]
#set_property -quiet PACKAGE_PIN K25 [get_ports {eb_tb4_1_DVI_IN_DATA_E_18}]
#set_property -quiet PACKAGE_PIN H24 [get_ports {eb_tb4_1_DVI_IN_DATA_E_19}]
#set_property -quiet PACKAGE_PIN J24 [get_ports {eb_tb4_1_DVI_IN_DATA_E_20}]
#set_property -quiet PACKAGE_PIN E22 [get_ports {eb_tb4_1_DVI_IN_DATA_E_21}]
#set_property -quiet PACKAGE_PIN F22 [get_ports {eb_tb4_1_DVI_IN_DATA_E_22}]
#set_property -quiet PACKAGE_PIN F24 [get_ports {eb_tb4_1_DVI_IN_DATA_E_23}]
#set_property -quiet PACKAGE_PIN G24 [get_ports {eb_tb4_1_DVI_IN_DATA_O_0}]
#set_property -quiet PACKAGE_PIN G22 [get_ports {eb_tb4_1_DVI_IN_DATA_O_1}]
#set_property -quiet PACKAGE_PIN H22 [get_ports {eb_tb4_1_DVI_IN_DATA_O_2}]
#set_property -quiet PACKAGE_PIN E25 [get_ports {eb_tb4_1_DVI_IN_DATA_O_3}]
#set_property -quiet PACKAGE_PIN E26 [get_ports {eb_tb4_1_DVI_IN_DATA_O_4}]
#set_property -quiet PACKAGE_PIN F25 [get_ports {eb_tb4_1_DVI_IN_DATA_O_5}]
#set_property -quiet PACKAGE_PIN G25 [get_ports {eb_tb4_1_DVI_IN_DATA_O_6}]
#set_property -quiet PACKAGE_PIN E23 [get_ports {eb_tb4_1_DVI_IN_DATA_O_7}]
#set_property -quiet PACKAGE_PIN F23 [get_ports {eb_tb4_1_DVI_IN_DATA_O_8}]
#set_property -quiet PACKAGE_PIN J16 [get_ports {eb_tb4_1_DVI_IN_DATA_O_9}]
#set_property -quiet PACKAGE_PIN K16 [get_ports {eb_tb4_1_DVI_IN_DATA_O_10}]
#set_property -quiet PACKAGE_PIN J15 [get_ports {eb_tb4_1_DVI_IN_DATA_O_11}]
#set_property -quiet PACKAGE_PIN K15 [get_ports {eb_tb4_1_DVI_IN_DATA_O_12}]
#set_property -quiet PACKAGE_PIN H21 [get_ports {eb_tb4_1_DVI_IN_DATA_O_13}]
#set_property -quiet PACKAGE_PIN J21 [get_ports {eb_tb4_1_DVI_IN_DATA_O_14}]
#set_property -quiet PACKAGE_PIN K12 [get_ports {eb_tb4_1_DVI_IN_DATA_O_15}]
#set_property -quiet PACKAGE_PIN L12 [get_ports {eb_tb4_1_DVI_IN_DATA_O_16}]
#set_property -quiet PACKAGE_PIN J20 [get_ports {eb_tb4_1_DVI_IN_DATA_O_17}]
#set_property -quiet PACKAGE_PIN K20 [get_ports {eb_tb4_1_DVI_IN_DATA_O_18}]
#set_property -quiet PACKAGE_PIN J13 [get_ports {eb_tb4_1_DVI_IN_DATA_O_19}]
#set_property -quiet PACKAGE_PIN J14 [get_ports {eb_tb4_1_DVI_IN_DATA_O_20}]
#set_property -quiet PACKAGE_PIN N13 [get_ports {eb_tb4_1_DVI_IN_DATA_O_21}]
#set_property -quiet PACKAGE_PIN P13 [get_ports {eb_tb4_1_DVI_IN_DATA_O_22}]
#set_property -quiet PACKAGE_PIN P14 [get_ports {eb_tb4_1_DVI_IN_DATA_O_23}]
#set_property -quiet PACKAGE_PIN J18 [get_ports {eb_tb4_1_DVI_IN_DE}]
#set_property -quiet PACKAGE_PIN M12 [get_ports {eb_tb4_1_DVI_IN_DFO}]
#set_property -quiet PACKAGE_PIN E17 [get_ports {eb_tb4_1_DVI_IN_EDID_SCL}]
#set_property -quiet PACKAGE_PIN E18 [get_ports {eb_tb4_1_DVI_IN_EDID_SDA}]
#set_property -quiet PACKAGE_PIN P15 [get_ports {eb_tb4_1_DVI_IN_HSYNC}]
#set_property -quiet PACKAGE_PIN N12 [get_ports {eb_tb4_1_DVI_IN_NPD}]
#set_property -quiet PACKAGE_PIN E20 [get_ports {eb_tb4_1_DVI_IN_NPDO}]
#set_property -quiet PACKAGE_PIN F19 [get_ports {eb_tb4_1_DVI_IN_NSTAG}]
#set_property -quiet PACKAGE_PIN N16 [get_ports {eb_tb4_1_DVI_IN_OCK_INV}]
#set_property -quiet PACKAGE_PIN M20 [get_ports {eb_tb4_1_DVI_IN_ODCK}]
#set_property -quiet PACKAGE_PIN F20 [get_ports {eb_tb4_1_DVI_IN_PIX}]
#set_property -quiet PACKAGE_PIN P16 [get_ports {eb_tb4_1_DVI_IN_SCDT}]
#set_property -quiet PACKAGE_PIN E21 [get_ports {eb_tb4_1_DVI_IN_ST}]
#set_property -quiet PACKAGE_PIN H18 [get_ports {eb_tb4_1_DVI_IN_VSYNC}]
#set_property -quiet PACKAGE_PIN U21 [get_ports {eb_tb4_1_DVI_OUT_A3_DK3}]
#set_property -quiet PACKAGE_PIN V21 [get_ports {eb_tb4_1_DVI_OUT_BSEL_SCL}]
#set_property -quiet PACKAGE_PIN T25 [get_ports {eb_tb4_1_DVI_OUT_CTL1_A1_DK1}]
#set_property -quiet PACKAGE_PIN U25 [get_ports {eb_tb4_1_DVI_OUT_CTL2_A2_DK2}]
#set_property -quiet PACKAGE_PIN H14 [get_ports {vga_out_data[0]}]
#set_property -quiet PACKAGE_PIN E15 [get_ports {vga_out_data[1]}]
#set_property -quiet PACKAGE_PIN E16 [get_ports {vga_out_data[2]}]
#set_property -quiet PACKAGE_PIN F15 [get_ports {vga_out_data[3]}]
#set_property -quiet PACKAGE_PIN T14 [get_ports {vga_out_data[4]}]
#set_property -quiet PACKAGE_PIN F14 [get_ports {vga_out_data[5]}]
#set_property -quiet PACKAGE_PIN R16 [get_ports {vga_out_data[6]}]
#set_property -quiet PACKAGE_PIN H12 [get_ports {vga_out_data[7]}]
#set_property -quiet PACKAGE_PIN H13 [get_ports {vga_out_data[8]}]
#set_property -quiet PACKAGE_PIN F13 [get_ports {vga_out_data[9]}]
#set_property -quiet PACKAGE_PIN G14 [get_ports {vga_out_data[10]}]
#set_property -quiet PACKAGE_PIN G15 [get_ports {vga_out_data[11]}]
#set_property -quiet PACKAGE_PIN T15 [get_ports {vga_out_data[12]}]
#set_property -quiet PACKAGE_PIN U15 [get_ports {vga_out_data[13]}]
#set_property -quiet PACKAGE_PIN R15 [get_ports {vga_out_data[14]}]
#set_property -quiet PACKAGE_PIN G12 [get_ports {vga_out_data[15]}]
#set_property -quiet PACKAGE_PIN R13 [get_ports {vga_out_data[16]}]
#set_property -quiet PACKAGE_PIN T13 [get_ports {vga_out_data[17]}]
#set_property -quiet PACKAGE_PIN U12 [get_ports {vga_out_data[18]}]
#set_property -quiet PACKAGE_PIN T12 [get_ports {vga_out_data[19]}]
#set_property -quiet PACKAGE_PIN V12 [get_ports {vga_out_data[20]}]
#set_property -quiet PACKAGE_PIN V13 [get_ports {vga_out_data[21]}]
#set_property -quiet PACKAGE_PIN F12 [get_ports {vga_out_data[22]}]
#set_property -quiet PACKAGE_PIN U14 [get_ports {vga_out_data[23]}]
#set_property -quiet PACKAGE_PIN T22 [get_ports {eb_tb4_1_DVI_OUT_DE}]
#set_property -quiet PACKAGE_PIN V22 [get_ports {eb_tb4_1_DVI_OUT_DKEN}]
#set_property -quiet PACKAGE_PIN P24 [get_ports {eb_tb4_1_DVI_OUT_DSEL_SDA}]
#set_property -quiet PACKAGE_PIN U22 [get_ports {eb_tb4_1_DVI_OUT_EDGE}]
#set_property -quiet PACKAGE_PIN G17 [get_ports {eb_tb4_1_DVI_OUT_EDID_SCL}]
#set_property -quiet PACKAGE_PIN H17 [get_ports {eb_tb4_1_DVI_OUT_EDID_SDA}]
#set_property -quiet PACKAGE_PIN R23 [get_ports {vga_out_hsync}]
#set_property -quiet PACKAGE_PIN K18 [get_ports {eb_tb4_1_DVI_OUT_IDCLK_N}]
#set_property -quiet PACKAGE_PIN L18 [get_ports {eb_tb4_1_DVI_OUT_IDCLK_P}]
#set_property -quiet PACKAGE_PIN U24 [get_ports {eb_tb4_1_DVI_OUT_ISEL_NRST}]
#set_property -quiet PACKAGE_PIN V23 [get_ports {eb_tb4_1_DVI_OUT_MSEN_PO1}]
#set_property -quiet PACKAGE_PIN L25 [get_ports {eb_tb4_1_DVI_OUT_NHPD}]
#set_property -quiet PACKAGE_PIN P25 [get_ports {eb_tb4_1_DVI_OUT_NOC}]
#set_property -quiet PACKAGE_PIN T24 [get_ports {eb_tb4_1_DVI_OUT_NPD}]
#set_property -quiet PACKAGE_PIN T23 [get_ports {vga_out_vsync}]
#set_property -quiet PACKAGE_PIN L19 [get_ports {eb_tb4_1_LED_0}]
#set_property -quiet PACKAGE_PIN K17 [get_ports {eb_tb4_1_LED_1}]
#set_property -quiet PACKAGE_PIN L14 [get_ports {eb_tb4_1_LED_2}]
#set_property -quiet PACKAGE_PIN M15 [get_ports {eb_tb4_1_LED_3}]
#set_property -quiet PACKAGE_PIN L20 [get_ports {eb_tb4_1_LED_4}]
#set_property -quiet PACKAGE_PIN K13 [get_ports {eb_tb4_1_LED_5}]
#set_property -quiet PACKAGE_PIN M14 [get_ports {eb_tb4_1_LED_6}]
#set_property -quiet PACKAGE_PIN N14 [get_ports {eb_tb4_1_LED_7}]
#set_property -quiet PACKAGE_PIN M19 [get_ports {eb_tb4_1_REF_CLK_0}]
#set_property -quiet PACKAGE_PIN L17 [get_ports {eb_tb4_1_REF_CLK_1}]
#set_property -quiet PACKAGE_PIN L15 [get_ports {eb_tb4_1_REF_CLK_2}]
#set_property -quiet PACKAGE_PIN M16 [get_ports {eb_tb4_1_REF_CLK_3}]


# FPGA module FM-XCVU440-R2 
# pins which are not connected to an x-board 
#set_property -quiet PACKAGE_PIN BE28 [get_ports {sys_clk_n}]
#set_property -quiet PACKAGE_PIN Y48 [get_ports {CLK_N_2}]
#set_property -quiet PACKAGE_PIN AA47 [get_ports {CLK_N_3}]
#set_property -quiet PACKAGE_PIN BB27 [get_ports {CLK_N_4}]
#set_property -quiet PACKAGE_PIN BD29 [get_ports {CLK_N_5}]
#set_property -quiet PACKAGE_PIN AA49 [get_ports {CLK_N_6}]
#set_property -quiet PACKAGE_PIN W46 [get_ports {CLK_N_7}]
#set_property -quiet PACKAGE_PIN BD28 [get_ports {sys_clk_p}]
#set_property -quiet PACKAGE_PIN Y47 [get_ports {CLK_P_2}]
#set_property -quiet PACKAGE_PIN AB47 [get_ports {CLK_P_3}]
#set_property -quiet PACKAGE_PIN BB26 [get_ports {CLK_P_4}]
#set_property -quiet PACKAGE_PIN BC29 [get_ports {CLK_P_5}]
#set_property -quiet PACKAGE_PIN AA48 [get_ports {CLK_P_6}]
#set_property -quiet PACKAGE_PIN Y46 [get_ports {CLK_P_7}]
#set_property -quiet PACKAGE_PIN AB45 [get_ports {DMBI_F2H_00}]
#set_property -quiet PACKAGE_PIN AB46 [get_ports {DMBI_F2H_01}]
#set_property -quiet PACKAGE_PIN AC46 [get_ports {DMBI_F2H_02}]
#set_property -quiet PACKAGE_PIN AC47 [get_ports {DMBI_F2H_03}]
#set_property -quiet PACKAGE_PIN AC42 [get_ports {DMBI_F2H_04}]
#set_property -quiet PACKAGE_PIN AC43 [get_ports {DMBI_F2H_05}]
#set_property -quiet PACKAGE_PIN W44 [get_ports {DMBI_F2H_06}]
#set_property -quiet PACKAGE_PIN W45 [get_ports {DMBI_F2H_07}]
#set_property -quiet PACKAGE_PIN AB41 [get_ports {DMBI_F2H_08}]
#set_property -quiet PACKAGE_PIN AB42 [get_ports {DMBI_F2H_09}]
#set_property -quiet PACKAGE_PIN AD53 [get_ports {DMBI_F2H_10}]
#set_property -quiet PACKAGE_PIN AC53 [get_ports {DMBI_F2H_11}]
#set_property -quiet PACKAGE_PIN AC49 [get_ports {DMBI_F2H_12}]
#set_property -quiet PACKAGE_PIN AB49 [get_ports {DMBI_F2H_13}]
#set_property -quiet PACKAGE_PIN AB50 [get_ports {DMBI_F2H_14}]
#set_property -quiet PACKAGE_PIN AA50 [get_ports {DMBI_F2H_15}]
#set_property -quiet PACKAGE_PIN AC51 [get_ports {DMBI_F2H_16}]
#set_property -quiet PACKAGE_PIN AB51 [get_ports {DMBI_F2H_17}]
#set_property -quiet PACKAGE_PIN AC52 [get_ports {DMBI_F2H_18}]
#set_property -quiet PACKAGE_PIN AB52 [get_ports {DMBI_F2H_19}]
#set_property -quiet PACKAGE_PIN BG26 [get_ports {DMBI_H2F_00}]
#set_property -quiet PACKAGE_PIN BH26 [get_ports {DMBI_H2F_01}]
#set_property -quiet PACKAGE_PIN BH28 [get_ports {DMBI_H2F_02}]
#set_property -quiet PACKAGE_PIN BJ28 [get_ports {DMBI_H2F_03}]
#set_property -quiet PACKAGE_PIN AV28 [get_ports {DMBI_H2F_04}]
#set_property -quiet PACKAGE_PIN AW28 [get_ports {DMBI_H2F_05}]
#set_property -quiet PACKAGE_PIN AU27 [get_ports {DMBI_H2F_06}]
#set_property -quiet PACKAGE_PIN AV27 [get_ports {DMBI_H2F_07}]
#set_property -quiet PACKAGE_PIN AW26 [get_ports {DMBI_H2F_08}]
#set_property -quiet PACKAGE_PIN AY26 [get_ports {DMBI_H2F_09}]
#set_property -quiet PACKAGE_PIN AU26 [get_ports {DMBI_H2F_10}]
#set_property -quiet PACKAGE_PIN AV26 [get_ports {DMBI_H2F_11}]
#set_property -quiet PACKAGE_PIN BA30 [get_ports {DMBI_H2F_12}]
#set_property -quiet PACKAGE_PIN BB30 [get_ports {DMBI_H2F_13}]
#set_property -quiet PACKAGE_PIN BA29 [get_ports {DMBI_H2F_14}]
#set_property -quiet PACKAGE_PIN BB29 [get_ports {DMBI_H2F_15}]
#set_property -quiet PACKAGE_PIN BF30 [get_ports {DMBI_H2F_16}]
#set_property -quiet PACKAGE_PIN BG30 [get_ports {DMBI_H2F_17}]
#set_property -quiet PACKAGE_PIN BH29 [get_ports {DMBI_H2F_18}]
#set_property -quiet PACKAGE_PIN BD25 [get_ports {DMBI_H2F_19}]
#set_property -quiet PACKAGE_PIN Y42 [get_ports {LED_BLUE}]
#set_property -quiet PACKAGE_PIN AC48 [get_ports {LED_BLUE2}]
#set_property -quiet PACKAGE_PIN Y43 [get_ports {LED_GREEN}]
#set_property -quiet PACKAGE_PIN Y45 [get_ports {LED_GREEN2}]
#set_property -quiet PACKAGE_PIN W43 [get_ports {LED_RED}]
#set_property -quiet PACKAGE_PIN W41 [get_ports {LED_RED2}]
#set_property -quiet PACKAGE_PIN Y41 [get_ports {LED_YELLOW}]
#set_property -quiet PACKAGE_PIN BG29 [get_ports {LED_YELLOW2}]
#set_property -quiet PACKAGE_PIN BH27 [get_ports {SRC_CLK_N_0}]
#set_property -quiet PACKAGE_PIN AW29 [get_ports {SRC_CLK_N_1}]
#set_property -quiet PACKAGE_PIN Y52 [get_ports {SRC_CLK_N_2}]
#set_property -quiet PACKAGE_PIN Y51 [get_ports {SRC_CLK_N_3}]
#set_property -quiet PACKAGE_PIN BG27 [get_ports {SRC_CLK_P_0}]
#set_property -quiet PACKAGE_PIN AV29 [get_ports {SRC_CLK_P_1}]
#set_property -quiet PACKAGE_PIN AA52 [get_ports {SRC_CLK_P_2}]
#set_property -quiet PACKAGE_PIN Y50 [get_ports {SRC_CLK_P_3}]
#set_property -quiet PACKAGE_PIN BJ30 [get_ports {SRC_SYNC_N_0}]
#set_property -quiet PACKAGE_PIN AU29 [get_ports {SRC_SYNC_N_1}]
#set_property -quiet PACKAGE_PIN Y54 [get_ports {SRC_SYNC_N_2}]
#set_property -quiet PACKAGE_PIN Y53 [get_ports {SRC_SYNC_N_3}]
#set_property -quiet PACKAGE_PIN BJ29 [get_ports {SRC_SYNC_P_0}]
#set_property -quiet PACKAGE_PIN AT29 [get_ports {SRC_SYNC_P_1}]
#set_property -quiet PACKAGE_PIN AA54 [get_ports {SRC_SYNC_P_2}]
#set_property -quiet PACKAGE_PIN AA53 [get_ports {SRC_SYNC_P_3}]
#set_property -quiet PACKAGE_PIN BF29 [get_ports {SYNC_N_0}]
#set_property -quiet PACKAGE_PIN BA28 [get_ports {SYNC_N_1}]
#set_property -quiet PACKAGE_PIN AA45 [get_ports {SYNC_N_2}]
#set_property -quiet PACKAGE_PIN AA43 [get_ports {SYNC_N_3}]
#set_property -quiet PACKAGE_PIN BA27 [get_ports {SYNC_N_4}]
#set_property -quiet PACKAGE_PIN BE30 [get_ports {SYNC_N_5}]
#set_property -quiet PACKAGE_PIN AB54 [get_ports {SYNC_N_6}]
#set_property -quiet PACKAGE_PIN AB44 [get_ports {SYNC_N_7}]
#set_property -quiet PACKAGE_PIN BF28 [get_ports {SYNC_P_0}]
#set_property -quiet PACKAGE_PIN AY28 [get_ports {SYNC_P_1}]
#set_property -quiet PACKAGE_PIN AA44 [get_ports {SYNC_P_2}]
#set_property -quiet PACKAGE_PIN AA42 [get_ports {SYNC_P_3}]
#set_property -quiet PACKAGE_PIN AY27 [get_ports {SYNC_P_4}]
#set_property -quiet PACKAGE_PIN BD30 [get_ports {SYNC_P_5}]
#set_property -quiet PACKAGE_PIN AC54 [get_ports {SYNC_P_6}]
#set_property -quiet PACKAGE_PIN AC44 [get_ports {SYNC_P_7}]
#set_property -quiet PACKAGE_PIN BF27 [get_ports {UART_CTS_B}]
#set_property -quiet PACKAGE_PIN BD26 [get_ports {UART_RTS_B}]
#set_property -quiet PACKAGE_PIN BE26 [get_ports {UART_RXD}]
#set_property -quiet PACKAGE_PIN BE27 [get_ports {UART_TXD}]

# VREF/DCI constraints for banks related to connector BA1
#   set_property INTERNAL_VREF {0.90} [get_iobanks 68]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 67]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 66]

## VREF/DCI constraints for banks related to connector BA2
#   set_property INTERNAL_VREF {0.90} [get_iobanks 60]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 39]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 40]

## VREF/DCI constraints for banks related to connector BB1
#   set_property INTERNAL_VREF {0.90} [get_iobanks 49]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 51]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 50]

## VREF/DCI constraints for banks related to connector BB2
#   set_property INTERNAL_VREF {0.90} [get_iobanks 73]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 53]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 52]

# VREF/DCI constraints for banks related to connector TA1
   set_property INTERNAL_VREF {0.90} [get_iobanks 42]
   set_property INTERNAL_VREF {0.90} [get_iobanks 41]
   set_property INTERNAL_VREF {0.90} [get_iobanks 43]

# VREF/DCI constraints for banks related to connector TA2
#   set_property INTERNAL_VREF {0.90} [get_iobanks 62]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 61]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 63]

## VREF/DCI constraints for banks related to connector TB1
#   set_property INTERNAL_VREF {0.90} [get_iobanks 47]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 46]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 48]

## VREF/DCI constraints for banks related to connector TB2
#   set_property INTERNAL_VREF {0.90} [get_iobanks 72]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 71]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 70]

# VREF/DCI constraints for banks related to connector TA1V1
#   set_property INTERNAL_VREF {0.90} [get_iobanks 44]

