-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cnn_accel_conv_layer_Pipeline_VITIS_LOOP_68_6_VITIS_LOOP_69_7_VITIS_LOOP_70_8_w_1_conv_9j0 is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cnn_accel_conv_layer_Pipeline_VITIS_LOOP_68_6_VITIS_LOOP_69_7_VITIS_LOOP_70_8_w_1_conv_9j0 is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00000000", 1 => "00000000", 2 => "00000000", 3 => "00000000", 
    4 => "00000001", 5 => "11111101", 6 => "00000100", 7 => "11111011", 
    8 => "00000000", 9 => "00000000", 10 => "00101100", 11 => "11010000", 
    12 => "00000000", 13 => "00000000", 14 => "00000100", 15 => "00000101", 
    16 => "00000000", 17 => "11111011", 18 => "00000010", 19 => "11111110", 
    20 => "11111101", 21 => "11111111", 22 => "00010100", 23 => "00000000", 
    24 => "11101001", 25 => "00000001", 26 => "11100101", 27 => "11110100", 
    28 => "00000000", 29 => "00000000", 30 => "11111110", 31 => "00000001", 
    32 => "00000000", 33 => "00000000", 34 => "11111001", 35 => "01011011", 
    36 => "00000001", 37 => "11111110", 38 => "00000110", 39 => "00101011", 
    40 => "11111111", 41 => "00000001", 42 => "11010001", 43 => "11010110", 
    44 => "00000000", 45 => "00000000", 46 => "00000110", 47 => "00001000", 
    48 => "11000010", 49 => "11101001", 50 => "00000000", 51 => "00000000", 
    52 => "00000000", 53 => "00000000", 54 => "00000000", 55 => "00000000", 
    56 => "00000011", 57 => "00001110", 58 => "00000001", 59 => "00000000", 
    60 => "00000000", 61 => "00000000", 62 => "11111110", 63 => "00000001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;

end if;
end process;

end rtl;

