
  function Bit#(`xlen) fn_probe_csr (Bit#(12) csr_addr);
    case (csr_addr)

        `MVENDORID : return zeroExtend(soc.soc_sb.sbread.mv_csr_mvendorid);
        `STVEC : return zeroExtend(soc.soc_sb.sbread.mv_csr_stvec);
        `MTVEC : return zeroExtend(soc.soc_sb.sbread.mv_csr_mtvec);
        `MSTATUS : return zeroExtend(soc.soc_sb.sbread.mv_csr_mstatus);
        `MARCHID : return zeroExtend(soc.soc_sb.sbread.mv_csr_marchid);
        `MIMPID : return zeroExtend(soc.soc_sb.sbread.mv_csr_mimpid);
        `MHARTID : return zeroExtend(soc.soc_sb.sbread.mv_csr_mhartid);
        `MIP : return zeroExtend(soc.soc_sb.sbread.mv_csr_mip);
        `SIP : return zeroExtend(soc.soc_sb.sbread.mv_csr_sip);
        `MIE : return zeroExtend(soc.soc_sb.sbread.mv_csr_mie);
        `SIE : return zeroExtend(soc.soc_sb.sbread.mv_csr_sie);
        `MSCRATCH : return zeroExtend(soc.soc_sb.sbread.mv_csr_mscratch);
        `SSCRATCH : return zeroExtend(soc.soc_sb.sbread.mv_csr_sscratch);
        `SEPC : return zeroExtend(soc.soc_sb.sbread.mv_csr_sepc);
        `STVAL : return zeroExtend(soc.soc_sb.sbread.mv_csr_stval);
        `SCAUSE : return zeroExtend(soc.soc_sb.sbread.mv_csr_scause);
        `MEPC : return zeroExtend(soc.soc_sb.sbread.mv_csr_mepc);
        `MTVAL : return zeroExtend(soc.soc_sb.sbread.mv_csr_mtval);
        `MCAUSE : return zeroExtend(soc.soc_sb.sbread.mv_csr_mcause);
        `MCYCLEH : return zeroExtend(soc.soc_sb.sbread.mv_csr_mcycleh);
        `MCYCLE : return zeroExtend(soc.soc_sb.sbread.mv_csr_mcycle);
        `MINSTRETH : return zeroExtend(soc.soc_sb.sbread.mv_csr_minstreth);
        `MINSTRET : return zeroExtend(soc.soc_sb.sbread.mv_csr_minstret);
        `TIMEH : return zeroExtend(soc.soc_sb.sbread.mv_csr_timeh);
        `TIME : return zeroExtend(soc.soc_sb.sbread.mv_csr_time);
        `MIDELEG : return zeroExtend(soc.soc_sb.sbread.mv_csr_mideleg);
        `MEDELEG : return zeroExtend(soc.soc_sb.sbread.mv_csr_medeleg);
        `PMPCFG0 : return zeroExtend(soc.soc_sb.sbread.mv_csr_pmpcfg0);
        `PMPADDR0 : return zeroExtend(soc.soc_sb.sbread.mv_csr_pmpaddr0);
        `PMPADDR1 : return zeroExtend(soc.soc_sb.sbread.mv_csr_pmpaddr1);
        `PMPADDR2 : return zeroExtend(soc.soc_sb.sbread.mv_csr_pmpaddr2);
        `PMPADDR3 : return zeroExtend(soc.soc_sb.sbread.mv_csr_pmpaddr3);
        `MCOUNTEREN : return zeroExtend(soc.soc_sb.sbread.mv_csr_mcounteren);
        `SCOUNTEREN : return zeroExtend(soc.soc_sb.sbread.mv_csr_scounteren);
        `MENVCFG : return zeroExtend(soc.soc_sb.sbread.mv_csr_menvcfg);
        `MENVCFGH : return zeroExtend(soc.soc_sb.sbread.mv_csr_menvcfgh);
        `SENVCFG : return zeroExtend(soc.soc_sb.sbread.mv_csr_senvcfg);
        `SATP : return zeroExtend(soc.soc_sb.sbread.mv_csr_satp);
        `MISA : return zeroExtend(soc.soc_sb.sbread.mv_csr_misa);
        `MSTATUSH : return zeroExtend(soc.soc_sb.sbread.mv_csr_mstatush);
        `MCOUNTINHIBIT : return zeroExtend(soc.soc_sb.sbread.mv_csr_mcountinhibit);
        `CUSTOMCONTROL : return zeroExtend(soc.soc_sb.sbread.mv_csr_customcontrol);
        `MHPMEVENT3 : return zeroExtend(soc.soc_sb.sbread.mv_csr_mhpmevent3);
        `MHPMEVENT4 : return zeroExtend(soc.soc_sb.sbread.mv_csr_mhpmevent4);
        `MHPMEVENT5 : return zeroExtend(soc.soc_sb.sbread.mv_csr_mhpmevent5);
        `MHPMEVENT6 : return zeroExtend(soc.soc_sb.sbread.mv_csr_mhpmevent6);
        `MHPMCOUNTER3 : return zeroExtend(soc.soc_sb.sbread.mv_csr_mhpmcounter3);
        `MHPMCOUNTER3H : return zeroExtend(soc.soc_sb.sbread.mv_csr_mhpmcounter3h);
        `MHPMCOUNTER4 : return zeroExtend(soc.soc_sb.sbread.mv_csr_mhpmcounter4);
        `MHPMCOUNTER4H : return zeroExtend(soc.soc_sb.sbread.mv_csr_mhpmcounter4h);
        `MHPMCOUNTER5 : return zeroExtend(soc.soc_sb.sbread.mv_csr_mhpmcounter5);
        `MHPMCOUNTER5H : return zeroExtend(soc.soc_sb.sbread.mv_csr_mhpmcounter5h);
        `MHPMCOUNTER6 : return zeroExtend(soc.soc_sb.sbread.mv_csr_mhpmcounter6);
        `MHPMCOUNTER6H : return zeroExtend(soc.soc_sb.sbread.mv_csr_mhpmcounter6h);
        `DCSR : return zeroExtend(soc.soc_sb.sbread.mv_csr_dcsr);
        `DPC : return zeroExtend(soc.soc_sb.sbread.mv_csr_dpc);
        `DSCRATCH0 : return zeroExtend(soc.soc_sb.sbread.mv_csr_dscratch0);
        `DSCRATCH1 : return zeroExtend(soc.soc_sb.sbread.mv_csr_dscratch1);
    default: return 0;
    endcase
  endfunction
