set_property SRC_FILE_INFO {cfile:/scratch1/iot/new/gc2025/hw/constraints.xdc rfile:../../../../../constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AD11  IOSTANDARD DIFF_SSTL15     } [get_ports { sys_clk_n }]; #IO_L12N_T1_MRCC_33 Sch=sysclk_n
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AD12  IOSTANDARD DIFF_SSTL15     } [get_ports { sys_clk_p }]; #IO_L12P_T1_MRCC_33 Sch=sysclk_p
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets clk_div/inst/clk_in1_clk_divider]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R19   IOSTANDARD LVCMOS33 } [get_ports { sys_rst }]; #IO_0_14 Sch=cpu_resetn
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y23   IOSTANDARD LVCMOS33 } [get_ports { uart0_SOUT }]; #IO_L1P_T0_12 Sch=uart_rx_out
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y20   IOSTANDARD LVCMOS33 } [get_ports { uart0_SIN }]; #IO_0_12 Sch=uart_tx_in
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AC17  IOSTANDARD LVCMOS18 } [get_ports { oled_dcpin }]; #IO_L18N_T2_32 Sch=oled_dc
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AB17  IOSTANDARD LVCMOS18 } [get_ports { oled_res }]; #IO_L18P_T2_32 Sch=oled_res
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AF17  IOSTANDARD LVCMOS18 } [get_ports { oled_clk }]; #IO_L12P_T1_MRCC_32 Sch=oled_sclk
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y15   IOSTANDARD LVCMOS18 } [get_ports { oled_sdin }]; #IO_L24N_T3_32 Sch=oled_sdin
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AB22  IOSTANDARD LVCMOS33 } [get_ports { oled_vbat }]; #IO_L3P_T0_DQS_12 Sch=oled_vbat
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AG17  IOSTANDARD LVCMOS18 } [get_ports { oled_vdd }]; #IO_L12N_T1_MRCC_32 Sch=oled_vdd
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U27   IOSTANDARD LVCMOS33 } [get_ports { spi0_mosi }]; #IO_L13P_T2_MRCC_14 Sch=ja_p[1]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U28   IOSTANDARD LVCMOS33 } [get_ports { spi0_ncs }]; #IO_L13N_T2_MRCC_14 Sch=ja_n[1]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T26   IOSTANDARD LVCMOS33 } [get_ports { spi0_miso }]; #IO_L12P_T1_MRCC_14 Sch=ja_p[2]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T27   IOSTANDARD LVCMOS33 } [get_ports { i2c1_scl }]; #IO_L12N_T1_MRCC_14 Sch=ja_n[2]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T22   IOSTANDARD LVCMOS33 } [get_ports { i2c0_sda }]; #IO_L5P_T0_D06_14 Sch=ja_p[3]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T23   IOSTANDARD LVCMOS33 } [get_ports { i2c0_scl }]; #IO_L5N_T0_D07_14 Sch=ja_n[3]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T20   IOSTANDARD LVCMOS33 } [get_ports { i2c1_sda }]; #IO_L4P_T0_D04_14 Sch=ja_p[4]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T21   IOSTANDARD LVCMOS33 } [get_ports { io7_cell }]; #IO_L4N_T0_D05_14 Sch=ja_n[4]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V29   IOSTANDARD LVCMOS33 } [get_ports { io17_cell }]; #IO_L17P_T2_A14_D30_14 Sch=jb_p[1]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V30   IOSTANDARD LVCMOS33 } [get_ports { io18_cell }]; #IO_L17N_T2_A13_D29_14 Sch=jb_n[1]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V25   IOSTANDARD LVCMOS33 } [get_ports { io19_cell }]; #IO_L18P_T2_A12_D28_14 Sch=jb_p[2]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W26   IOSTANDARD LVCMOS33 } [get_ports { io20_cell }]; #IO_L18N_T2_A11_D27_14 Sch=jb_n[2]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T25   IOSTANDARD LVCMOS33 } [get_ports { io12_cell }]; #IO_L14P_T2_SRCC_14 Sch=jb_p[3]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U25   IOSTANDARD LVCMOS33 } [get_ports { io13_cell }]; #IO_L14N_T2_SRCC_14 Sch=jb_n[3]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U22   IOSTANDARD LVCMOS33 } [get_ports { io16_cell }]; #IO_L21P_T3_DQS_14 Sch=jb_p[4]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U23   IOSTANDARD LVCMOS33 } [get_ports { io8_cell }]; #IO_L21N_T3_DQS_A06_D22_14 Sch=jb_n[4]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AC26  IOSTANDARD LVCMOS33 } [get_ports { spi2_mosi }]; #IO_L19P_T3_13 Sch=jc[1]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AJ27  IOSTANDARD LVCMOS33 } [get_ports { spi2_ncs }]; #IO_L20P_T3_13 Sch=jc[2]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AH30  IOSTANDARD LVCMOS33 } [get_ports { spi2_miso }]; #IO_L18N_T2_13 Sch=jc[3]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AK29  IOSTANDARD LVCMOS33 } [get_ports { spi2_sclk }]; #IO_L15P_T2_DQS_13 Sch=jc[4]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AD26  IOSTANDARD LVCMOS33 } [get_ports { gpio_4 }]; #IO_L19N_T3_VREF_13 Sch=jc[7]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AG30  IOSTANDARD LVCMOS33 } [get_ports { gpio_7 }]; #IO_L18P_T2_13 Sch=jc[8]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AK30  IOSTANDARD LVCMOS33 } [get_ports { gpio_8 }]; #IO_L15N_T2_DQS_13 Sch=jc[9]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AK28  IOSTANDARD LVCMOS33 } [get_ports { gpio_14 }]; #IO_L20N_T3_13 Sch=jc[10]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V27   IOSTANDARD LVCMOS33 } [get_ports { spi3_sclk }]; #IO_L16N_T2_A15_D31_14 Sch=jd[1]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y30   IOSTANDARD LVCMOS33 } [get_ports { io9_cell }]; #IO_L8P_T1_13 Sch=jd[2]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V24   IOSTANDARD LVCMOS33 } [get_ports { io10_cell }]; #IO_L23N_T3_A02_D18_14 Sch=jd[3]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W22   IOSTANDARD LVCMOS33 } [get_ports { spi3_mosi }]; #IO_L24N_T3_A00_D16_14 Sch=jd[4]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U24   IOSTANDARD LVCMOS33 } [get_ports { gpio_20 }]; #IO_L23P_T3_A03_D19_14 Sch=jd[7]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y26   IOSTANDARD LVCMOS33 } [get_ports { gpio_21 }]; #IO_L1P_T0_13 Sch=jd[8]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V22   IOSTANDARD LVCMOS33 } [get_ports { gpio_22 }]; #IO_L22N_T3_A04_D20_14 Sch=jd[9]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W21   IOSTANDARD LVCMOS33 } [get_ports { gpio_23 }]; #IO_L24P_T3_A01_D17_14 Sch=jd[10]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J24   IOSTANDARD LVCMOS33 } [get_ports { gpio_24 }]; #IO_L1N_T0_AD0N_15 Sch=xadc0r_n
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J23   IOSTANDARD LVCMOS33 } [get_ports { gpio_25 }]; #IO_L1P_T0_AD0P_15 Sch=xadc0r_p
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K24   IOSTANDARD LVCMOS33 } [get_ports { gpio_26 }]; #IO_L3N_T0_DQS_AD1N_15 Sch=xadc1r_n
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K23   IOSTANDARD LVCMOS33 } [get_ports { gpio_27 }]; #IO_L3P_T0_DQS_AD1P_15 Sch=xadc1r_p
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L23   IOSTANDARD LVCMOS33 } [get_ports { gpio_28 }]; #IO_L2N_T0_AD8N_15 Sch=xadc8r_n
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L22   IOSTANDARD LVCMOS33 } [get_ports { gpio_29 }]; #IO_L2P_T0_AD8P_15 Sch=xadc8r_p
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K21   IOSTANDARD LVCMOS33 } [get_ports { gpio_30 }]; #IO_L4N_T0_AD9N_15 Sch=xadc9r_n
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L21   IOSTANDARD LVCMOS33 } [get_ports { gpio_31 }]; #IO_L4P_T0_AD9P_15 Sch=xadc9r_p
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G30   IOSTANDARD LVCMOS12 } [get_ports { spi3_ncs }]; #IO_L24N_T3_16 Sch=fmc_la_n[02]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H30   IOSTANDARD LVCMOS12 } [get_ports { spi3_miso }]; #IO_L24P_T3_16 Sch=fmc_la_p[02]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E30   IOSTANDARD LVCMOS12 } [get_ports { gpio_15 }]; #IO_L18N_T2_16 Sch=fmc_la_n[03]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E29   IOSTANDARD LVCMOS12 } [get_ports { gpio_16 }]; #IO_L18P_T2_16 Sch=fmc_la_p[03]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H27   IOSTANDARD LVCMOS12 } [get_ports { gpio_17 }]; #IO_L23N_T3_16 Sch=fmc_la_n[04]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H26   IOSTANDARD LVCMOS12 } [get_ports { gpio_18 }]; #IO_L23P_T3_16 Sch=fmc_la_p[04]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A30   IOSTANDARD LVCMOS12 } [get_ports { gpio_19 }]; #IO_L17N_T2_16 Sch=fmc_la_n[05]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B30   IOSTANDARD LVCMOS12 } [get_ports { io19_cell }]; #IO_L17P_T2_16 Sch=fmc_la_p[05]
