-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cnn_accel_conv_layer_1_Pipeline_VITIS_LOOP_62_7_VITIS_LOOP_63_8_VITIS_LOOP_64_9_w_1_con1iI is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cnn_accel_conv_layer_1_Pipeline_VITIS_LOOP_62_7_VITIS_LOOP_63_8_VITIS_LOOP_64_9_w_1_con1iI is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00000000", 1 => "00000000", 2 => "00000000", 3 => "00000000", 
    4 => "10100110", 5 => "00001010", 6 => "11111100", 7 => "11111111", 
    8 => "00000000", 9 => "00000000", 10 => "11111001", 11 => "00001000", 
    12 => "00000000", 13 => "00000000", 14 => "00000111", 15 => "11110100", 
    16 => "11111000", 17 => "00000110", 18 => "01011111", 19 => "11101111", 
    20 => "00010110", 21 => "11111100", 22 => "00000001", 23 => "11111111", 
    24 => "11111101", 25 => "00000010", 26 => "11111110", 27 => "00001100", 
    28 => "00000000", 29 => "00000000", 30 => "00000011", 31 => "11111101", 
    32 => "00000000", 33 => "00000000", 34 => "11110011", 35 => "00010100", 
    36 => "11111101", 37 => "11111111", 38 => "00000111", 39 => "11110100", 
    40 => "11111001", 41 => "00000111", 42 => "00000100", 43 => "11111011", 
    44 => "00000000", 45 => "00000000", 46 => "00000000", 47 => "00001010", 
    48 => "11111000", 49 => "00000100", 50 => "00000000", 51 => "00000000", 
    52 => "00000000", 53 => "00000000", 54 => "00000000", 55 => "00000000", 
    56 => "11111001", 57 => "00000110", 58 => "11111001", 59 => "00000001", 
    60 => "00000000", 61 => "00000000", 62 => "11111100", 63 => "00000100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;

end if;
end process;

end rtl;

