-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cnn_accel_conv_layer_1_Pipeline_VITIS_LOOP_62_7_VITIS_LOOP_63_8_VITIS_LOOP_64_9_w_1_conShg is 
    generic(
             DataWidth     : integer := 6; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cnn_accel_conv_layer_1_Pipeline_VITIS_LOOP_62_7_VITIS_LOOP_63_8_VITIS_LOOP_64_9_w_1_conShg is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "000000", 1 => "000000", 2 => "000000", 3 => "000000", 
    4 => "110111", 5 => "101101", 6 => "000110", 7 => "111111", 
    8 => "000000", 9 => "000000", 10 => "010011", 11 => "000100", 
    12 => "000001", 13 => "001111", 14 => "111010", 15 => "111111", 
    16 => "010001", 17 => "111101", 18 => "111110", 19 => "001100", 
    20 => "111100", 21 => "111110", 22 => "111111", 23 => "111111", 
    24 => "000010", 25 => "111111", 26 => "001000", 27 => "000010", 
    28 => "000000", 29 => "000000", 30 => "110101", 31 => "000010", 
    32 => "000000", 33 => "000000", 34 => "001010", 35 => "000010", 
    36 => "001000", 37 => "111101", 38 => "111111", 39 => "000001", 
    40 => "001111", 41 => "111100", 42 => "110001", 43 => "111101", 
    44 => "000000", 45 => "000000", 46 => "110000", 47 => "000101", 
    48 => "001000", 49 => "000000", 50 => "000000", 51 => "000000", 
    52 => "000000", 53 => "000000", 54 => "000000", 55 => "000000", 
    56 => "001010", 57 => "000010", 58 => "000000", 59 => "101001", 
    60 => "000000", 61 => "000000", 62 => "000011", 63 => "000000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;

end if;
end process;

end rtl;

