-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cnn_accel_conv_layer_1_Pipeline_VITIS_LOOP_60_6_VITIS_LOOP_61_7_VITIS_LOOP_62_8_w_1_conbil is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cnn_accel_conv_layer_1_Pipeline_VITIS_LOOP_60_6_VITIS_LOOP_61_7_VITIS_LOOP_62_8_w_1_conbil is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00000000", 1 => "00000000", 2 => "00000000", 3 => "00000000", 
    4 => "11111100", 5 => "00000010", 6 => "00000101", 7 => "00000101", 
    8 => "00000000", 9 => "00000000", 10 => "11111110", 11 => "00011101", 
    12 => "00000001", 13 => "00000000", 14 => "00011101", 15 => "11111010", 
    16 => "11000100", 17 => "00000101", 18 => "11111110", 19 => "00000100", 
    20 => "11111110", 21 => "11111111", 22 => "00000000", 23 => "11111111", 
    24 => "11111111", 25 => "11110111", 26 => "10110110", 27 => "00000110", 
    28 => "00000000", 29 => "00000000", 30 => "11111010", 31 => "00000000", 
    32 => "00000000", 33 => "00000000", 34 => "11110011", 35 => "11110011", 
    36 => "11111110", 37 => "11111110", 38 => "00100011", 39 => "11100100", 
    40 => "00000100", 41 => "00000000", 42 => "00000000", 43 => "00000000", 
    44 => "00000000", 45 => "00000000", 46 => "00100100", 47 => "11111101", 
    48 => "11110000", 49 => "00000110", 50 => "00000000", 51 => "00000000", 
    52 => "00000000", 53 => "00000000", 54 => "00000000", 55 => "00000000", 
    56 => "11111110", 57 => "11111100", 58 => "00000000", 59 => "00000001", 
    60 => "00000000", 61 => "00000000", 62 => "11111110", 63 => "00000100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;

end if;
end process;

end rtl;

