// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mobilenet_top_gap_6_6_6_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pool_res_address0,
        pool_res_ce0,
        pool_res_we0,
        pool_res_d0,
        fm_B_address0,
        fm_B_ce0,
        fm_B_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] pool_res_address0;
output   pool_res_ce0;
output   pool_res_we0;
output  [15:0] pool_res_d0;
output  [13:0] fm_B_address0;
output   fm_B_ce0;
input  [15:0] fm_B_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln89_fu_187_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln91_fu_199_p2;
reg   [0:0] icmp_ln91_reg_576;
reg   [0:0] icmp_ln91_reg_576_pp0_iter1_reg;
reg   [0:0] icmp_ln91_reg_576_pp0_iter2_reg;
reg   [0:0] icmp_ln91_reg_576_pp0_iter3_reg;
wire   [2:0] select_ln89_2_fu_268_p3;
reg   [2:0] select_ln89_2_reg_585;
reg   [2:0] select_ln89_2_reg_585_pp0_iter2_reg;
reg   [2:0] select_ln89_2_reg_585_pp0_iter3_reg;
reg   [2:0] select_ln89_2_reg_585_pp0_iter4_reg;
reg   [2:0] select_ln89_2_reg_585_pp0_iter5_reg;
reg   [2:0] select_ln89_2_reg_585_pp0_iter6_reg;
reg   [2:0] select_ln89_2_reg_585_pp0_iter7_reg;
reg   [2:0] select_ln89_2_reg_585_pp0_iter8_reg;
reg   [2:0] select_ln89_2_reg_585_pp0_iter9_reg;
reg   [2:0] select_ln89_2_reg_585_pp0_iter10_reg;
wire   [2:0] select_ln91_fu_294_p3;
reg   [2:0] select_ln91_reg_590;
wire   [6:0] add_ln94_fu_340_p2;
reg   [6:0] add_ln94_reg_596;
wire   [0:0] icmp_ln92_1_fu_352_p2;
reg   [0:0] icmp_ln92_1_reg_601;
reg   [0:0] icmp_ln92_1_reg_601_pp0_iter2_reg;
reg   [0:0] icmp_ln92_1_reg_601_pp0_iter3_reg;
reg   [0:0] icmp_ln92_1_reg_601_pp0_iter4_reg;
reg   [0:0] icmp_ln92_1_reg_601_pp0_iter5_reg;
reg   [0:0] icmp_ln92_1_reg_601_pp0_iter6_reg;
reg   [0:0] icmp_ln92_1_reg_601_pp0_iter7_reg;
reg   [0:0] icmp_ln92_1_reg_601_pp0_iter8_reg;
reg   [0:0] icmp_ln92_1_reg_601_pp0_iter9_reg;
reg   [0:0] icmp_ln92_1_reg_601_pp0_iter10_reg;
wire   [0:0] icmp_ln91_1_fu_358_p2;
reg   [0:0] icmp_ln91_1_reg_605;
reg   [0:0] icmp_ln91_1_reg_605_pp0_iter2_reg;
reg   [0:0] icmp_ln91_1_reg_605_pp0_iter3_reg;
reg   [0:0] icmp_ln91_1_reg_605_pp0_iter4_reg;
reg   [0:0] icmp_ln91_1_reg_605_pp0_iter5_reg;
reg   [0:0] icmp_ln91_1_reg_605_pp0_iter6_reg;
reg   [0:0] icmp_ln91_1_reg_605_pp0_iter7_reg;
reg   [0:0] icmp_ln91_1_reg_605_pp0_iter8_reg;
reg   [0:0] icmp_ln91_1_reg_605_pp0_iter9_reg;
reg   [0:0] icmp_ln91_1_reg_605_pp0_iter10_reg;
reg   [15:0] fm_B_load_reg_614;
wire   [39:0] s_fu_432_p2;
reg   [39:0] s_reg_619;
reg   [0:0] tmp_23_reg_624;
reg   [0:0] tmp_23_reg_624_pp0_iter5_reg;
reg   [0:0] tmp_23_reg_624_pp0_iter6_reg;
reg   [0:0] tmp_23_reg_624_pp0_iter7_reg;
reg   [0:0] tmp_23_reg_624_pp0_iter8_reg;
reg   [0:0] tmp_23_reg_624_pp0_iter9_reg;
reg   [0:0] tmp_23_reg_624_pp0_iter10_reg;
wire   [112:0] grp_fu_146_p2;
reg   [112:0] mul_ln96_reg_635;
reg   [23:0] tmp_11_cast_reg_640;
wire   [23:0] select_ln96_fu_488_p3;
reg   [23:0] select_ln96_reg_645;
reg   [15:0] tmp_1_reg_650;
wire   [31:0] zext_ln94_1_fu_406_p1;
wire    ap_block_pp0_stage0;
wire   [31:0] zext_ln96_fu_526_p1;
reg   [39:0] s_8_fu_96;
wire    ap_loop_init;
reg   [2:0] w_fu_100;
wire   [2:0] add_ln92_fu_346_p2;
reg   [2:0] h_fu_104;
reg   [5:0] indvar_flatten_fu_108;
wire   [5:0] select_ln91_1_fu_211_p3;
reg   [5:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [2:0] c_fu_112;
reg   [7:0] indvar_flatten14_fu_116;
wire   [7:0] add_ln89_1_fu_193_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten14_load;
reg    fm_B_ce0_local;
reg    pool_res_we0_local;
wire   [15:0] select_ln96_1_fu_519_p3;
reg    pool_res_ce0_local;
wire   [57:0] grp_fu_146_p1;
wire   [5:0] add_ln91_1_fu_205_p2;
wire   [0:0] icmp_ln92_fu_256_p2;
wire   [0:0] xor_ln89_fu_251_p2;
wire   [2:0] add_ln89_fu_238_p2;
wire   [2:0] select_ln89_fu_244_p3;
wire   [0:0] and_ln89_fu_262_p2;
wire   [0:0] empty_fu_281_p2;
wire   [2:0] add_ln91_fu_275_p2;
wire   [3:0] tmp_fu_302_p3;
wire   [2:0] w_mid2_fu_286_p3;
wire   [4:0] tmp_22_fu_322_p3;
wire   [6:0] p_shl_fu_314_p3;
wire   [6:0] zext_ln94_2_fu_330_p1;
wire   [6:0] zext_ln91_fu_310_p1;
wire   [6:0] sub_ln94_fu_334_p2;
wire   [8:0] zext_ln94_fu_387_p1;
wire   [8:0] mul_ln_fu_379_p4;
wire   [8:0] add_ln94_1_fu_390_p2;
wire   [7:0] lshr_ln_fu_396_p4;
wire   [23:0] shl_ln_fu_421_p3;
wire  signed [39:0] sext_ln94_fu_428_p1;
wire   [39:0] select_ln89_1_fu_414_p3;
wire  signed [55:0] shl_ln3_fu_451_p3;
wire   [112:0] sub_ln96_fu_473_p2;
wire   [23:0] tmp_10_cast_fu_478_p4;
wire   [23:0] sub_ln96_1_fu_504_p2;
wire   [15:0] tmp_s_fu_509_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 s_8_fu_96 = 40'd0;
#0 w_fu_100 = 3'd0;
#0 h_fu_104 = 3'd0;
#0 indvar_flatten_fu_108 = 6'd0;
#0 c_fu_112 = 3'd0;
#0 indvar_flatten14_fu_116 = 8'd0;
#0 ap_done_reg = 1'b0;
end

mobilenet_top_mul_56s_58ns_113_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 56 ),
    .din1_WIDTH( 58 ),
    .dout_WIDTH( 113 ))
mul_56s_58ns_113_5_1_U75(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(shl_ln3_fu_451_p3),
    .din1(grp_fu_146_p1),
    .ce(1'b1),
    .dout(grp_fu_146_p2)
);

mobilenet_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_112 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            c_fu_112 <= select_ln89_2_fu_268_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            h_fu_104 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            h_fu_104 <= select_ln91_fu_294_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln89_fu_187_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten14_fu_116 <= add_ln89_1_fu_193_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten14_fu_116 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln89_fu_187_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_108 <= select_ln91_1_fu_211_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_108 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            s_8_fu_96 <= 40'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            s_8_fu_96 <= s_fu_432_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_fu_100 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            w_fu_100 <= add_ln92_fu_346_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln94_reg_596[6 : 1] <= add_ln94_fu_340_p2[6 : 1];
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln91_1_reg_605 <= icmp_ln91_1_fu_358_p2;
        icmp_ln91_reg_576 <= icmp_ln91_fu_199_p2;
        icmp_ln91_reg_576_pp0_iter1_reg <= icmp_ln91_reg_576;
        icmp_ln92_1_reg_601 <= icmp_ln92_1_fu_352_p2;
        select_ln89_2_reg_585 <= select_ln89_2_fu_268_p3;
        select_ln91_reg_590 <= select_ln91_fu_294_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        fm_B_load_reg_614 <= fm_B_q0;
        icmp_ln91_1_reg_605_pp0_iter10_reg <= icmp_ln91_1_reg_605_pp0_iter9_reg;
        icmp_ln91_1_reg_605_pp0_iter2_reg <= icmp_ln91_1_reg_605;
        icmp_ln91_1_reg_605_pp0_iter3_reg <= icmp_ln91_1_reg_605_pp0_iter2_reg;
        icmp_ln91_1_reg_605_pp0_iter4_reg <= icmp_ln91_1_reg_605_pp0_iter3_reg;
        icmp_ln91_1_reg_605_pp0_iter5_reg <= icmp_ln91_1_reg_605_pp0_iter4_reg;
        icmp_ln91_1_reg_605_pp0_iter6_reg <= icmp_ln91_1_reg_605_pp0_iter5_reg;
        icmp_ln91_1_reg_605_pp0_iter7_reg <= icmp_ln91_1_reg_605_pp0_iter6_reg;
        icmp_ln91_1_reg_605_pp0_iter8_reg <= icmp_ln91_1_reg_605_pp0_iter7_reg;
        icmp_ln91_1_reg_605_pp0_iter9_reg <= icmp_ln91_1_reg_605_pp0_iter8_reg;
        icmp_ln91_reg_576_pp0_iter2_reg <= icmp_ln91_reg_576_pp0_iter1_reg;
        icmp_ln91_reg_576_pp0_iter3_reg <= icmp_ln91_reg_576_pp0_iter2_reg;
        icmp_ln92_1_reg_601_pp0_iter10_reg <= icmp_ln92_1_reg_601_pp0_iter9_reg;
        icmp_ln92_1_reg_601_pp0_iter2_reg <= icmp_ln92_1_reg_601;
        icmp_ln92_1_reg_601_pp0_iter3_reg <= icmp_ln92_1_reg_601_pp0_iter2_reg;
        icmp_ln92_1_reg_601_pp0_iter4_reg <= icmp_ln92_1_reg_601_pp0_iter3_reg;
        icmp_ln92_1_reg_601_pp0_iter5_reg <= icmp_ln92_1_reg_601_pp0_iter4_reg;
        icmp_ln92_1_reg_601_pp0_iter6_reg <= icmp_ln92_1_reg_601_pp0_iter5_reg;
        icmp_ln92_1_reg_601_pp0_iter7_reg <= icmp_ln92_1_reg_601_pp0_iter6_reg;
        icmp_ln92_1_reg_601_pp0_iter8_reg <= icmp_ln92_1_reg_601_pp0_iter7_reg;
        icmp_ln92_1_reg_601_pp0_iter9_reg <= icmp_ln92_1_reg_601_pp0_iter8_reg;
        mul_ln96_reg_635 <= grp_fu_146_p2;
        s_reg_619 <= s_fu_432_p2;
        select_ln89_2_reg_585_pp0_iter10_reg <= select_ln89_2_reg_585_pp0_iter9_reg;
        select_ln89_2_reg_585_pp0_iter2_reg <= select_ln89_2_reg_585;
        select_ln89_2_reg_585_pp0_iter3_reg <= select_ln89_2_reg_585_pp0_iter2_reg;
        select_ln89_2_reg_585_pp0_iter4_reg <= select_ln89_2_reg_585_pp0_iter3_reg;
        select_ln89_2_reg_585_pp0_iter5_reg <= select_ln89_2_reg_585_pp0_iter4_reg;
        select_ln89_2_reg_585_pp0_iter6_reg <= select_ln89_2_reg_585_pp0_iter5_reg;
        select_ln89_2_reg_585_pp0_iter7_reg <= select_ln89_2_reg_585_pp0_iter6_reg;
        select_ln89_2_reg_585_pp0_iter8_reg <= select_ln89_2_reg_585_pp0_iter7_reg;
        select_ln89_2_reg_585_pp0_iter9_reg <= select_ln89_2_reg_585_pp0_iter8_reg;
        select_ln96_reg_645 <= select_ln96_fu_488_p3;
        tmp_11_cast_reg_640 <= {{grp_fu_146_p2[101:78]}};
        tmp_1_reg_650 <= {{select_ln96_fu_488_p3[23:8]}};
        tmp_23_reg_624 <= s_fu_432_p2[32'd39];
        tmp_23_reg_624_pp0_iter10_reg <= tmp_23_reg_624_pp0_iter9_reg;
        tmp_23_reg_624_pp0_iter5_reg <= tmp_23_reg_624;
        tmp_23_reg_624_pp0_iter6_reg <= tmp_23_reg_624_pp0_iter5_reg;
        tmp_23_reg_624_pp0_iter7_reg <= tmp_23_reg_624_pp0_iter6_reg;
        tmp_23_reg_624_pp0_iter8_reg <= tmp_23_reg_624_pp0_iter7_reg;
        tmp_23_reg_624_pp0_iter9_reg <= tmp_23_reg_624_pp0_iter8_reg;
    end
end

always @ (*) begin
    if (((icmp_ln89_fu_187_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten14_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten14_load = indvar_flatten14_fu_116;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_108;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        fm_B_ce0_local = 1'b1;
    end else begin
        fm_B_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        pool_res_ce0_local = 1'b1;
    end else begin
        pool_res_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln91_1_reg_605_pp0_iter10_reg == 1'd1) & (icmp_ln92_1_reg_601_pp0_iter10_reg == 1'd1))) begin
        pool_res_we0_local = 1'b1;
    end else begin
        pool_res_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln89_1_fu_193_p2 = (ap_sig_allocacmp_indvar_flatten14_load + 8'd1);

assign add_ln89_fu_238_p2 = (c_fu_112 + 3'd1);

assign add_ln91_1_fu_205_p2 = (ap_sig_allocacmp_indvar_flatten_load + 6'd1);

assign add_ln91_fu_275_p2 = (select_ln89_fu_244_p3 + 3'd1);

assign add_ln92_fu_346_p2 = (w_mid2_fu_286_p3 + 3'd1);

assign add_ln94_1_fu_390_p2 = (zext_ln94_fu_387_p1 + mul_ln_fu_379_p4);

assign add_ln94_fu_340_p2 = (zext_ln91_fu_310_p1 + sub_ln94_fu_334_p2);

assign and_ln89_fu_262_p2 = (xor_ln89_fu_251_p2 & icmp_ln92_fu_256_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_281_p2 = (icmp_ln91_reg_576 | and_ln89_fu_262_p2);

assign fm_B_address0 = zext_ln94_1_fu_406_p1;

assign fm_B_ce0 = fm_B_ce0_local;

assign grp_fu_146_p1 = 113'd128102389400760776;

assign icmp_ln89_fu_187_p2 = ((ap_sig_allocacmp_indvar_flatten14_load == 8'd216) ? 1'b1 : 1'b0);

assign icmp_ln91_1_fu_358_p2 = ((select_ln91_fu_294_p3 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln91_fu_199_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 6'd36) ? 1'b1 : 1'b0);

assign icmp_ln92_1_fu_352_p2 = ((add_ln92_fu_346_p2 == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln92_fu_256_p2 = ((w_fu_100 == 3'd6) ? 1'b1 : 1'b0);

assign lshr_ln_fu_396_p4 = {{add_ln94_1_fu_390_p2[8:1]}};

assign mul_ln_fu_379_p4 = {{{select_ln91_reg_590}, {select_ln91_reg_590}}, {3'd0}};

assign p_shl_fu_314_p3 = {{w_mid2_fu_286_p3}, {4'd0}};

assign pool_res_address0 = zext_ln96_fu_526_p1;

assign pool_res_ce0 = pool_res_ce0_local;

assign pool_res_d0 = select_ln96_1_fu_519_p3;

assign pool_res_we0 = pool_res_we0_local;

assign s_fu_432_p2 = ($signed(sext_ln94_fu_428_p1) + $signed(select_ln89_1_fu_414_p3));

assign select_ln89_1_fu_414_p3 = ((icmp_ln91_reg_576_pp0_iter3_reg[0:0] == 1'b1) ? 40'd0 : s_8_fu_96);

assign select_ln89_2_fu_268_p3 = ((icmp_ln91_reg_576[0:0] == 1'b1) ? add_ln89_fu_238_p2 : c_fu_112);

assign select_ln89_fu_244_p3 = ((icmp_ln91_reg_576[0:0] == 1'b1) ? 3'd0 : h_fu_104);

assign select_ln91_1_fu_211_p3 = ((icmp_ln91_fu_199_p2[0:0] == 1'b1) ? 6'd1 : add_ln91_1_fu_205_p2);

assign select_ln91_fu_294_p3 = ((and_ln89_fu_262_p2[0:0] == 1'b1) ? add_ln91_fu_275_p2 : select_ln89_fu_244_p3);

assign select_ln96_1_fu_519_p3 = ((tmp_23_reg_624_pp0_iter10_reg[0:0] == 1'b1) ? tmp_s_fu_509_p4 : tmp_1_reg_650);

assign select_ln96_fu_488_p3 = ((tmp_23_reg_624_pp0_iter9_reg[0:0] == 1'b1) ? tmp_10_cast_fu_478_p4 : tmp_11_cast_reg_640);

assign sext_ln94_fu_428_p1 = $signed(shl_ln_fu_421_p3);

assign shl_ln3_fu_451_p3 = {{s_reg_619}, {16'd0}};

assign shl_ln_fu_421_p3 = {{fm_B_load_reg_614}, {8'd0}};

assign sub_ln94_fu_334_p2 = (p_shl_fu_314_p3 - zext_ln94_2_fu_330_p1);

assign sub_ln96_1_fu_504_p2 = (24'd0 - select_ln96_reg_645);

assign sub_ln96_fu_473_p2 = (113'd0 - mul_ln96_reg_635);

assign tmp_10_cast_fu_478_p4 = {{sub_ln96_fu_473_p2[101:78]}};

assign tmp_22_fu_322_p3 = {{w_mid2_fu_286_p3}, {2'd0}};

assign tmp_fu_302_p3 = {{select_ln89_2_fu_268_p3}, {1'd0}};

assign tmp_s_fu_509_p4 = {{sub_ln96_1_fu_504_p2[23:8]}};

assign w_mid2_fu_286_p3 = ((empty_fu_281_p2[0:0] == 1'b1) ? 3'd0 : w_fu_100);

assign xor_ln89_fu_251_p2 = (icmp_ln91_reg_576 ^ 1'd1);

assign zext_ln91_fu_310_p1 = tmp_fu_302_p3;

assign zext_ln94_1_fu_406_p1 = lshr_ln_fu_396_p4;

assign zext_ln94_2_fu_330_p1 = tmp_22_fu_322_p3;

assign zext_ln94_fu_387_p1 = add_ln94_reg_596;

assign zext_ln96_fu_526_p1 = select_ln89_2_reg_585_pp0_iter10_reg;

always @ (posedge ap_clk) begin
    add_ln94_reg_596[0] <= 1'b0;
end

endmodule //mobilenet_top_gap_6_6_6_s
