// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mobilenet_top_dw_conv_Pipeline_VITIS_LOOP_61_2_VITIS_LOOP_62_3_VITIS_LOOP_64_4_VITIS_LOOP_65_5_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_cast,
        zext_ln60,
        c,
        fm_A_address0,
        fm_A_ce0,
        fm_A_we0,
        fm_A_d0,
        fm_exp_address0,
        fm_exp_ce0,
        fm_exp_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [25:0] s_cast;
input  [4:0] zext_ln60;
input  [4:0] c;
output  [13:0] fm_A_address0;
output   fm_A_ce0;
output   fm_A_we0;
output  [10:0] fm_A_d0;
output  [14:0] fm_exp_address0;
output   fm_exp_ce0;
input  [15:0] fm_exp_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln61_fu_289_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [9:0] p_features_features_2_conv_conv_1_conv_1_0_weight_quant_export_handler_Constant_1_address0;
wire   [7:0] p_features_features_2_conv_conv_1_conv_1_0_weight_quant_export_handler_Constant_1_q0;
wire    ap_block_pp0_stage0_11001;
wire   [6:0] zext_ln60_cast_fu_235_p1;
reg   [6:0] zext_ln60_cast_reg_1013;
wire  signed [39:0] s_cast_cast_fu_239_p1;
reg  signed [39:0] s_cast_cast_reg_1018;
reg   [0:0] icmp_ln61_reg_1024;
wire   [0:0] icmp_ln62_fu_301_p2;
reg   [0:0] icmp_ln62_reg_1028;
reg   [0:0] icmp_ln62_reg_1028_pp0_iter1_reg;
reg   [0:0] icmp_ln62_reg_1028_pp0_iter2_reg;
reg   [0:0] icmp_ln62_reg_1028_pp0_iter3_reg;
reg   [0:0] icmp_ln62_reg_1028_pp0_iter4_reg;
reg   [0:0] icmp_ln62_reg_1028_pp0_iter5_reg;
wire   [0:0] exitcond_flatten_mid240_fu_364_p2;
reg   [0:0] exitcond_flatten_mid240_reg_1039;
reg   [0:0] exitcond_flatten_mid240_reg_1039_pp0_iter2_reg;
reg   [0:0] exitcond_flatten_mid240_reg_1039_pp0_iter3_reg;
reg   [0:0] exitcond_flatten_mid240_reg_1039_pp0_iter4_reg;
reg   [0:0] exitcond_flatten_mid240_reg_1039_pp0_iter5_reg;
wire   [0:0] empty_fu_376_p2;
reg   [0:0] empty_reg_1044;
wire   [0:0] icmp_ln65_mid213_fu_398_p2;
reg   [0:0] icmp_ln65_mid213_reg_1049;
wire   [2:0] select_ln62_fu_404_p3;
reg   [2:0] select_ln62_reg_1054;
wire   [1:0] kw_mid2_fu_423_p3;
reg   [1:0] kw_mid2_reg_1061;
reg   [1:0] kw_mid2_reg_1061_pp0_iter2_reg;
wire   [0:0] icmp_ln65_1_fu_437_p2;
reg   [0:0] icmp_ln65_1_reg_1067;
reg   [0:0] icmp_ln65_1_reg_1067_pp0_iter2_reg;
reg   [0:0] icmp_ln65_1_reg_1067_pp0_iter3_reg;
reg   [0:0] icmp_ln65_1_reg_1067_pp0_iter4_reg;
reg   [0:0] icmp_ln65_1_reg_1067_pp0_iter5_reg;
reg   [0:0] icmp_ln65_1_reg_1067_pp0_iter6_reg;
wire   [4:0] empty_68_fu_585_p2;
reg   [4:0] empty_68_reg_1071;
wire   [6:0] empty_69_fu_591_p2;
reg   [6:0] empty_69_reg_1078;
wire   [5:0] empty_70_fu_597_p1;
reg   [5:0] empty_70_reg_1083;
wire   [0:0] icmp_ln68_fu_616_p2;
reg   [0:0] icmp_ln68_reg_1088;
reg   [0:0] icmp_ln68_reg_1088_pp0_iter3_reg;
reg   [0:0] icmp_ln68_reg_1088_pp0_iter4_reg;
reg   [0:0] icmp_ln68_reg_1088_pp0_iter5_reg;
wire   [10:0] add_ln69_fu_648_p2;
reg   [10:0] add_ln69_reg_1093;
wire   [0:0] icmp_ln64_1_fu_654_p2;
reg   [0:0] icmp_ln64_1_reg_1098;
reg   [0:0] icmp_ln64_1_reg_1098_pp0_iter3_reg;
reg   [0:0] icmp_ln64_1_reg_1098_pp0_iter4_reg;
reg   [0:0] icmp_ln64_1_reg_1098_pp0_iter5_reg;
reg   [0:0] icmp_ln64_1_reg_1098_pp0_iter6_reg;
reg   [9:0] lshr_ln71_3_reg_1102;
reg   [9:0] lshr_ln71_3_reg_1102_pp0_iter3_reg;
reg   [9:0] lshr_ln71_3_reg_1102_pp0_iter4_reg;
reg   [9:0] lshr_ln71_3_reg_1102_pp0_iter5_reg;
reg   [9:0] lshr_ln71_3_reg_1102_pp0_iter6_reg;
wire   [0:0] empty_72_fu_736_p2;
reg   [0:0] empty_72_reg_1107;
reg   [0:0] empty_72_reg_1107_pp0_iter4_reg;
reg   [0:0] empty_72_reg_1107_pp0_iter5_reg;
reg   [15:0] fm_exp_load_reg_1122;
reg   [7:0] p_features_features_2_conv_conv_1_conv_1_0_weight_quant_export_handler_Constant_1_2_reg_1127;
wire   [47:0] mul_ln69_fu_231_p2;
reg   [47:0] mul_ln69_reg_1132;
wire   [39:0] s_2_fu_877_p3;
reg   [39:0] s_2_reg_1137;
reg   [15:0] x_reg_1142;
reg   [0:0] tmp_26_reg_1147;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [31:0] zext_ln69_fu_791_p1;
wire    ap_block_pp0_stage0;
wire   [31:0] zext_ln69_1_fu_802_p1;
wire   [31:0] zext_ln71_2_fu_943_p1;
reg   [39:0] s_fu_142;
wire    ap_loop_init;
reg   [1:0] kw_fu_146;
wire   [1:0] add_ln65_fu_431_p2;
reg   [1:0] kh_fu_150;
wire   [1:0] select_ln64_fu_504_p3;
reg   [3:0] indvar_flatten_fu_154;
wire   [3:0] select_ln64_1_fu_449_p3;
reg   [2:0] ow_fu_158;
reg   [6:0] indvar_flatten14_fu_162;
wire   [6:0] select_ln62_1_fu_313_p3;
reg   [6:0] ap_sig_allocacmp_indvar_flatten14_load;
reg   [2:0] oh_fu_166;
wire   [2:0] select_ln61_fu_484_p3;
reg   [8:0] indvar_flatten41_fu_170;
wire   [8:0] add_ln61_1_fu_295_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten41_load;
reg    fm_exp_ce0_local;
reg    p_features_features_2_conv_conv_1_conv_1_0_weight_quant_export_handler_Constant_1_ce0_local;
reg    fm_A_we0_local;
wire   [10:0] select_ln16_fu_934_p3;
reg    fm_A_ce0_local;
wire   [6:0] add_ln62_1_fu_307_p2;
wire   [0:0] icmp_ln64_fu_358_p2;
wire   [0:0] not_exitcond_flatten16_fu_347_p2;
wire   [2:0] ow_mid221_fu_340_p3;
wire   [0:0] exitcond_flatten_not_fu_381_p2;
wire   [0:0] icmp_ln65_fu_352_p2;
wire   [0:0] icmp_ln65_mid236_fu_392_p2;
wire   [0:0] not_exitcond_flatten_mid240_fu_387_p2;
wire   [2:0] add_ln62_fu_370_p2;
wire   [0:0] empty_65_fu_412_p2;
wire   [0:0] empty_66_fu_418_p2;
wire   [3:0] add_ln64_1_fu_443_p2;
wire   [2:0] add_ln61_fu_478_p2;
wire   [1:0] kh_mid26_fu_491_p3;
wire   [1:0] add_ln64_fu_498_p2;
wire   [6:0] p_shl15_fu_511_p3;
wire   [5:0] tmp_s_fu_523_p3;
wire   [3:0] tmp_2_fu_538_p3;
wire   [3:0] tmp_3_fu_560_p3;
wire   [1:0] tmp_fu_575_p2;
wire  signed [4:0] tmp_cast_fu_581_p1;
wire   [4:0] p_cast8_fu_546_p1;
wire   [6:0] zext_ln64_1_fu_571_p1;
wire   [6:0] empty_67_fu_518_p2;
wire   [1:0] add_ln67_1_fu_601_p2;
wire  signed [4:0] sext_ln67_fu_606_p1;
wire   [4:0] zext_ln64_fu_567_p1;
wire   [4:0] add_ln67_fu_610_p2;
wire   [8:0] tmp_25_fu_630_p3;
wire   [10:0] p_shl10_fu_622_p3;
wire  signed [10:0] sext_ln69_fu_638_p1;
wire   [10:0] zext_ln61_fu_530_p1;
wire   [10:0] sub_ln69_fu_642_p2;
wire   [6:0] tmp_27_fu_667_p3;
wire   [8:0] p_shl_fu_660_p3;
wire   [8:0] zext_ln71_1_fu_674_p1;
wire   [8:0] zext_ln61_1_fu_534_p1;
wire   [8:0] sub_ln71_fu_678_p2;
wire   [8:0] add_ln71_fu_684_p2;
wire   [10:0] zext_ln71_fu_690_p1;
wire   [10:0] mul_ln_fu_550_p4;
wire   [10:0] add_ln71_1_fu_694_p2;
wire   [7:0] p_shl14_fu_723_p3;
wire   [7:0] p_cast9_fu_720_p1;
wire   [10:0] tmp_24_fu_748_p3;
wire   [13:0] p_shl12_fu_741_p3;
wire  signed [13:0] sext_ln65_fu_755_p1;
wire  signed [13:0] sext_ln69_1_fu_768_p1;
wire   [13:0] add_ln65_1_fu_759_p2;
wire   [13:0] add_ln69_1_fu_771_p2;
wire   [12:0] trunc_ln_fu_777_p4;
wire  signed [14:0] sext_ln69_2_fu_787_p1;
wire   [7:0] zext_ln65_fu_765_p1;
wire   [7:0] empty_71_fu_730_p2;
wire   [7:0] add_ln69_2_fu_796_p2;
wire  signed [23:0] shl_ln_fu_807_p3;
wire  signed [23:0] shl_ln69_3_fu_814_p3;
wire   [39:0] s_12_mid226_fu_834_p3;
wire   [39:0] s_12_mid29_fu_840_p3;
wire   [55:0] shl_ln69_4_fu_850_p3;
wire  signed [55:0] sext_ln69_5_fu_858_p1;
wire   [55:0] add_ln69_3_fu_861_p2;
wire   [0:0] and_ln68_fu_846_p2;
wire   [39:0] s_9_fu_867_p4;
wire   [0:0] icmp_ln17_fu_917_p2;
wire   [0:0] or_ln16_fu_929_p2;
wire   [10:0] select_ln16_3_fu_922_p3;
wire   [10:0] trunc_ln9_fu_908_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 s_fu_142 = 40'd0;
#0 kw_fu_146 = 2'd0;
#0 kh_fu_150 = 2'd0;
#0 indvar_flatten_fu_154 = 4'd0;
#0 ow_fu_158 = 3'd0;
#0 indvar_flatten14_fu_162 = 7'd0;
#0 oh_fu_166 = 3'd0;
#0 indvar_flatten41_fu_170 = 9'd0;
#0 ap_done_reg = 1'b0;
end

mobilenet_top_dw_conv_Pipeline_VITIS_LOOP_61_2_VITIS_LOOP_62_3_VITIS_LOOP_64_4_VITIS_LOOP_6eOg #(
    .DataWidth( 8 ),
    .AddressRange( 864 ),
    .AddressWidth( 10 ))
p_features_features_2_conv_conv_1_conv_1_0_weight_quant_export_handler_Constant_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_features_features_2_conv_conv_1_conv_1_0_weight_quant_export_handler_Constant_1_address0),
    .ce0(p_features_features_2_conv_conv_1_conv_1_0_weight_quant_export_handler_Constant_1_ce0_local),
    .q0(p_features_features_2_conv_conv_1_conv_1_0_weight_quant_export_handler_Constant_1_q0)
);

mobilenet_top_mul_24s_24s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 48 ))
mul_24s_24s_48_1_1_U37(
    .din0(shl_ln69_3_fu_814_p3),
    .din1(shl_ln_fu_807_p3),
    .dout(mul_ln69_fu_231_p2)
);

mobilenet_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln61_fu_289_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten14_fu_162 <= select_ln62_1_fu_313_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten14_fu_162 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln61_fu_289_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten41_fu_170 <= add_ln61_1_fu_295_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten41_fu_170 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_154 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln61_reg_1024 == 1'd0))) begin
            indvar_flatten_fu_154 <= select_ln64_1_fu_449_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            kh_fu_150 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            kh_fu_150 <= select_ln64_fu_504_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            kw_fu_146 <= 2'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln61_reg_1024 == 1'd0))) begin
            kw_fu_146 <= add_ln65_fu_431_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            oh_fu_166 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            oh_fu_166 <= select_ln61_fu_484_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ow_fu_158 <= 3'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln61_reg_1024 == 1'd0))) begin
            ow_fu_158 <= select_ln62_fu_404_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            s_fu_142 <= s_cast_cast_fu_239_p1;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            s_fu_142 <= s_2_fu_877_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln69_reg_1093[10 : 1] <= add_ln69_fu_648_p2[10 : 1];
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        empty_68_reg_1071 <= empty_68_fu_585_p2;
        empty_69_reg_1078 <= empty_69_fu_591_p2;
        empty_70_reg_1083 <= empty_70_fu_597_p1;
        empty_72_reg_1107 <= empty_72_fu_736_p2;
        empty_72_reg_1107_pp0_iter4_reg <= empty_72_reg_1107;
        empty_72_reg_1107_pp0_iter5_reg <= empty_72_reg_1107_pp0_iter4_reg;
        exitcond_flatten_mid240_reg_1039_pp0_iter2_reg <= exitcond_flatten_mid240_reg_1039;
        exitcond_flatten_mid240_reg_1039_pp0_iter3_reg <= exitcond_flatten_mid240_reg_1039_pp0_iter2_reg;
        exitcond_flatten_mid240_reg_1039_pp0_iter4_reg <= exitcond_flatten_mid240_reg_1039_pp0_iter3_reg;
        exitcond_flatten_mid240_reg_1039_pp0_iter5_reg <= exitcond_flatten_mid240_reg_1039_pp0_iter4_reg;
        fm_exp_load_reg_1122 <= fm_exp_q0;
        icmp_ln62_reg_1028_pp0_iter2_reg <= icmp_ln62_reg_1028_pp0_iter1_reg;
        icmp_ln62_reg_1028_pp0_iter3_reg <= icmp_ln62_reg_1028_pp0_iter2_reg;
        icmp_ln62_reg_1028_pp0_iter4_reg <= icmp_ln62_reg_1028_pp0_iter3_reg;
        icmp_ln62_reg_1028_pp0_iter5_reg <= icmp_ln62_reg_1028_pp0_iter4_reg;
        icmp_ln64_1_reg_1098 <= icmp_ln64_1_fu_654_p2;
        icmp_ln64_1_reg_1098_pp0_iter3_reg <= icmp_ln64_1_reg_1098;
        icmp_ln64_1_reg_1098_pp0_iter4_reg <= icmp_ln64_1_reg_1098_pp0_iter3_reg;
        icmp_ln64_1_reg_1098_pp0_iter5_reg <= icmp_ln64_1_reg_1098_pp0_iter4_reg;
        icmp_ln64_1_reg_1098_pp0_iter6_reg <= icmp_ln64_1_reg_1098_pp0_iter5_reg;
        icmp_ln65_1_reg_1067_pp0_iter2_reg <= icmp_ln65_1_reg_1067;
        icmp_ln65_1_reg_1067_pp0_iter3_reg <= icmp_ln65_1_reg_1067_pp0_iter2_reg;
        icmp_ln65_1_reg_1067_pp0_iter4_reg <= icmp_ln65_1_reg_1067_pp0_iter3_reg;
        icmp_ln65_1_reg_1067_pp0_iter5_reg <= icmp_ln65_1_reg_1067_pp0_iter4_reg;
        icmp_ln65_1_reg_1067_pp0_iter6_reg <= icmp_ln65_1_reg_1067_pp0_iter5_reg;
        icmp_ln68_reg_1088 <= icmp_ln68_fu_616_p2;
        icmp_ln68_reg_1088_pp0_iter3_reg <= icmp_ln68_reg_1088;
        icmp_ln68_reg_1088_pp0_iter4_reg <= icmp_ln68_reg_1088_pp0_iter3_reg;
        icmp_ln68_reg_1088_pp0_iter5_reg <= icmp_ln68_reg_1088_pp0_iter4_reg;
        kw_mid2_reg_1061_pp0_iter2_reg <= kw_mid2_reg_1061;
        lshr_ln71_3_reg_1102 <= {{add_ln71_1_fu_694_p2[10:1]}};
        lshr_ln71_3_reg_1102_pp0_iter3_reg <= lshr_ln71_3_reg_1102;
        lshr_ln71_3_reg_1102_pp0_iter4_reg <= lshr_ln71_3_reg_1102_pp0_iter3_reg;
        lshr_ln71_3_reg_1102_pp0_iter5_reg <= lshr_ln71_3_reg_1102_pp0_iter4_reg;
        lshr_ln71_3_reg_1102_pp0_iter6_reg <= lshr_ln71_3_reg_1102_pp0_iter5_reg;
        mul_ln69_reg_1132 <= mul_ln69_fu_231_p2;
        p_features_features_2_conv_conv_1_conv_1_0_weight_quant_export_handler_Constant_1_2_reg_1127 <= p_features_features_2_conv_conv_1_conv_1_0_weight_quant_export_handler_Constant_1_q0;
        s_2_reg_1137 <= s_2_fu_877_p3;
        tmp_26_reg_1147 <= s_2_fu_877_p3[32'd23];
        x_reg_1142 <= {{s_2_fu_877_p3[23:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        empty_reg_1044 <= empty_fu_376_p2;
        exitcond_flatten_mid240_reg_1039 <= exitcond_flatten_mid240_fu_364_p2;
        icmp_ln61_reg_1024 <= icmp_ln61_fu_289_p2;
        icmp_ln62_reg_1028 <= icmp_ln62_fu_301_p2;
        icmp_ln62_reg_1028_pp0_iter1_reg <= icmp_ln62_reg_1028;
        icmp_ln65_1_reg_1067 <= icmp_ln65_1_fu_437_p2;
        icmp_ln65_mid213_reg_1049 <= icmp_ln65_mid213_fu_398_p2;
        kw_mid2_reg_1061 <= kw_mid2_fu_423_p3;
        s_cast_cast_reg_1018 <= s_cast_cast_fu_239_p1;
        select_ln62_reg_1054 <= select_ln62_fu_404_p3;
        zext_ln60_cast_reg_1013[4 : 0] <= zext_ln60_cast_fu_235_p1[4 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln61_fu_289_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln61_reg_1024 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten14_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten14_load = indvar_flatten14_fu_162;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten41_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten41_load = indvar_flatten41_fu_170;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        fm_A_ce0_local = 1'b1;
    end else begin
        fm_A_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln64_1_reg_1098_pp0_iter6_reg == 1'd1) & (icmp_ln65_1_reg_1067_pp0_iter6_reg == 1'd1))) begin
        fm_A_we0_local = 1'b1;
    end else begin
        fm_A_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        fm_exp_ce0_local = 1'b1;
    end else begin
        fm_exp_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_features_features_2_conv_conv_1_conv_1_0_weight_quant_export_handler_Constant_1_ce0_local = 1'b1;
    end else begin
        p_features_features_2_conv_conv_1_conv_1_0_weight_quant_export_handler_Constant_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln61_1_fu_295_p2 = (ap_sig_allocacmp_indvar_flatten41_load + 9'd1);

assign add_ln61_fu_478_p2 = (oh_fu_166 + 3'd1);

assign add_ln62_1_fu_307_p2 = (ap_sig_allocacmp_indvar_flatten14_load + 7'd1);

assign add_ln62_fu_370_p2 = (ow_mid221_fu_340_p3 + 3'd1);

assign add_ln64_1_fu_443_p2 = (indvar_flatten_fu_154 + 4'd1);

assign add_ln64_fu_498_p2 = (kh_mid26_fu_491_p3 + 2'd1);

assign add_ln65_1_fu_759_p2 = ($signed(p_shl12_fu_741_p3) + $signed(sext_ln65_fu_755_p1));

assign add_ln65_fu_431_p2 = (kw_mid2_fu_423_p3 + 2'd1);

assign add_ln67_1_fu_601_p2 = ($signed(kw_mid2_reg_1061) + $signed(2'd3));

assign add_ln67_fu_610_p2 = ($signed(sext_ln67_fu_606_p1) + $signed(zext_ln64_fu_567_p1));

assign add_ln69_1_fu_771_p2 = ($signed(sext_ln69_1_fu_768_p1) + $signed(add_ln65_1_fu_759_p2));

assign add_ln69_2_fu_796_p2 = (zext_ln65_fu_765_p1 + empty_71_fu_730_p2);

assign add_ln69_3_fu_861_p2 = ($signed(shl_ln69_4_fu_850_p3) + $signed(sext_ln69_5_fu_858_p1));

assign add_ln69_fu_648_p2 = (zext_ln61_fu_530_p1 + sub_ln69_fu_642_p2);

assign add_ln71_1_fu_694_p2 = (zext_ln71_fu_690_p1 + mul_ln_fu_550_p4);

assign add_ln71_fu_684_p2 = (zext_ln61_1_fu_534_p1 + sub_ln71_fu_678_p2);

assign and_ln68_fu_846_p2 = (icmp_ln68_reg_1088_pp0_iter5_reg & empty_72_reg_1107_pp0_iter5_reg);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_65_fu_412_p2 = (icmp_ln65_mid213_fu_398_p2 | exitcond_flatten_mid240_fu_364_p2);

assign empty_66_fu_418_p2 = (icmp_ln62_reg_1028 | empty_65_fu_412_p2);

assign empty_67_fu_518_p2 = (p_shl15_fu_511_p3 - zext_ln60_cast_reg_1013);

assign empty_68_fu_585_p2 = ($signed(tmp_cast_fu_581_p1) + $signed(p_cast8_fu_546_p1));

assign empty_69_fu_591_p2 = (zext_ln64_1_fu_571_p1 + empty_67_fu_518_p2);

assign empty_70_fu_597_p1 = empty_69_fu_591_p2[5:0];

assign empty_71_fu_730_p2 = (p_shl14_fu_723_p3 - p_cast9_fu_720_p1);

assign empty_72_fu_736_p2 = ((empty_68_reg_1071 < 5'd12) ? 1'b1 : 1'b0);

assign empty_fu_376_p2 = (icmp_ln62_reg_1028 | exitcond_flatten_mid240_fu_364_p2);

assign exitcond_flatten_mid240_fu_364_p2 = (not_exitcond_flatten16_fu_347_p2 & icmp_ln64_fu_358_p2);

assign exitcond_flatten_not_fu_381_p2 = (icmp_ln64_fu_358_p2 ^ 1'd1);

assign fm_A_address0 = zext_ln71_2_fu_943_p1;

assign fm_A_ce0 = fm_A_ce0_local;

assign fm_A_d0 = select_ln16_fu_934_p3;

assign fm_A_we0 = fm_A_we0_local;

assign fm_exp_address0 = zext_ln69_fu_791_p1;

assign fm_exp_ce0 = fm_exp_ce0_local;

assign icmp_ln17_fu_917_p2 = (($signed(x_reg_1142) > $signed(16'd1536)) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_289_p2 = ((ap_sig_allocacmp_indvar_flatten41_load == 9'd324) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_301_p2 = ((ap_sig_allocacmp_indvar_flatten14_load == 7'd54) ? 1'b1 : 1'b0);

assign icmp_ln64_1_fu_654_p2 = ((select_ln64_fu_504_p3 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_358_p2 = ((indvar_flatten_fu_154 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln65_1_fu_437_p2 = ((add_ln65_fu_431_p2 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_352_p2 = ((kw_fu_146 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln65_mid213_fu_398_p2 = (not_exitcond_flatten_mid240_fu_387_p2 & icmp_ln65_mid236_fu_392_p2);

assign icmp_ln65_mid236_fu_392_p2 = (not_exitcond_flatten16_fu_347_p2 & icmp_ln65_fu_352_p2);

assign icmp_ln68_fu_616_p2 = ((add_ln67_fu_610_p2 < 5'd12) ? 1'b1 : 1'b0);

assign kh_mid26_fu_491_p3 = ((empty_reg_1044[0:0] == 1'b1) ? 2'd0 : kh_fu_150);

assign kw_mid2_fu_423_p3 = ((empty_66_fu_418_p2[0:0] == 1'b1) ? 2'd0 : kw_fu_146);

assign mul_ln_fu_550_p4 = {{{select_ln61_fu_484_p3}, {select_ln61_fu_484_p3}}, {5'd0}};

assign not_exitcond_flatten16_fu_347_p2 = (icmp_ln62_reg_1028 ^ 1'd1);

assign not_exitcond_flatten_mid240_fu_387_p2 = (icmp_ln62_reg_1028 | exitcond_flatten_not_fu_381_p2);

assign or_ln16_fu_929_p2 = (tmp_26_reg_1147 | icmp_ln17_fu_917_p2);

assign ow_mid221_fu_340_p3 = ((icmp_ln62_reg_1028[0:0] == 1'b1) ? 3'd0 : ow_fu_158);

assign p_cast8_fu_546_p1 = tmp_2_fu_538_p3;

assign p_cast9_fu_720_p1 = empty_69_reg_1078;

assign p_features_features_2_conv_conv_1_conv_1_0_weight_quant_export_handler_Constant_1_address0 = zext_ln69_1_fu_802_p1;

assign p_shl10_fu_622_p3 = {{add_ln67_fu_610_p2}, {6'd0}};

assign p_shl12_fu_741_p3 = {{empty_68_reg_1071}, {9'd0}};

assign p_shl14_fu_723_p3 = {{empty_70_reg_1083}, {2'd0}};

assign p_shl15_fu_511_p3 = {{zext_ln60}, {2'd0}};

assign p_shl_fu_660_p3 = {{select_ln62_reg_1054}, {6'd0}};

assign s_12_mid226_fu_834_p3 = ((icmp_ln62_reg_1028_pp0_iter5_reg[0:0] == 1'b1) ? s_cast_cast_reg_1018 : s_fu_142);

assign s_12_mid29_fu_840_p3 = ((exitcond_flatten_mid240_reg_1039_pp0_iter5_reg[0:0] == 1'b1) ? s_cast_cast_reg_1018 : s_12_mid226_fu_834_p3);

assign s_2_fu_877_p3 = ((and_ln68_fu_846_p2[0:0] == 1'b1) ? s_9_fu_867_p4 : s_12_mid29_fu_840_p3);

assign s_9_fu_867_p4 = {{add_ln69_3_fu_861_p2[55:16]}};

assign s_cast_cast_fu_239_p1 = $signed(s_cast);

assign select_ln16_3_fu_922_p3 = ((tmp_26_reg_1147[0:0] == 1'b1) ? 11'd0 : 11'd1536);

assign select_ln16_fu_934_p3 = ((or_ln16_fu_929_p2[0:0] == 1'b1) ? select_ln16_3_fu_922_p3 : trunc_ln9_fu_908_p4);

assign select_ln61_fu_484_p3 = ((icmp_ln62_reg_1028_pp0_iter1_reg[0:0] == 1'b1) ? add_ln61_fu_478_p2 : oh_fu_166);

assign select_ln62_1_fu_313_p3 = ((icmp_ln62_fu_301_p2[0:0] == 1'b1) ? 7'd1 : add_ln62_1_fu_307_p2);

assign select_ln62_fu_404_p3 = ((exitcond_flatten_mid240_fu_364_p2[0:0] == 1'b1) ? add_ln62_fu_370_p2 : ow_mid221_fu_340_p3);

assign select_ln64_1_fu_449_p3 = ((empty_fu_376_p2[0:0] == 1'b1) ? 4'd1 : add_ln64_1_fu_443_p2);

assign select_ln64_fu_504_p3 = ((icmp_ln65_mid213_reg_1049[0:0] == 1'b1) ? add_ln64_fu_498_p2 : kh_mid26_fu_491_p3);

assign sext_ln65_fu_755_p1 = $signed(tmp_24_fu_748_p3);

assign sext_ln67_fu_606_p1 = $signed(add_ln67_1_fu_601_p2);

assign sext_ln69_1_fu_768_p1 = $signed(add_ln69_reg_1093);

assign sext_ln69_2_fu_787_p1 = $signed(trunc_ln_fu_777_p4);

assign sext_ln69_5_fu_858_p1 = $signed(mul_ln69_reg_1132);

assign sext_ln69_fu_638_p1 = $signed(tmp_25_fu_630_p3);

assign shl_ln69_3_fu_814_p3 = {{p_features_features_2_conv_conv_1_conv_1_0_weight_quant_export_handler_Constant_1_2_reg_1127}, {16'd0}};

assign shl_ln69_4_fu_850_p3 = {{s_12_mid29_fu_840_p3}, {16'd0}};

assign shl_ln_fu_807_p3 = {{fm_exp_load_reg_1122}, {8'd0}};

assign sub_ln69_fu_642_p2 = ($signed(p_shl10_fu_622_p3) - $signed(sext_ln69_fu_638_p1));

assign sub_ln71_fu_678_p2 = (p_shl_fu_660_p3 - zext_ln71_1_fu_674_p1);

assign tmp_24_fu_748_p3 = {{empty_68_reg_1071}, {6'd0}};

assign tmp_25_fu_630_p3 = {{add_ln67_fu_610_p2}, {4'd0}};

assign tmp_27_fu_667_p3 = {{select_ln62_reg_1054}, {4'd0}};

assign tmp_2_fu_538_p3 = {{select_ln61_fu_484_p3}, {1'd0}};

assign tmp_3_fu_560_p3 = {{select_ln62_reg_1054}, {1'd0}};

assign tmp_cast_fu_581_p1 = $signed(tmp_fu_575_p2);

assign tmp_fu_575_p2 = ($signed(select_ln64_fu_504_p3) + $signed(2'd3));

assign tmp_s_fu_523_p3 = {{c}, {1'd0}};

assign trunc_ln9_fu_908_p4 = {{s_2_reg_1137[18:8]}};

assign trunc_ln_fu_777_p4 = {{add_ln69_1_fu_771_p2[13:1]}};

assign zext_ln60_cast_fu_235_p1 = zext_ln60;

assign zext_ln61_1_fu_534_p1 = tmp_s_fu_523_p3;

assign zext_ln61_fu_530_p1 = tmp_s_fu_523_p3;

assign zext_ln64_1_fu_571_p1 = select_ln64_fu_504_p3;

assign zext_ln64_fu_567_p1 = tmp_3_fu_560_p3;

assign zext_ln65_fu_765_p1 = kw_mid2_reg_1061_pp0_iter2_reg;

assign zext_ln69_1_fu_802_p1 = add_ln69_2_fu_796_p2;

assign zext_ln69_fu_791_p1 = $unsigned(sext_ln69_2_fu_787_p1);

assign zext_ln71_1_fu_674_p1 = tmp_27_fu_667_p3;

assign zext_ln71_2_fu_943_p1 = lshr_ln71_3_reg_1102_pp0_iter6_reg;

assign zext_ln71_fu_690_p1 = add_ln71_fu_684_p2;

always @ (posedge ap_clk) begin
    zext_ln60_cast_reg_1013[6:5] <= 2'b00;
    add_ln69_reg_1093[0] <= 1'b0;
end

endmodule //mobilenet_top_dw_conv_Pipeline_VITIS_LOOP_61_2_VITIS_LOOP_62_3_VITIS_LOOP_64_4_VITIS_LOOP_65_5_2
